### ISSUE TITLE
Support for NMEA $GNRMC etc

### ISSUE THREAD

**Issue by Leethal60** [tomojitakasu/RTKLIB#100]
Hi,

I just downloaded RTKLIB and as a newbie I first ran Plot. This worked fine with an uBlox LEA-6H which puts out NMEA stings in the $GPGGA etc. I then tried a uBlox M8N which puts out the stings in the $GNGGA format which didn't work. Is the Plot software unable to parse these strings or is there something I need to do.

Lee.

**Comment by tomojitakasu** [comment]
Currently it only supports $GPRMC and $GPGGA. Use $GPGGA instead.

**Comment by Leethal60** [comment]
Can a uBlox M8N be configured in uCentre to do this? Is this done in messages? I don't have one in front of me at the moment but will try tomorrow.
