### ISSUE TITLE
RTKNAVI vs RTKRCV

### ISSUE THREAD

**Issue by MKlimenko** [tomojitakasu/RTKLIB#114]
Hello, I'd like to use this software of SoC's ARM CPU. But before trying to build it for ARM, I try to build rtkrcv in Linux to test it with the rtklibsamples. 
Are their config files the same? Can I use the one from the samples for the rtknavi with the rtkrcv?

**Comment by tomojitakasu** [comment]
No.
A config file for RTKRCV has to contain additional settings from one for RTKNAVI.
The list for the settings is found in rtklib/app/rtkrcv/rtkrcv.c L141 as rcvopts[]:
