### ISSUE TITLE
GPS+GLONASS not working on Raspberry Pi 2

### ISSUE THREAD

**Issue by jfilba** [tomojitakasu/RTKLIB#118]
Currently I am using two NV08C modules to perform RTKGPS using RTKLIB 2.4.2p11 on Kinematic mode.

The problem I am facing is that, while the setup works perfectly on Windows or Linux PCs, when I use the RPi1 or RPi2 it only works if GLONASS is disabled.
When GLONASS is enabled the solution starts to jump back and forth.
This can be seen in the images below:

GPS+GLO:
![gps_glo_rpi](https://cloud.githubusercontent.com/assets/13047985/10976630/1e8dae3e-83ed-11e5-967d-720a792cefc7.jpg)

GPS only:
![gps_rpi](https://cloud.githubusercontent.com/assets/13047985/10976640/32895bfe-83ed-11e5-8103-f1cbfd3f8070.jpg)

The data I am using was recorded using RTKNAVI and streamed using strsvr from file to serial, so the data received on PC or Raspberry Pi should be exactly the same.

The solution starts being OK, but as soon as the first GLONASS ephemeris are received and some GLONASS satellite is added to the valid satellites, the solution starts to jump.

I tried to compile rtkrcv with the default makefile and also adding some compiler options to adapt it to the Raspberry Pi hardware:

CTARGET= -DENAGLO -DENAQZS -DENACMP -DNFREQ=3
CFLAGS = -march=armv7-a -marm -mthumb-interwork -mfloat-abi=hard -mfpu=neon-vfpv4 -mtune=cortex-a7 -O3 -ffast-math -funroll-loops -DNDEBUG -Wno-error -I$(SRC) -I.. -DTRACE $(CTARGET) -g

I checked the computational power used, but it doesn't seem the problem, since it is quite low.

I also tried many different values for the parameters in the configuration file to see if some of them were causing the trouble, but the problem persists. The configuration file I am using is this one:
# rtkrcv options for RTK positioning (2015/10/20, v.2.4.2p11)

console-passwd     =admin
console-timetype   =gpst       # (0:gpst,1:utc,2:jst,3:tow)
console-soltype    =enu        # (0:dms,1:deg,2:xyz,3:enu,4:pyl)
console-solflag    =0          # (0:off,1:std+2:age/ratio/ns)
inpstr1-type       =serial     # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,7:ntripcli,8:ftp,9:http)
inpstr2-type       =serial        # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,7:ntripcli,8:ftp,9:http)
inpstr3-type       =off        # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,7:ntripcli,8:ftp,9:http)
inpstr1-path       =ttyUSB0:115200:8:n:1:off    #rover
inpstr2-path       =ttyUSB1:115200:8:n:1:off    #base
inpstr3-path       =
inpstr1-format     =nvs       # (0:rtcm2,1:rtcm3,2:oem4,3:oem3,4:ubx,5:ss2,6:hemis,7:skytraq,8:sp3)
inpstr2-format     =nvs      # (0:rtcm2,1:rtcm3,2:oem4,3:oem3,4:ubx,5:ss2,6:hemis,7:skytraq,8:sp3)
inpstr3-format     =rtcm3      # (0:rtcm2,1:rtcm3,2:oem4,3:oem3,4:ubx,5:ss2,6:hemis,7:skytraq,8:sp3)
inpstr2-nmeareq    =off        # (0:off,1:latlon,2:single)
inpstr2-nmealat    =0          # (deg)
inpstr2-nmealon    =0          # (deg)
outstr1-type       =file       # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripsvr)
outstr2-type       =off           # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripsvr)
outstr1-path       =/home/pi/GPS_test/test1/5/RTK.pos
outstr2-path       =
outstr1-format     =enu        # (0:llh,1:xyz,2:enu,3:nmea)
outstr2-format     =enu       # (0:llh,1:xyz,2:enu,3:nmea)
logstr1-type       =file        # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripsvr)
logstr2-type       =file        # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripsvr)
logstr3-type       =off        # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripsvr)
logstr1-path       =/home/pi/GPS_test/test1/5/rover.log
logstr2-path       =/home/pi/GPS_test/test1/5/base.log
logstr3-path       =
misc-svrcycle      =10         # (ms)
misc-timeout       =30000      # (ms)
misc-reconnect     =30000      # (ms)
misc-nmeacycle     =5000       # (ms)
misc-buffsize      =32768      # (bytes)
misc-navmsgsel     =rover      # (0:all,1:rover,1:base,2:corr)
misc-startcmd      =/home/pi/RTKLIB-master/data/rtkstart.sh
misc-stopcmd       =/home/pi/RTKLIB-master/data/rtkshut.sh
file-cmdfile1      =/home/pi/RTKLIB-master/data/nvs_raw_5hz.cmd
file-cmdfile2      =/home/pi/RTKLIB-master/data/nvs_raw_1hz.cmd
file-cmdfile3      =
pos1-posmode       =kinematic     # (0:single,1:dgps,2:kinematic,3:static,4:movingbase,5:fixed,6:ppp-kine,7:ppp-static)
pos1-frequency     =l1       # (1:l1,2:l1+l2,3:l1+l2+l5)
pos1-soltype       =forward    # (0:forward,1:backward,2:combined)
pos1-elmask        =15         # (deg)
pos1-snrmask_r     =on        # (0:off,1:on)
pos1-snrmask_b     =on        # (0:off,1:on)
pos1-snrmask_L1    =35,35,35,35,35,35,35,35,35          # (dBHz)
pos1-dynamics      =off        # (0:off,1:on)
pos1-tidecorr      =off        # (0:off,1:on)
pos1-ionoopt       =brdc       # (0:off,1:brdc,2:sbas,3:dual-freq,4:est-stec)
pos1-tropopt       =saas       # (0:off,1:saas,2:sbas,3:est-ztd,4:est-ztdgrad)
pos1-sateph        =brdc       # (0:brdc,1:precise,2:brdc+sbas,3:brdc+ssrapc,4:brdc+ssrcom)
pos1-posopt5       =on
pos1-exclsats      =           # (prn ...)
pos1-navsys        =5          # (1:gps+2:sbas+4:glo+8:gal+16:qzs+32:comp)
pos2-armode        =continuous        # (0:off,1:continuous,2:instantaneous,3:fix-and-hold)
pos2-gloarmode     =off        # (0:off,1:on,2:autocal)
pos2-arthres       =3
pos2-arlockcnt     =0
pos2-arelmask      =0          # (deg)
pos2-aroutcnt      =5
pos2-arminfix      =10
pos2-slipthres     =0.05       # (m)
pos2-maxage        =30         # (s)
pos2-rejionno      =30         # (m)
pos2-niter         =1
pos2-baselen       =0          # (m)
pos2-basesig       =0          # (m)
out-solformat      =enu        # (0:llh,1:xyz,2:enu,3:nmea)
out-outhead        =on         # (0:off,1:on)
out-outopt         =on        # (0:off,1:on)
out-timesys        =utc       # (0:gpst,1:utc,2:jst)
out-timeform       =hms        # (0:tow,1:hms)
out-timendec       =3
out-degform        =deg        # (0:deg,1:dms)
out-fieldsep       =
out-height         =ellipsoidal # (0:ellipsoidal,1:geodetic)
out-geoid          =internal   # (0:internal,1:egm96,2:egm08_2.5,3:egm08_1,4:gsi2000)
out-solstatic      =all        # (0:all,1:single)
out-nmeaintv1      =0          # (s)
out-nmeaintv2      =0          # (s)
out-outstat        =residual        # (0:off,1:state,2:residual)
stats-errratio     =100
stats-errphase     =0.003      # (m)
stats-errphaseel   =0.003      # (m)
stats-errphasebl   =0          # (m/10km)
stats-errdoppler   =1          # (Hz)
stats-stdbias      =30         # (m)
stats-stdiono      =0.03       # (m)
stats-stdtrop      =0.3        # (m)
stats-prnaccelh    =1          # (m/s^2)
stats-prnaccelv    =0.1        # (m/s^2)
stats-prnbias      =0.0001     # (m)
stats-prniono      =0.001      # (m)
stats-prntrop      =0.0001     # (m)
stats-clkstab      =5e-12      # (s/s)
ant1-postype       =llh        # (0:llh,1:xyz,2:single,3:posfile,4:rinexhead,5:rtcm)
ant1-pos1          =0          # (deg|m)
ant1-pos2          =0          # (deg|m)
ant1-pos3          =0          # (m|m)
ant1-anttype       =
ant1-antdele       =0          # (m)
ant1-antdeln       =0          # (m)
ant1-antdelu       =0          # (m)
ant2-postype       =llh        # (0:llh,1:xyz,2:single,3:posfile,4:rinexhead,5:rtcm)
ant2-pos1          =xxxxxx       # (deg|m)
ant2-pos2          =xxxxxx        # (deg|m)
ant2-pos3          =xxxxxx       # (m|m)
ant2-anttype       =
ant2-antdele       =0          # (m)
ant2-antdeln       =0          # (m)
ant2-antdelu       =0          # (m)
misc-timeinterp    =off        # (0:off,1:on)
misc-sbasatsel     =0          # (0:all)
file-satantfile    =/home/pi/RTKLIB-master/data/igs05.atx
file-rcvantfile    =/home/pi/RTKLIB-master/data/igs05.atx
file-staposfile    =/home/pi/RTKLIB-master/data/station.pos
file-geoidfile     =
file-dcbfile       =/home/pi/RTKLIB-master/data/P1C1_ALL.DCB
file-tempdir       =/home/pi/RTKLIB-master/data/temp
file-geexefile     =
file-solstatfile   =
file-tracefile     =

**Comment by twagler** [comment]
Same problem with the nVidia Jetson board.  Possibly related to ARM vs x86_64 and code portability?

**Comment by thiagodefreitas** [comment]
@twagler, I am from the same team of @jfilba and we are using a NV08C-CSM V4.1 0814

**Comment by Minipada** [comment]
@twagler What gcc version are you using ?

**Comment by Minipada** [comment]
Multiple tests have been done:
clang / 03 compilation: same issues. Memory error appear and program stops on raw message (line 434 nvs.c). It runs with -mno-unaligned-access but the solution jumps like before
clang / 02 compilation: no error but data is less reliable

**Comment by twagler** [comment]
I can't remember at the moment, but it was whatever is in the Fedora 22 repo. I'm assuming 5.x.

**Comment by twagler** [comment]
Has anyone made any progress on this?  I can't imagine we're the only groups trying to use RTKLIB with NVS boards on ARM hardware.  So far between the RPi2, Beaglebone Black, and nVidia Jetson board I have the same results as above even though the same configurations work perfectly on x86_64.

**Comment by tomojitakasu** [comment]
Refer No.130 and try the modification.

http://www.rtklib.com/rtklib_support.htm

**Comment by twagler** [comment]
Thanks, I'll try this out once I get set back up.

**Comment by DaniGPS** [comment]
We have the same problem with the Beaglebone Black. We have fixed the bug #130 by setting the system date and time propertly. However this problem persists in our tests. Anybody knows how to solve this issue?

Thanks in advance

**Comment by twagler** [comment]
The most effective workaround at the moment is to execute on an x86 processor. I've also not been able to get it to work on the pi, Beaglebone Black, or the nVidia Jetson TK1.

**Comment by DaniGPS** [comment]
Hello twagler. Thanks for your reply. Unfortunately it is not possible for us to run rtkrcv in an x86 processor. We hope to get a solution for this issue.

**Comment by DavidKelleySCSC** [comment]
DaniGPS 
    Keep at it, it can be done.   We run successfully on a BBB here with
    no issues, on ubuntu 15.04.  [But we use mostly work with Hemisphere
    and uBlox products, not Septentrio so we have not run into the issue
    of #130]   As I recall the only issue that took lots of time was
    getting the kernel working with combination of the right HW floating
    point and an automotive CAN bus driver libs all sorted out. Seems
    like we were rebuilding the OS for many weeks over this.  This runs
    the 'classic' RTK code base in its 'server' mode on a console.  
    [Aside, here we are likely going to move to a dragon board (another
    ARM processor) to get a little more elbow room. BBB does not lend
    itself to projects where you have more than one or two peripherals
    involved, and we we never have gotten the IMU correctly running over
    the SPI interface for other projects. ]
    Regards,
David Kelley
    
    On 2/24/2016 7:49 AM, DaniGPS wrote:
    
    
      Hello twagler. Thanks for your reply. Unfortunately it is not
        possible for us to run rtkrcv in an x86 processor. We hope to
        get a solution for this issue.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by DaniGPS** [comment]
David,
Thanks for the reply. I will try to rebuild the kernel.
Regards

**Comment by krisklau** [comment]
How did it go? I'm currently also having issues using GLONASS on the beaglebone.

**Comment by DaniGPS** [comment]
Hello krisklau. I could not have a solution yet. I have tried to modify the kernel including the HW floating point and it doesn't work. I am still working on it. 
Regards

**Comment by krisklau** [comment]
@DavidKelleySCSC Would you mind sharing a couple more details about your endeavor that made it work? I understand if you won't/can't give specifics. For instance, did you use -mfloat-abi hard or softfp, and -mfpu=vfpv3 or neon?

Kristian

**Comment by JPimpi** [comment]
I also work with two NVS08C with Pi 2 and the same complications with GLONASS ocurred. Thanks to this thread and others, i managed to compile rtkrcv with -mfloat-abi=hard and the given flags. 
(-march=armv6 -mfpu=vfp -mloat-abi=hard -DENGLO -DENAQZS -DENACMP -DNFREQ=3)
Thanks,
Julian

**Comment by thiagodefreitas** [comment]
@damfernandez Adding this compiler flag has worked for us:
`-funsigned-char`

You can find more information about it, at:

https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html

**Comment by damfernandez** [comment]
Hi @thiagodefreitas, we are trying it using this compiler flag, but the problem persist. Could you share with us the compiler flags and de compiler version that are you using? And other question, what plataform are you using to execute RTKLIB?
We are using a BeagleBone Black (AM335x 1GHz ARM® Cortex-A8) with this compiler flags configuration:
CTARGET= -mfpu=neon -mfloat-abi=hard -ffast-math -funsigned-char -DENAGLO -DENAQZS -DENACMP -DNFREQ=3
CFLAGS = -Wall -O3 -ansi -pedantic -Wno-unused-but-set-variable -I$(SRC) -I.. -DTRACE $(CTARGET) -g
LDLIBS  = -lm -lrt -lpthread

Thanks in advance,
Damián

**Comment by damfernandez** [comment]
Hi guys,
we test some configurations and finally we have achieved a correct position with GLONASS satellites only modifing the next compiler flag:
`-fsigned-char`

Like I said before we are using a BeagleBone Black.

Thanks all for the help,
Damián

**Comment by tomojitakasu** [comment]
Thanks.
The current code implies "char" as "signed char" (as default in many environment).
However, in some platform, "char" is treated as "unsigned char". 
So "char" in the codes should be modified to "signed char" to avoid such machine-dependency.

**Comment by tomojitakasu** [comment]
It is fixed in 2.4.3 b27.
