### ISSUE TITLE
Issue with L2C in convbin

### ISSUE THREAD

**Issue by arty86** [tomojitakasu/RTKLIB#126]
Hello, 
as you know RTCM 3.1 stream can contain only one type of GPS L2 code: L2P or L2C, and L2C has priority.
I use RTCM 3.1 stream for making RINEX 2.11.
If my receiver trackes only GPS L2P CONVBIN makes correct RINEX. 
But if I chose on my receiver setting "L2P or L2C" or "L2P and L2C", then CONVBIN makes RINEX only with L2C, CONVBIN ignores L2P from satellites without L2C.
I've checked stream via GNSSSurfer and BNC, so I can say stream is ok.

Someboby know about it?

Thanks!

**Comment by tomojitakasu** [comment]
Please send a sample RTCM log file to the RTKLIB support address.

rtklib_support(a)gpspp.sakura.ne.jp

Tomoji Takasu.

**Comment by arty86** [comment]
Hello, please check your email.

Thanks,
Arthur

**Comment by tomojitakasu** [comment]
See No.131 of the support information.

http://www.rtklib.com/rtklib_support.htm

Tomoji Takasu

**Comment by arty86** [comment]
Hello, I did what you suggest. But I cannot check it, because now my RINEX files don't have GPS data, only Glonass. 
Example:

 16  1 12 12 59 30.0000000  0  8R 3R11R12R 1R 2R19R18R10

I also checked convbin.exe and rtkconv.exe which I downloaded from web site, and I see the same - RINEX contains only Glonass data.

Thanks,
Arthur

**Comment by tomojitakasu** [comment]
Use 2.4.2 p11.

Tomoji Takasu

**Comment by arty86** [comment]
Works good! Thank you.
BR,
Arthur
