### ISSUE TITLE
Convbin, No GLO obs L1, L2 from RTCM MT1084

### ISSUE THREAD

**Issue by arty86** [tomojitakasu/RTKLIB#129]
Hello Tomoji,

Convbin has an issue with Glonass observation L1 and L2 from RTCM MT1084.
In the RINEX file I see only C1 and C2 obs in the Glonass strings.
Please check your email to find stream file.

BR, Arthur

**Comment by tomojitakasu** [comment]
GLONASS RTCM MSM4 does not contain extended satellite info for FCN (frequency channel number). RTKLIB cannot convert phase-ranges to phase-cycles without the info. Please use MT1085/1087 (MSM5/MSM7) or include MT1020 (GLONASS ephemeris) instead.

Tomoji Takasu
