### ISSUE TITLE
Ublox M8N new firmware 3.01 doesn't work anymore on RTKLIB 2.4.3?

### ISSUE THREAD

**Issue by sobido** [tomojitakasu/RTKLIB#134]
Hi
I recently upgrade my M8N with the new firmware 3.01. If it works on U-center , It seems that RTKLIB does not reconize the GPS anymore. 
Worked fine with Firmware 2.01 of Ublox . 
I came then back to 2.01 .
Did you note this problem too ?

**Comment by tomojitakasu** [comment]
In M8N F/W 3.01, un-official messages TRK-MEAS and TRK-SFRBX are not supported. If you want raw-measurement data by M8N, don't update the F/W.

**Comment by sobido** [comment]
thanks. 
Of course same problem with RTKGPS+ android app.
I came back effectively to the F/W 2.01 to keep RTKLIB and raw measurement.

**Comment by franciskumar2001** [comment]
Hi, I am using ublox8 gps module which gives the raw information and that is not compatible to any rtklib. It is unable to convert to rinex. And there is some measurements drop on my system.any compatible rtk please help me to watch the data on readable mode.
