### ISSUE TITLE
Ublox M8T Navigation Rate problems on Linux

### ISSUE THREAD

**Issue by m91moreira** [tomojitakasu/RTKLIB#138]
Hi,

I'm having some trouble getting RTKLIB to work on the Ublox M8T using linux when the navigation rate is different then 1. Using windows I'm able to get rtk even at 10Hz (versions 2.4.2 and 2.4.3), but when I try it on linux, I'm only able to get observations when I set the ublox navigation rate to 1Hz (max 2Hz).

I'm doing all the settings using the u-center on windows.

Does anyone experienced the same problem?

**Comment by aforster** [comment]
I think I had a similar problem. Try to increase the baudrate on the UART port. I added the following line to https://github.com/tomojitakasu/RTKLIB/blob/master/data/ubx_m8t_glo_raw_5hz.cmd

`!UBX CFG-PRT 1 0 0 2240 460800 7 3 0 0`

**Comment by m91moreira** [comment]
Thanks for your repply.

I was using the USB, so I think that it was not a communication speed problem.

But, since in the future I will need to use the serial port of the UBLOX I tryed to do what you told me, and use the UART1, but for some reason I don't get any observations. I configured the UBLOX to send the NAVSOL, NAVTIME, RXMRAWX and RXMSFRBX. I'm missing something?

**Comment by aforster** [comment]
I guess it was not the same problem then.

**Comment by tomojitakasu** [comment]
See also the u-blox support forum:

https://forum.u-blox.com/index.php?qa=2093&qa_1=5hz-rawx-messages-stop-after-around-1-second-lea-m8t

**Comment by m91moreira** [comment]
Hi,

The problem is solved. I started using the serial port at 921600 baud. Now I'm able to get data at 10Hz.

**Comment by weisongwen** [comment]
Hi, @m91moreira 

I also work on the ublox m8T, do you have finished the driver for collecting raw data from ublox m8t?

Thanks 
Welson
