### ISSUE TITLE
2.4.3 b8 ppp processing in rtknavi

### ISSUE THREAD

**Issue by coandrei** [tomojitakasu/RTKLIB#139]
PPP processing in RTKNAVI does not work but Single Mode solution is shown.
The same configuration works fine in 2.4.2_p11

**Comment by georgmichel** [comment]
...same for RTKPOST

**Comment by tomojitakasu** [comment]
Sorry, no support for beta. It's just a working and development branch.
For stable, use 2.4.2 p11.

**Comment by georgmichel** [comment]
OK, I understand. Thanks for replying.
