### ISSUE TITLE
Compilling error

### ISSUE THREAD

**Issue by m1mahesh** [tomojitakasu/RTKLIB#14]
Hello Sir,

i am trying to compile rtklib on ubuntu desktop as well as beagle bone black, when i run "makeall.sh" it completes with warning and after that i run "makefile" which is under rtkrcv \ gcc folder giving below errors i am getting same error on desktop as well as beaglebone black. i am very newbie into linux. any suggestion ?

mahesh@WZ7:~/rtklib/app/rtkrcv/gcc$ ls
?           ephemeris.c  javad.o    options.c  ppp.c      rcvraw.o  rtcm3e.o  rtkpos.c      rtkrcv.o      sbas.o      stec.o       ublox.o
binex.o     ephemeris.o  lambda.c   options.o  ppp.o      rinex.c   rtcm3.o   rtkpos_gsi.c  rtkrcv.trace  skytraq.o   stream.c
convkml.c   geoid.c      lambda.o   pntpos.c   preceph.c  rinex.o   rtcm.c    rtkpos_gsi.o  rtkshut.sh    solution.c  stream.o
convrnx.c   geoid.o      makefile   pntpos.o   preceph.o  rtcm2.c   rtcm.o    rtkpos.o      rtkstart.sh   solution.o  streamsvr.c
crescent.o  gw10.o       makefile~  postpos.c  qzslex.c   rtcm2.o   rtkcmn.c  rtkrcv        rtksvr.c      src         temp
datum.c     ionex.c      novatel.o  ppp_ar.c   rcv        rtcm3.c   rtkcmn.o  rtkrcv.conf   rtksvr.o      ss2.o       tle.c
download.c  ionex.o      nvs.o      ppp_ar.o   rcvraw.c   rtcm3e.c  rtklib.h  rtkrcv.nav    sbas.c        stec.c      todo
mahesh@WZ7:~/rtklib/app/rtkrcv/gcc$ bash makefil
bash: makefil: No such file or directory
mahesh@WZ7:~/rtklib/app/rtkrcv/gcc$ bash makefile
makefile: line 2: $'\r': command not found
makefile: line 3: BINDIR: command not found
makefile: line 4: SRC: command not found
makefile: line 5: $'\r': command not found
makefile: line 8: -DENAGLO: command not found
makefile: line 9: $'\r': command not found
makefile: line 10: SRC: command not found
makefile: line 10: CTARGET: command not found
makefile: line 10: CFLAGS: command not found
makefile: line 11: LDLIBS: command not found
makefile: line 12: $'\r': command not found
makefile: line 13: all: command not found
makefile: line 14: rtkrcv: command not found
makefile: line 15: rtkrcv: command not found
makefile: line 16: rtkrcv: command not found
makefile: line 17: rtkrcv: command not found
makefile: line 18: $'\r': command not found
makefile: line 19: rtkrcv.o: command not found
makefile: line 20: CC: command not found
makefile: line 20: CFLAGS: command not found
makefile: line 20: -c: command not found
makefile: line 21: SRC: command not found
makefile: line 21: rtkcmn.o: command not found
makefile: line 22: CC: command not found
makefile: line 22: CFLAGS: command not found
makefile: line 22: SRC: command not found
makefile: line 22: -c: command not found
makefile: line 23: SRC: command not found
makefile: line 23: rtksvr.o: command not found
makefile: line 24: CC: command not found
makefile: line 24: CFLAGS: command not found
makefile: line 24: SRC: command not found
makefile: line 24: -c: command not found
makefile: line 25: SRC: command not found
makefile: line 25: rtkpos.o: command not found
makefile: line 26: CC: command not found
makefile: line 26: CFLAGS: command not found
makefile: line 26: SRC: command not found
makefile: line 26: -c: command not found
makefile: line 27: SRC: command not found
makefile: line 27: geoid.o: command not found
makefile: line 28: CC: command not found
makefile: line 28: CFLAGS: command not found
makefile: line 28: SRC: command not found
makefile: line 28: -c: command not found
makefile: line 29: SRC: command not found
makefile: line 29: solution.o: command not found
makefile: line 30: CC: command not found
makefile: line 30: CFLAGS: command not found
makefile: line 30: SRC: command not found
makefile: line 30: -c: command not found
makefile: line 31: SRC: command not found
makefile: line 31: lambda.o: command not found
makefile: line 32: CC: command not found
makefile: line 32: CFLAGS: command not found
makefile: line 32: SRC: command not found
makefile: line 32: -c: command not found
makefile: line 33: SRC: command not found
makefile: line 33: sbas.o: command not found
makefile: line 34: CC: command not found
makefile: line 34: CFLAGS: command not found
makefile: line 34: SRC: command not found
makefile: line 34: -c: command not found
makefile: line 35: SRC: command not found
makefile: line 35: stream.o: command not found
makefile: line 36: CC: command not found
makefile: line 36: CFLAGS: command not found
makefile: line 36: SRC: command not found
makefile: line 36: -c: command not found
makefile: line 37: SRC: command not found
makefile: line 37: rcvraw.o: command not found
makefile: line 38: CC: command not found
makefile: line 38: CFLAGS: command not found
makefile: line 38: SRC: command not found
makefile: line 38: -c: command not found
makefile: line 39: SRC: command not found
makefile: line 39: rtcm.o: command not found
makefile: line 40: CC: command not found
makefile: line 40: CFLAGS: command not found
makefile: line 40: SRC: command not found
makefile: line 40: -c: command not found
makefile: line 41: SRC: command not found
makefile: line 41: rtcm2.o: command not found
makefile: line 42: CC: command not found
makefile: line 42: CFLAGS: command not found
makefile: line 42: SRC: command not found
makefile: line 42: -c: command not found
makefile: line 43: SRC: command not found
makefile: line 43: rtcm3.o: command not found
makefile: line 44: CC: command not found
makefile: line 44: CFLAGS: command not found
makefile: line 44: SRC: command not found
makefile: line 44: -c: command not found
makefile: line 45: SRC: command not found
makefile: line 45: rtcm3e.o: command not found
makefile: line 46: CC: command not found
makefile: line 46: CFLAGS: command not found
makefile: line 46: SRC: command not found
makefile: line 46: -c: command not found
makefile: line 47: SRC: command not found
makefile: line 47: preceph.o: command not found
makefile: line 48: CC: command not found
makefile: line 48: CFLAGS: command not found
makefile: line 48: SRC: command not found
makefile: line 48: -c: command not found
makefile: line 49: SRC: command not found
makefile: line 49: options.o: command not found
makefile: line 50: CC: command not found
makefile: line 50: CFLAGS: command not found
makefile: line 50: SRC: command not found
makefile: line 50: -c: command not found
makefile: line 51: SRC: command not found
makefile: line 51: pntpos.o: command not found
makefile: line 52: CC: command not found
makefile: line 52: CFLAGS: command not found
makefile: line 52: SRC: command not found
makefile: line 52: -c: command not found
makefile: line 53: SRC: command not found
makefile: line 53: ppp.o: command not found
makefile: line 54: CC: command not found
makefile: line 54: CFLAGS: command not found
makefile: line 54: SRC: command not found
makefile: line 54: -c: command not found
makefile: line 55: SRC: command not found
makefile: line 55: ppp_ar.o: command not found
makefile: line 56: CC: command not found
makefile: line 56: CFLAGS: command not found
makefile: line 56: SRC: command not found
makefile: line 56: -c: command not found
makefile: line 57: SRC: command not found
makefile: line 57: novatel.o: command not found
makefile: line 58: CC: command not found
makefile: line 58: CFLAGS: command not found
makefile: line 58: SRC: command not found
makefile: line 58: -c: command not found
makefile: line 59: SRC: command not found
makefile: line 59: ublox.o: command not found
makefile: line 60: CC: command not found
makefile: line 60: CFLAGS: command not found
makefile: line 60: SRC: command not found
makefile: line 60: -c: command not found
makefile: line 61: SRC: command not found
makefile: line 61: ss2.o: command not found
makefile: line 62: CC: command not found
makefile: line 62: CFLAGS: command not found
makefile: line 62: SRC: command not found
makefile: line 62: -c: command not found
makefile: line 63: SRC: command not found
makefile: line 63: crescent.o: command not found
makefile: line 64: CC: command not found
makefile: line 64: CFLAGS: command not found
makefile: line 64: SRC: command not found
makefile: line 64: -c: command not found
makefile: line 65: SRC: command not found
makefile: line 65: skytraq.o: command not found
makefile: line 66: CC: command not found
makefile: line 66: CFLAGS: command not found
makefile: line 66: SRC: command not found
makefile: line 66: -c: command not found
makefile: line 67: SRC: command not found
makefile: line 67: gw10.o: command not found
makefile: line 68: CC: command not found
makefile: line 68: CFLAGS: command not found
makefile: line 68: SRC: command not found
makefile: line 68: -c: command not found
makefile: line 69: SRC: command not found
makefile: line 69: javad.o: command not found
makefile: line 70: CC: command not found
makefile: line 70: CFLAGS: command not found
makefile: line 70: SRC: command not found
makefile: line 70: -c: command not found
makefile: line 71: SRC: command not found
makefile: line 71: nvs.o: command not found
makefile: line 72: CC: command not found
makefile: line 72: CFLAGS: command not found
makefile: line 72: SRC: command not found
makefile: line 72: -c: command not found
makefile: line 73: SRC: command not found
makefile: line 73: binex.o: command not found
makefile: line 74: CC: command not found
makefile: line 74: CFLAGS: command not found
makefile: line 74: SRC: command not found
makefile: line 74: -c: command not found
makefile: line 75: SRC: command not found
makefile: line 75: ephemeris.o:: command not found
makefile: line 76: CC: command not found
makefile: line 76: CFLAGS: command not found
makefile: line 76: SRC: command not found
makefile: line 76: -c: command not found
makefile: line 77: SRC: command not found
makefile: line 77: rinex.o: command not found
makefile: line 78: CC: command not found
makefile: line 78: CFLAGS: command not found
makefile: line 78: SRC: command not found
makefile: line 78: -c: command not found
makefile: line 79: SRC: command not found
makefile: line 79: ionex.o: command not found
makefile: line 80: CC: command not found
makefile: line 80: CFLAGS: command not found
makefile: line 80: SRC: command not found
makefile: line 80: -c: command not found
makefile: line 81: SRC: command not found
makefile: line 81: stec.o: command not found
makefile: line 82: CC: command not found
makefile: line 82: CFLAGS: command not found
makefile: line 82: SRC: command not found
makefile: line 82: -c: command not found
makefile: line 83: SRC: command not found
makefile: line 83: rtkpos_gsi.o:: command not found
makefile: line 84: CC: command not found
makefile: line 84: CFLAGS: command not found
makefile: line 84: SRC: command not found
makefile: line 84: -c: command not found
makefile: line 85: $'\r': command not found
makefile: line 86: SRC: command not found
makefile: line 86: rtkrcv.o: command not found
makefile: line 87: SRC: command not found
makefile: line 87: rtkcmn.o: command not found
makefile: line 88: SRC: command not found
makefile: line 88: rtksvr.o: command not found
makefile: line 89: SRC: command not found
makefile: line 89: rtkpos.o: command not found
makefile: line 90: SRC: command not found
makefile: line 90: geoid.o: command not found
makefile: line 91: SRC: command not found
makefile: line 91: solution.o: command not found
makefile: line 92: SRC: command not found
makefile: line 92: lambda.o: command not found
makefile: line 93: SRC: command not found
makefile: line 93: sbas.o: command not found
makefile: line 94: SRC: command not found
makefile: line 94: rcvraw.o: command not found
makefile: line 95: SRC: command not found
makefile: line 95: rtcm.o: command not found
makefile: line 96: SRC: command not found
makefile: line 96: rtcm2.o: command not found
makefile: line 97: SRC: command not found
makefile: line 97: rtcm3.o: command not found
makefile: line 98: SRC: command not found
makefile: line 98: rtcm3e.o: command not found
makefile: line 99: SRC: command not found
makefile: line 99: preceph.o: command not found
makefile: line 100: SRC: command not found
makefile: line 100: options.o: command not found
makefile: line 101: SRC: command not found
makefile: line 101: pntpos.o: command not found
makefile: line 102: SRC: command not found
makefile: line 102: ppp.o: command not found
makefile: line 103: SRC: command not found
makefile: line 103: novatel.o: command not found
makefile: line 104: SRC: command not found
makefile: line 104: ublox.o: command not found
makefile: line 105: SRC: command not found
makefile: line 105: ss2.o: command not found
makefile: line 106: SRC: command not found
makefile: line 106: crescent.o: command not found
makefile: line 107: SRC: command not found
makefile: line 107: skytraq.o: command not found
makefile: line 108: SRC: command not found
makefile: line 108: gw10.o: command not found
makefile: line 109: SRC: command not found
makefile: line 109: javad.o: command not found
makefile: line 110: SRC: command not found
makefile: line 110: nvs.o: command not found
makefile: line 111: SRC: command not found
makefile: line 111: binex.o: command not found
makefile: line 112: SRC: command not found
makefile: line 112: ephemeris.o:: command not found
makefile: line 113: SRC: command not found
makefile: line 113: rinex.o: command not found
makefile: line 114: SRC: command not found
makefile: line 114: ionex.o: command not found
makefile: line 115: SRC: command not found
makefile: line 115: stec.o: command not found
makefile: line 116: SRC: command not found
makefile: line 116: rtkpos_gsi.o:: command not found
makefile: line 117: $'\r': command not found
makefile: line 118: $'install:\r': command not found
makefile: line 119: BINDIR: command not found
makefile: line 120: $'\r': command not found
makefile: line 121: $'test1:\r': command not found
invalid option value pos1-snrmask (./rtkrcv.conf:46)
*\* rtkrcv ver.2.4.2 b11 console (h:help) **
rtkrcv>

**Comment by dusabecasta** [comment]
I want to compile rtkrcv on my pixhawk , in gcc compiler by run command make  i face with this error make: *** [makefile:22: rtkcmn.o] Error 1
$ make
cc -c -Wall -O3 -ansi -pedantic -I../../../src -DTRACE -DENAGLO -DENAGAL -DENAQZS -DNFREQ=3 ../rtkrcv.c
../rtkrcv.c: In function ‘prstatus’:
../rtkrcv.c:934:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     thread=(int)svr.thread;
            ^
../rtkrcv.c:1035:9: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
         for (i=0;i<3;i++) rr[i]=rtk.x[i]-rtk.rb[i]; bl1=norm(rr,3);
         ^~~
../rtkrcv.c:1035:53: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
         for (i=0;i<3;i++) rr[i]=rtk.x[i]-rtk.rb[i]; bl1=norm(rr,3);
                                                     ^~~
../rtkrcv.c:1038:9: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
         for (i=0;i<3;i++) rr[i]=rtk.xa[i]-rtk.rb[i]; bl2=norm(rr,3);
         ^~~
../rtkrcv.c:1038:54: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
         for (i=0;i<3;i++) rr[i]=rtk.xa[i]-rtk.rb[i]; bl2=norm(rr,3);
                                                      ^~~
../rtkrcv.c: In function ‘cmdshell’:
../rtkrcv.c:1533:18: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
     int i,j,narg,ret;
                  ^~~
At top level:
../rtkrcv.c:45:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
 static const char rcsid[]="$Id:$";
                   ^~~~~
cc -c -Wall -O3 -ansi -pedantic -I../../../src -DTRACE -DENAGLO -DENAGAL -DENAQZS -DNFREQ=3 ../../../src/rtkcmn.c
../../../src/rtkcmn.c: In function ‘matinv’:
../../../src/rtkcmn.c:966:9: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
         for (i=0;i<n;i++) A[i+j*n]=0.0; A[j+j*n]=1.0;
         ^~~
../../../src/rtkcmn.c:966:41: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
         for (i=0;i<n;i++) A[i+j*n]=0.0; A[j+j*n]=1.0;
                                         ^
../../../src/rtkcmn.c: In function ‘str2num’:
../../../src/rtkcmn.c:1139:5: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
     for (s+=i;*s&&--n>=0;s++) *p++=*s=='d'||*s=='D'?'E':*s; *p='\0';
     ^~~
../../../src/rtkcmn.c:1139:61: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
     for (s+=i;*s&&--n>=0;s++) *p++=*s=='d'||*s=='D'?'E':*s; *p='\0';
                                                             ^
../../../src/rtkcmn.c: In function ‘str2time’:
../../../src/rtkcmn.c:1155:5: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
     for (s+=i;*s&&--n>=0;) *p++=*s++; *p='\0';
     ^~~
../../../src/rtkcmn.c:1155:39: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
     for (s+=i;*s&&--n>=0;) *p++=*s++; *p='\0';
                                       ^
../../../src/rtkcmn.c: In function ‘tickget’:
../../../src/rtkcmn.c:1512:24: error: ‘CLOCK_MONOTONIC_RAW’ undeclared (first use in this function)
     if (!clock_gettime(CLOCK_MONOTONIC_RAW,&tp)) {
                        ^~~~~~~~~~~~~~~~~~~
../../../src/rtkcmn.c:1512:24: note: each undeclared identifier is reported only once for each function it appears in
../../../src/rtkcmn.c:1520:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
At top level:
../../../src/rtkcmn.c:105:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
 static const char rcsid[]="$Id: rtkcmn.c,v 1.1 2008/07/17 21:48:06 ttaka Exp ttaka $";
                   ^~~~~
make: *** [makefile:22: rtkcmn.o] Error 1
anyone could help me to solve it
