### ISSUE TITLE
How to compile rtknavi under Debian GNU/Linux

### ISSUE THREAD

**Issue by kellogs** [tomojitakasu/RTKLIB#140]
```
Hello,

Under GNU/Linux, I could compile librtk under Debian GNU/Linux:
```
sudo sh makeall.sh install

% pos2kml/gcc
cp pos2kml /usr/local/bin

% str2str/gcc
cp str2str /usr/local/bin

% rnx2rtkp/gcc
cp rnx2rtkp /usr/local/bin

% convbin/gcc
cp convbin /usr/local/bin

% rtkrcv/gcc
cp rtkrcv /usr/local/bin
```
Unfortunately, I could not find a way to compile rtklib graphical environment under Debian GNU/Linux. For example rtknavi.

How to compile?

**Comment by tomojitakasu** [comment]
Read the manual 2.1 and 4.

**Comment by alexmyczko** [comment]
Meanwhile you can `apt-get install rtklib rtklib-qt rtklib-doc`
