### ISSUE TITLE
GPS + GLONASS with M8T in 2.4.2 and 2.4.3 on Windows 7

### ISSUE THREAD

**Issue by georgmichel** [tomojitakasu/RTKLIB#143]
I made the observation that the GPS+GLONASS solution for singe as well as RTK kinematic is regularly worse than GPS only. No SBAS or other correction is used. 

I don't know whether this is a M8T or RTKLIB issue or maybe my own fault.

**Comment by georgmichel** [comment]
Maybe this information is useful: I recorded about 1h worth of data with M8T for two points under completely open sky. When using static PPP, combined, no corrections, the GLONASS only solution was in both cases 6.45m West from the GPS only solution.

**Comment by georgmichel** [comment]
Some more news: Today I made another experiment under perfect conditions (clear sky view, "near survey grade" antenna, 1h). I made the observation that I obtain only PPP fixes (100%) when the uBlox M8T issues only NAV-TIMEUTC messages. When it issues only NAV-TIMEGPS + NAV-TIMEGLO instead, then I obtain 1% single/SBAS fixes for both GPS and GLONASS, which is more realistic. However, in the uBlox documentation the use of NAV-TIMEUTC is encouraged for multi-GNSS. 

There are still 4m offset between GPS and GLONASS for the uncorrected calculation. I will check this in two weeks when precise GLONASS ephemerides are available. 

For another finding I open a new issue because I think it has nothing to do with M8T.

**Comment by tomojitakasu** [comment]
I don't recommend to use the single-freq PPP mode.
It' hard to obtain good results because of large iono and DCB errors.

**Comment by FaaizJeelani** [comment]
Hello..

I am using RTKlib 2.4.3 and Ublox M8P for post processing.

After generating RINEX through Emlid Studio, i can see 8-10 GPS & 8-10 GLONASS and 2-3 QZSS Satellites , however when i select Static or DGNSS/DGPS positioning mode and enter the base coordinates (base is also set using M8P), the results shown are exactly same when i enable GPS + GLONASS + QZSS or GPS only. Therefore, no change in the results with or without GLONASS & QZSS.

If i run GLONASS + QZSS only without GPS satellites, there is no result Q=0

I understand the receiver is not enabled for BeiDou and SBAS so none of these satellites are visible during data logging or in RINEX

Any suggestions would be highly appreciated please.
