### ISSUE TITLE
the comment for ambiguity fix flag in data struct ssat_t is not correct

### ISSUE THREAD

**Issue by Marszsu** [tomojitakasu/RTKLIB#147]
If my understanding is correct, the comment for ambiguity fix flag in data struct ssat_t is not correct. 
In rtklib.h, data struct ssat_t
unsigned char fix [NFREQ]; /* ambiguity fix flag (1:fix,2:float,3:hold) */
shall be changed to
unsigned char fix [NFREQ]; /* ambiguity fix flag (0:initial,1-float,2-fix,3-hold) */

Is it a "slip of keyboard" or my understanding is wrong?

**Comment by tomojitakasu** [comment]
It's just a mistake.
See also the header comment of rtkpos() in rtkpos.c.

**Comment by Marszsu** [comment]
Thanks for the fast reply.
