### ISSUE TITLE
Useless/incorrect signal definitions

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [tomojitakasu/RTKLIB#148]
There are some signal code definitions which are incorrect or useless.
* `CODE_L1E` is declared for L1-SAIF (QZS) but it's not used in sources and correct code for this signal is 1Z (RINEX 3.03 specs)
* `CODE_L1I` is declared for B1I (BDS) and `CODE_L1Q` is for B1Q while they should be `CODE_L2I` and `CODE_L2Q`. These incorrect values are used widely in the source while correct ones have no appearances.

**Comment by tomojitakasu** [comment]
In RINEX 3.02, 1I and 1Q is defined as BDS B1I and B1Q. (In 3.03 or 3.02 draft, 2I and 2Q are used as BDS B1I and B1Q). RTKLIB accepts both of 1I/1Q and 2I/2Q as BDS B1I and B1Q.
1E is not used in the recent codes. It's defined just for old-code compatibility.

**Comment by Fr0sT-Brutal** [comment]
Well, wouldn't it be more logical to move this legacy from the main header to those places where they're used? I suppose CODE_L1I/Q are only used when you deal with Rinex 3.01-2 and it's just a matter of mapping and conversion. Anyway it's up to you of course but maybe you could at least mention the sense of these signals in comments for clarity?

**Comment by tomojitakasu** [comment]
It is fixed in 2.4.3 b11.
