### ISSUE TITLE
Dropping L2 signals in RINEX files with RTKCONV tool

### ISSUE THREAD

**Issue by DavidKelleySCSC** [tomojitakasu/RTKLIB#15]
We are using the RTKlib 2.4.2 source code in a project and having problems converting what appears to me me to be valid RTCM 1004 message content into a RINEX file. The call to convrnx() has worked well overall but we seem to be having problems with any C2/P2 content being dropped out and not in the final file.  [And an aside, the RTCM binary content has been checked using the commercial Alberding InspectRTCM tool and which confirms it is well formed and decodes]

As is my habit with this wonderful tool, I then used RTKCONV directly to try and convert one RINEX file to another in order to understand some of the control flags. 

I am having two problems that seem to be part of the tool itself.  First the "Scan Obs Types" seem to damage the output and remove any L2 signal content which is present in any SV which does not also have P2/C2 content.  Otherwise it seems to correctly detect there is not any Doppler and remove that signal entry.  This may be related to the below.

Second, the RTKCONV tool, when scan obs types is disabled (checked off) and all signal types are enabled (C, L, D, S and L1, L2 are all checked on) also removes any L2 signal content which is present in any SV which does not also have P2/C2 content. 

In fact I am not seeing any way to pass the L2 content for those SV that do not have a P2 signal.  Very Strange.

[And When we use the same core routines in our own code, we DO get the desired L2 content in the RINEX Obs file output at all times, however we seem unable to get any P2 values - which is what first led to this posting]

Here is a the 1st epoch of a RINEX file that illustrates this problem
Original file is:
>      2.10           OBSERVATION DATA    M (MIXED)           RINEX VERSION / TYPE
> DCTOOLS             DCTOOLS             20130808 000310 UTC PGM / RUN BY / DATE
>                                                             COMMENT             
>  station ID: GISA                                           COMMENT             
>                                                             COMMENT                       
> gisar30                                                     MARKER NAME
>                                                             MARKER NUMBER       
>                                                             OBSERVER / AGENCY   
>                     TRIMBLE NETR9                           REC # / TYPE / VERS
> 30137282            TRM55971.00     NONE                    ANT # / TYPE        
>  -2419200.2475 -4703567.0730  3553009.4654                  APPROX POSITION XYZ
>         0.0000        0.0000        0.0000                  ANTENNA: DELTA H/E/N
>      1     1                                                WAVELENGTH FACT L1/2
>     10    C1    L1    D1    S1    P1    P2    L2    D2    S2# / TYPES OF OBSERV
>           C2                                                # / TYPES OF OBSERV
>   2013     8     7    23    58   17.0000000     GPS         TIME OF FIRST OBS   
>   2013     8     8     0     3   26.0000000     GPS         TIME OF LAST OBS    
>                                                             END OF HEADER       
>  13  8  7 23 58 17.0000000  0  9G 2G12G10G29G31G 4G25G24G 5
>   21185515.060   111330764.192                          50.500                  
>   21185518.040    86751290.425                          39.500                  
>   20328459.626   106826846.532                          49.750                  
>                   83241721.081                          49.750                  
>   22365271.972   117530411.680                          47.750                  
>   22365278.772    91582172.665                          31.250                  
>   22755330.950   119580161.255                          45.250                  
>                   93179371.102                          42.500                  
>   25188280.032   132365310.315                          40.250                  
>                  103141802.997                          34.000                  
>   23676469.084   124420786.001                          41.500                  
>   23676474.664    96951288.234                          18.250                  
>   21069863.760   110722943.173                          47.500                  
>                   86277629.738                          48.250                  
>   24339685.798   127905879.334                          38.250                  
>                   99666909.523                          39.250                  
>   21556860.958   113282235.481                          45.750                  
>                   88271914.310                          45.500                  
>  13  8  7 23 58 18.0000000  0  9G 2G12G10G29G31G 4G25G24G 5
> - cut ---
Note that there is an L2 entry for every SV.
The returned file from RTKCONV is:

>      2.11           OBSERVATION DATA    G (GPS)             RINEX VERSION / TYPE
> RTKCONV 2.4.2                           20131204 181548 UTC PGM / RUN BY / DATE
> log: C:\Users\dck\Desktop\DCToos-625\trunk\QT-Compress\Tes  COMMENT             
> format: RINEX                                               COMMENT             
> gisar30                                                     MARKER NAME         
>                                                             MARKER NUMBER       
>                                                             OBSERVER / AGENCY   
>                     TRIMBLE NETR9                           REC # / TYPE / VERS
> 30137282            TRM55971.00     NONE                    ANT # / TYPE        
>  -2419200.2475 -4703567.0730  3553009.4654                  APPROX POSITION XYZ
>         0.0000        0.0000        0.0000                  ANTENNA: DELTA H/E/N
>      1     1                                                WAVELENGTH FACT L1/2
>     10    C1    L1    D1    S1    P1    C2    L2    D2    S2# / TYPES OF OBSERV
>           P2                                                # / TYPES OF OBSERV
>   2013     8     7    23    58   17.0000000     GPS         TIME OF FIRST OBS   
>   2013     8     8     0     3   26.0000000     GPS         TIME OF LAST OBS    
>                                                             END OF HEADER       
>  13  8  7 23 58 17.0000000  0  9G 2G12G10G29G31G 4G25G24G 5
>   21185515.060   111330764.192                          50.500                  
>                   86751290.425                          39.500    21185518.040  
>   20328459.626   106826846.532                          49.750                  
>                                                                                 
>   22365271.972   117530411.680                          47.750                  
>                   91582172.665                          31.250    22365278.772  
>   22755330.950   119580161.255                          45.250                  
>                                                                                 
>   25188280.032   132365310.315                          40.250                  
>                                                                                 
>   23676469.084   124420786.001                          41.500                  
>                   96951288.234                          18.250    23676474.664  
>   21069863.760   110722943.173                          47.500                  
>                                                                                 
>   24339685.798   127905879.334                          38.250                  
>                                                                                 
>   21556860.958   113282235.481                          45.750                  
>                                                                                 
>  13  8  7 23 58 18.0000000  0  9G 2G12G10G29G31G 4G25G24G 5

Note that that the L2 signal is now only present when there is a P2 signal and for all other SVs have been dropped.
Your assistance with this is sought.

**Comment by tomojitakasu** [comment]
See No.131 of the support information.

http://www.rtklib.com/rtklib_support.htm

Tomoji Takasu
