### ISSUE TITLE
Minimum lock count for ambiguity resolution (arlockcnt) does not work

### ISSUE THREAD

**Issue by rtklibexplorer** [tomojitakasu/RTKLIB#151]
"pos2-Arlockcnt" (the input parameter to specify how many epochs a satellite must be locked for before being used for ambiguity resolution) has no effect because of an incorrect variable type.

In this line of code from rtkpos.c, lock[f] is compared to zero:

if (rtk->ssat[i-k].lock[f]>0&&!(rtk->ssat[i-k].slip[f]&2)&&
     rtk->ssat[i-k].azel[1]>=rtk->opt.elmaskar) {
     rtk->ssat[i-k].fix[f]=2; /* fix */

but lock[f] is defined as an unsigned int, so this check will never fail.  Changing the definition of lock from "unsigned int" to "int" resolves the problem.

This bug causes satellites to be used for ambiguity resolution regardless of the lock count.  This can cause ambiguity resolution to fail because satellites are being used before they have time to converge.

I have included more detail and a demonstration of the problem and fix at:

 https://rtklibexplorer.wordpress.com/2016/02/26/improving-rtklib-solution-ar-lock-count-and-elevation-mask/

**Comment by Marszsu** [comment]
It's a good point. I actually have the same finds recently. 
PS: nice rtklib know-how blog!

**Comment by tomojitakasu** [comment]
Thanks. It is fixed in 2.4.3 b11.
