### ISSUE TITLE
rtcm->sta.hgt doesn't make it into output file header as antenna height above arp

### ISSUE THREAD

**Issue by astrodanco** [tomojitakasu/RTKLIB#154]
rtcm->sta.hgt doesn't make it into the output file header as the antenna height above the arp because the code is zeroing it right after setting it.

The following lines in file src/convrnx.c function rtcm2opt() need to be changed

From:

    else {
        opt->antdel[0]=rtcm->sta.hgt;
        opt->antdel[0]=0.0;
        opt->antdel[0]=0.0;
    }

To:

    else {
        opt->antdel[0]=rtcm->sta.hgt;
        opt->antdel[1]=0.0;
        opt->antdel[2]=0.0;
    }

Please make this change.

Thank you.

**Comment by tomojitakasu** [comment]
Thanks. It is fixed in 2.4.3 b10.
