### ISSUE TITLE
RTKplot export

### ISSUE THREAD

**Issue by Willardcz** [tomojitakasu/RTKLIB#156]
Hi, 

I have a question about RTKPlot. Is there some way to export position data from RTKPlot? For example I have a trajectory on the map and I want to export these position data (lat lon), is this
possible somehow? All I found were only exports for graphs etc.
Thank you!

**Comment by astrodanco** [comment]
> I want to export these position data

 

Those are located in the solution file being plotted, are they not?

**Comment by Willardcz** [comment]
I am streaming data to RTKPlot via TCP, so it doesn't use any solution file. I just wanted to know, if I could export these data straight from RTKPlot, or if I will have to manually write them to a file while streaming to RTKPlot.

**Comment by Willardcz** [comment]
Ah, already found it, it's in the View->Input montor.

**Comment by mbavaro** [comment]
Could you therefore close the issue you opened?
