### ISSUE TITLE
Min satellite PRN number of SBAS in rtkcmn.c

### ISSUE THREAD

**Issue by AlexeyBulatov** [tomojitakasu/RTKLIB#159]
Why constant 100 is used instead of MINPRNSBS here https://github.com/tomojitakasu/RTKLIB/blob/master/src/rtkcmn.c#L437?

**Comment by tomojitakasu** [comment]
In RINEX convention, "S12" means SBAS PRN 112. See 3.5 of RINEX 3.02.

ftp://igs.org/pub/data/format/rinex302.pdf
