### ISSUE TITLE
Not able to see SNR for UBLOX6M receiver

### ISSUE THREAD

**Issue by bipin9766** [tomojitakasu/RTKLIB#162]
Hello Team,

This is my first project with rtklib and GPS. I am using two Ublox modules- 7P and 6M... The idea is to use 6M as base station and 7P as rover or otherwise. But when I use these steps (https://docs.emlid.com/navio/RTKLIB/rtklib-rover-setup/)  to setup in RTKNAVI I am not getting the SNR for 6M module. The same module is working correctly with U-center. Is there anything i need to know or check to get this working. Please help.

**Comment by mbavaro** [comment]
As mentioned already, 6M does not officially support RAW data. Therefore, please close this issue as it is NOT related to RTKLIB. Having lots of issues like this pending on the repository prevents the maintainers from focussing on the real ones.

**Comment by bipin9766** [comment]
Thanks for the help. I googled the 6M commands and found the solution on https://gist.github.com/fenrir-naru/918b2fbe427903401e9c .... its working now
