### ISSUE TITLE
Problem sending RTCM3 over radiolink

### ISSUE THREAD

**Issue by PellePettersson** [tomojitakasu/RTKLIB#163]
I can send RTCM3 data over TCP-server/client, but not if i use radio-link over serial.
How to solve this?

**Comment by DavidKelleySCSC** [comment]
Why not?  As long as you do not drop bits/bytes you can view this pipe 
as just just another stream.  See also #152 for a few related details. 
RTCM3 has a reasonably good check sum which can be used to detect the 
event of message loss or corruption.  Many receiver and consumption 
device will do this for you, RTKLIB included.  When you have a low rate 
of message loss (or BER if you prefer) you will likely have no issues, 
then when BER grows, total failure. Have you tested the link itself with 
some sort of terminal device?
Regards, DCKelley

**Comment by PellePettersson** [comment]
OK!
Then i can start to trouboleshoot my radilink. (APC220)
Thanks a lot David!
