### ISSUE TITLE
encode_msm1() function can't work

### ISSUE THREAD

**Issue by linkaiqin** [tomojitakasu/RTKLIB#165]
encode_msm1() calling encode_msm_head(info) and the set the argument info to NULL.
encode_msm_head(info)                                 rtcm3e.c:2180
    gen_msm_sat(info)                                      rtcm3e.c:1931
    info[k]=sys!=SYS_GLO?0:(fcn<0?15:fcn)    rtcm3e.c:1809

The pointer info is NULL, it will cause system down.

**Comment by tomojitakasu** [comment]
It will be fixed in the next release. Until that, please modify codes as follows and rebuild APs.

src/rtcm3e.c >1596(2.4.2 p11), L1809(2.4.3 b10)

info[k]=sys!=SYS_GLO?0:(fcn<0?15:fcn);
->
if (info) info[k]=sys!=SYS_GLO?0:(fcn<0?15:fcn);

**Comment by tomojitakasu** [comment]
It is fixed in 2.4.3 b11.
