### ISSUE TITLE
rtkrcv hangs forever after adding the debug option -t 4 in 2.4.3

### ISSUE THREAD

**Issue by linkaiqin** [tomojitakasu/RTKLIB#170]
initlock(f)->pthread_mutex_init(f,NUL) doesn't set the mutex recursive attribute. If thread locks the mutex more than once,  the thread will block forever.

After gdb debugging, I find the calling procedure below will casue the issue.

    trace()
      traceswap()               rtkcmn.c:2823
        lock(&lock_trace)       rtkcmn.c:2772  first lock
        reppath()               rtkcmn.c:2781
           trace()              rtkcmn.c:3144
              traceswap()       rtkcmn.c:2823
              lock(&lock_trace) rtkcmn.c:2772  second lock and thread blocks forever

**Comment by tomojitakasu** [comment]
Thanks. It is fixed in 2.4.3 b11.
