### ISSUE TITLE
loss of fix when a new sat is added

### ISSUE THREAD

**Issue by divid54** [tomojitakasu/RTKLIB#174]
when a new sat is involved in RTK solution, fix will be lost instantly, and recovered in a few seconds. It seems like there is something wrong in the covariance matrix

**Comment by tomojitakasu** [comment]
It's normal behavior.
To improve the situation, increase "Min Lock to fix Amb" of the options, which is to keep the ambiguity float for newly added satellites.

**Comment by divid54** [comment]
when I set "Min Lock to fix Amb" to value 15, it turns out that only the 15th point after the new sat added is fixed, and the ratio is almost the same as before( before new sat added), while the status of the first 14 points after the new sat added are not fixed.

**Comment by divid54** [comment]
we use 'rtk->ssat[sat[i]-1].lock[f]=-rtk->opt.minlock;' in Rtkpos.c to set the opt value but the variable 'lock' in struct 'ssat_t' is defined as 'unsigned int lock [NFREQ]; /* lock counter of phase */'
it should be 'int' instead.

**Comment by tomojitakasu** [comment]
Yes. It's just a bug and fixed in 2.4.3 b11.
The 2.4.2 p11 still has the problem.
