### ISSUE TITLE
ionospheric and tropospheric corrections using EMS files

### ISSUE THREAD

**Issue by mohamedamjad** [tomojitakasu/RTKLIB#175]
I used RTKPOST in static mode (see screenshot attached for the options chosen). As input files I set a rinex obervation file for the rover and he base, a navigation file (broadcasted ephemeris) and EMS files for satellites PRN120 and 136. I choose SBAS corrections for both ionosphere and troposphere. I noticed that the results are EXACTLY the same than when I didn't apply SBAS correction and let the defaults options: Saastomoinen model for troposphere and broadcasted for ionosphere.
Is ionospheric and tropospheric corrections work in RTKLIB with EMS files?

Thank you in advance
![capture d ecran - 26062016 - 23 16 54](https://cloud.githubusercontent.com/assets/6891161/16364989/80f32300-3bf4-11e6-9400-2a6744ecaace.png)
![capture d ecran - 26062016 - 23 17 28](https://cloud.githubusercontent.com/assets/6891161/16364988/80f0c4de-3bf4-11e6-885b-93cc3fe72562.png)

**Comment by tomojitakasu** [comment]
Yes.
The options should be: Satellite Ephemeris/Clock: Broadcast+SBAS
However, The SBAS ionosphere correction is not applied to baseline processing. The SBAS tropos-model and ephemeris correction may very slightly affect to the baseline solutions. Usually you can get no improvement with under 100 km baseline.
