### ISSUE TITLE
age of differential error

### ISSUE THREAD

**Issue by Kilik86** [tomojitakasu/RTKLIB#176]
Hi everybody
I am trying to implement the RTK technique with two NavSpark NS-RAW. I am using two Raspberry Pi and the LoRa protocol for the communication.
For my purpose I tunneled the serial data from the Base Station Receiver trough LoRa. I can correctly get the data from the Rover and give them in input to the RTKRCV but the communication is quite slow because of the used protocol.

I am getting the following error:

> 08:08:09.00: age of differential error (age=109.6)
> 08:08:10.00: age of differential error (age=110.6)
> 08:08:11.00: age of differential error (age=110.6)
> 08:08:12.00: age of differential error (age=111.6)
> 08:08:13.00: age of differential error (age=111.6)
> 08:08:14.00: age of differential error (age=112.6)
> 08:08:15.00: age of differential error (age=112.6)
> 08:08:16.00: age of differential error (age=113.6)
> 08:08:17.00: age of differential error (age=113.6)
> 08:08:18.00: age of differential error (age=114.6)

**What does it mean??**
**Is it correlated with the low bitrate of the communication?**

**Comment by tomojitakasu** [comment]
Age of differential is over the limit. The limit can be set as Options - Setting 2 - Max Age of Diff (s).

**Comment by Kilik86** [comment]
tanks
