### ISSUE TITLE
M8P and RTKCONV . no navigation datas?

### ISSUE THREAD

**Issue by sobido** [tomojitakasu/RTKLIB#177]
Hi 
I tried to explore M8P Raw datas ( via C94-M8P ) in RTKconv 2.4.3. b8. I can't achieved to obtain any .nav file even if the raw file seems to be there. it worls fine with M8N .
The RTKnavi seems to work well however.
It is normal ?
No way to make post treatment from M8P with RTKLIB ?

I can't upgrade RTKLIB. If I  find the 2.4.3 b12 version ,  the <bin> directory has been moved to "RTKLIB_bin" that I don't find. 

thanks by advance

**Comment by tomojitakasu** [comment]
Check UBX-RXM-SFRBX messages in your M8P log.

RTKLIB_bin can be found at:
https://github.com/tomojitakasu/RTKLIB_bin

**Comment by sobido** [comment]
Thanks. 
Effectively both UBX-RXM-SFRBX + UBX-RXM-RAWX need to be  activated for M8P in C94-M8P module, to be transformed  in RTKConv ( .nav and .pos file ) and used for post treatment.
UBX-RXM-SFRBX alone is not enough, as well as RAWX.

Both older 2.4.3b8 RTKLIB and new 2.4.3b12 are working for that.

I am however a little bit confused by the new version of the "bin" files because this directory is mixing several version of RTKLIB . When you open the new 2.4.3b12 rtklaunch , there is then only mention of 2.4.2 RTKLIB !! ... You don't really know where you are after.
In comparison, when you open the older 2.4.3 b8 rtklaunch , you are clearly advised that this is the 2.4.3b8 version . 

Thanks
