### ISSUE TITLE
Base NMEA output in latlon mode

### ISSUE THREAD

**Issue by egorf** [tomojitakasu/RTKLIB#179]
Hi!

I've been testing the NMEA GGA message sent to the base. It seems that in **latlon** mode the coordinates are wrong.

With the following settings

```
inpstr2-nmeareq    =latlon      # (0:off,1:latlon,2:single)
inpstr2-nmealat    =60          # (deg)
inpstr2-nmealon    =30          # (deg)
```

I get this:

`$GPGGA,161309.57,5960.0000000,N,02960.0000000,E,1,00,1.0,-15.988,M,15.988,M,0.0,*57`

The **single** mode works perfectly, though.

RTKLIB version 2.4.2

**Comment by tomojitakasu** [comment]
Thanks. It is fixed in 2.4.3 b25.
