### ISSUE TITLE
Ublox M8N half cycle valid bit not supported

### ISSUE THREAD

**Issue by rtklibexplorer** [tomojitakasu/RTKLIB#181]
Although undocumented,  it seems evident from observations of the raw M8N data that bit 7 of the status byte is equivalent to the "half cycle valid" bit on the Ublox M8T.  Including this bit in the RTKLIB translation from raw ublox data to Rinex noticeably improves the solution.  See [here](https://rtklibexplorer.wordpress.com/2016/06/30/ublox-m8n-half-cycle-valid-bit/) for more details and an example.

**Comment by tomojitakasu** [comment]
Thanks. It is fixed in 2.4.3 b13.
