### ISSUE TITLE
rnx2rtkp: no obs dataobs data

### ISSUE THREAD

**Issue by Deginch** [tomojitakasu/RTKLIB#183]
when I using rnx2rtkp handling data provided by convbin , the data include obs and nav , but it returns "no obs dataobs data". Can rnx2rtkp handle obs data and how to configure it?
there is my command: rnx2rtkp -p 4 -f 4 -a -o test.pos /home/sheldon/data/1_rover.obs /home/sheldon/data/1_base.obs.

**Comment by freeExec** [comment]
Perhaps the time of the rover and the base does not overlap. For greater efficiency should be given and the files themselves.

**Comment by tomojitakasu** [comment]
Thanks. It is fixed in 2.4.3 b16.
