### ISSUE TITLE
A tiny bug in rtksrv.c

### ISSUE THREAD

**Issue by yigiter** [tomojitakasu/RTKLIB#184]
Line 203 in rtksvr.c causes the rtklib to ignore all bradcasted utc/ion parameters due to incompatibility with the option definitions.
The original form of the file is as follows:

```
202:    else if (ret==9) { /* ion/utc parameters */
203:        if (svr->navsel==index||svr->navsel>=3) {
204:            for (i=0;i<8;i++) svr->nav.ion_gps[i]=nav->ion_gps[i];

```
As seen from above, the code assumes "all" option has the value "3". However, it is in fact "0". Hence, the code should be corrected as follows:

```
202:    else if (ret==9) { /* ion/utc parameters */
203:        if (!svr->navsel||svr->navsel==index+1) { //(svr->navsel==index||svr->navsel>=3)
204:            for (i=0;i<8;i++) svr->nav.ion_gps[i]=nav->ion_gps[i];
```

**Comment by tomojitakasu** [comment]
Thanks. It is fixed in 2.4.3 b16.
