### ISSUE TITLE
strsvr ublox M8P COM1 getconfig error

### ISSUE THREAD

**Issue by johschmitz** [tomojitakasu/RTKLIB#187]
I am trying to send NTRIP RTCM3 to the M8P using strsvr.
I am running the newest binary version from github ver.2.4.3 b13 in wine
When i click start I get the getconfig error.
Anybody has an idea what's going wrong.
In rtknavi it is working well over the serial port.

![screenshot from 2016-07-21 17 56 38](https://cloud.githubusercontent.com/assets/771979/17029702/81f71000-4f6c-11e6-9da4-c56fe716377f.png)

**Comment by tomojitakasu** [comment]
The "(5)" means Windows Error Code ERROR_ACCESS_DENIED after calling WIN32 API GetCommConfig().

https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx

**Comment by johschmitz** [comment]
And why does this happen in strsvr and not in rtknavi? Very weird.. What's the difference between the way they try to access the port?

**Comment by johschmitz** [comment]
I just tested this under Windows 10 with the same hardware and it works.
So this is a problem with Linux/Wine due to the way strsvr tries to access the com port.
Would be good if it could be unified and use the same API like rtknavi, because then it will work with wine.
