### ISSUE TITLE
Time delay between RTKNAV and RTKPOST

### ISSUE THREAD

**Issue by uziak** [tomojitakasu/RTKLIB#188]
Hi everyone.

I am trying to use RTKNAV for measuring the heading of a vehicle. I am using Moving-Base mode.
For validation, I used another GPS compass (Hemispher). The problem was that there was time delay between the GPS compass and a "sol" data generated by RTKNAV (1 sec) 
Although, when I used RTKPOST and did post-processing using "log" data, the delay was very small (0.1 sec).
Does anybody know the reason of the time difference between real-time solution and post-processing solution?

I used two M8Ns and Windows PC or Raspberry pi 3. In the case of Raspi, I used rtkrcv. I found 0.5 sec delay in "sol" file by rtkrcv.

**Comment by DavidKelleySCSC** [comment]
Are you saying the delay/offset was in the time you got the
      outputs or in the time stamps of the outputs? 
    
    Also, which Hemisphere board were you using.  You also might was
      want to take the Hemi raw data, post process that with the same
      RTKPOST settings and see how your time offsets compare.  
    
    Regards, DC Kelley
    
    
    On 7/23/2016 8:35 AM, uziak wrote:
    
    
      Hi everyone.
      I am trying to use RTKNAV for measuring the heading of a
        vehicle. I am using Moving-Base mode.
        For validation, I used another GPS compass (Hemispher). The
        problem was that there was time delay between the GPS compass
        and a "sol" data generated by RTKNAV (1 sec) 
        Although, when I used RTKPOST and did post-processing using
        "log" data, the delay was very small (0.1 sec).
        Does anybody know the reason of the time difference between
        real-time solution and post-processing solution?
      I used two M8Ns and Windows PC or Raspberry pi 3. In the case
        of Raspi, I used rtkrcv. I found 0.5 sec delay in "sol" file by
        rtkrcv.

**Comment by uziak** [comment]
Dear DC Kelley

Thank you for a comment. I compared them based on time stamp. What I did was as following. 
1. Put two antennae and a gps compass on a same rotating table. 
2. Rotate a table at certain moment.
3. Save a solution data and raw data with rtklib and gps compass heading data(HEHDT) simultaneously. 
4. Plot the heading datas from sol file, post-processed sol file and gps compass file. 

From the plots, in a realtime sol file the heading started moving 0.5 sec later from the heading measured by post processing and gps compass. 

A gps compass I used was ssV-102

Regards, Uziak

**Comment by rugimuleh** [comment]
sorry for asking, im newbie in this programing. 
i had a project to build the rtk lib, but i (honestly dont know anything about rtk lib and how to use it) want to know what compiler should i use to opeh this project?
can i open it on visual studio? thx for your attention.

**Comment by uziak** [comment]
Hi rugimuleh

Your question was posted to wrong place, though I was also a newbie a few month ago, I can tell you some advice.

If you use Windows, just click "download zip" on the top page of rtklib github page. You will have exe files in bin folder. You may find manual in doc folder. If you use Linux, first install github and then download rtklib 
Type following. 
$ git clone https://github.com/tomojitakasu/RTKLIB.git
$ cd RTKLIB/app
$ chmod 755 makeall.sh
$ ./makeall.sh
$ cd

Hope it will work

Uziak 

2016/07/26 13:21$B!"(Brugimuleh <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by uziak** [comment]
Dear friends. The problem was solved!

First, the delay to the Hemisphere GPS compass was my misunderstanding.

My solution file generated by rtkrcv for 5Hz sampling included a time stamp column as below.
In one second, there were 5 datas.
% GPST
1908 222079
1908 222079
1908 222079
1908 222079
1908 222079
1908 222080
1908 222080
The time does not have decimal digit, so I thought the first row was 
1908 222079.0 and a second row was 
1908 222079.2 and so on.
But according to Dr. Takasu, it uses rounding rule, so the first row was
1908 222078.6 and the second row was
1908 222078.8 and so on

That was why I mistakenly thought there was 0.4 sec delay between the RTKNAV and RTKPOST.
RTKPOST outputs time stamp with decimal digits. 

Thank you very much DC.
However I am still wondering how to add decimal digit to a sol file. I changed out-timendec value to 1 or 2, nothing happened. I am attaching my .conf file. 
[myrtkmbl.conf.txt](https://github.com/tomojitakasu/RTKLIB/files/397160/myrtkmbl.conf.txt)

**Comment by coandrei** [comment]
@uziak:

These options in your config file are your friends:
> out-timesys        =jst       # (0:gpst,1:utc,2:jst)
> out-timeform       =tow        # (0:tow,1:hms)
> out-timendec       =2

though I am wondering what is JST and why did you select this time?

**Comment by uziak** [comment]
Hi coandrei

JST stands for Japanese Standard Time. I don't need to use this time, though I just wanted to see the change in a solution file, If  I changed three lines you suggested. The time stamp is always
recorded in gpst and there is no decimal. When I used RTKNAV.exe in Windows, the change of the option was reflected to the result properly. 

Thank you very much!
