### ISSUE TITLE
Can´t convert .ubx into RINEX using intervall function

### ISSUE THREAD

**Issue by chunkleader** [tomojitakasu/RTKLIB#190]
Hello, 
I´m trying to convert the logged .ubx files into the RINEX format using rtkconv.exe, but the .obs file isn´t created after the conversion is completed. The measurement period of the receiver was in the first attempt 75ms and the intervall for the conversion in rtkconv was set to 1s. I tried 100ms too, since 1000ms is divisble by 100ms, but without success.
I analyzed the debugger trace file and I get these message on level 2: "no broadcast ephemeris", "no broadcast clock" and "point position error (lack of valid sats ns=4)".
Regards

**Comment by mohamedamjad** [comment]
could you please join an ubx sample file?

**Comment by chunkleader** [comment]
[rover.zip](https://github.com/tomojitakasu/RTKLIB/files/384014/rover.zip)

**Comment by tomojitakasu** [comment]
Use RTKCONV Options - Option "-TADJ=0.075" to adjust time-tags to round number of the TADJ parameter (s).
