### ISSUE TITLE
rtkconv can't convert RTCM3 Beidou B1 observations to rinex

### ISSUE THREAD

**Issue by linkaiqin** [tomojitakasu/RTKLIB#191]
rtkconv can't convert RTCM3 Beidou B1 observations to rinex 3.02. 
To fix the issue, modify convrnx.c L544.

`    const unsigned char codes_rtcm3[7][8]={`
`         ......`
`        {CODE_L1C,CODE_L2C,CODE_L7I},{0}`
`    };`
---->
`    const unsigned char codes_rtcm3[7][8]={`
`         ......`
`        {CODE_L1C,CODE_L2C,CODE_L7I,CODE_L1I}},{0}`
`    };`

**Comment by tomojitakasu** [comment]
Thanks. It is fixed in 2.4.3 b16.
