### ISSUE TITLE
RAD Studio 10.1 Berlin support

### ISSUE THREAD

**Issue by astrodanco** [tomojitakasu/RTKLIB#195]
Please upgrade your compiler to 10.1 Berlin so that you can run into the same build problems we have and which have made us dead in the water for pending code pull requests we need to make. Thank you.

Building RTKNAVI gets these errors. Everything else builds fine.

[bcc32 Error] mondlg.cpp(1232): E2015 Ambiguity between 'std::fabs(long double)' and 'std::fabs(float)'
[bcc32 Error] mondlg.cpp(1246): E2015 Ambiguity between 'std::fabs(long double)' and 'std::fabs(float)'
[bcc32 Error] mondlg.cpp(1648): E2015 Ambiguity between 'std::fabs(long double)' and 'std::fabs(float)'

[ilink32 Error] Error: Unresolved external '__fastcall Vcl::Controls::TWinControl::GetDeviceContext(void *&)' referenced from H:\GITHUB\RTKLIB\APP\RTKNAVI\DEBUG_BUILD\NAVIMAIN.OBJ
[ilink32 Error] Error: Unresolved external '__fastcall Vcl::Forms::TCustomForm::PaintWindow(void *)' referenced from H:\GITHUB\RTKLIB\APP\RTKNAVI\DEBUG_BUILD\NAVIMAIN.OBJ
[ilink32 Error] Error: Unresolved external '__fastcall Vcl::Graphics::TFont::SetHandle(void * const)' referenced from H:\GITHUB\RTKLIB\APP\RTKNAVI\DEBUG_BUILD\GRAPH.OBJ

**Comment by tomojitakasu** [comment]
Thanks. It is fixed in rtklib 2.4.3 b17.
