### ISSUE TITLE
Beidou bug with convbin and rnx2rtkp

### ISSUE THREAD

**Issue by Deginch** [tomojitakasu/RTKLIB#197]
I can not get Beidou pos solution by convbin and rnx2rtkp on linux.
this is my command: 
1. convbin -r ubx -v 3.02 -od -os -d data/obs data/raw/31001
2. convbin -r ubx -v 3.02 -od -os -d data/obs data/raw/31001
3. rnx2rtkp -p 4 -m 0 -f 1 -c -i -h -a -t -o data/pos/1.pos data/obs/42020.obs data/obs/31001.obs data/obs/42020.nav
there isn't Beidou satellites in pos result.

**Comment by tomojitakasu** [comment]
Without -k option, you can only enable GPS and GLO.
For BDS, GAL, QZS, SBS and IRN, use -k option and set the pos1-navsys in the conf file.

**Comment by Deginch** [comment]
It is fixed, thank you very much!

**Comment by coandrei** [comment]
@Deginch: Which version are your convbin and rnx2rtkp? 2.4.3_b16?
