### ISSUE TITLE
Decode of cycle-slip flag for Ublox RXM-RAWX command

### ISSUE THREAD

**Issue by rtklibexplorer** [tomojitakasu/RTKLIB#204]
The decode_rxmrawx() function used to decode the raw output of the M8T receiver in ublox.c does not take advantage of the carrier phase quality indicator (cpStdev) status from the receiver when setting the cycle-slip (LLI) flag.  Failure to delay the setting of the cycle-slip flag until the quality of the phase measurement is sufficient to be used to reset the carrier-phase bias state can cause large erroneous spikes in the solution.  Modifying this code to match the functionality of the decode_trkmeas() function used to decode raw output from the Ublox M8N receiver resolves the problem.  Although the names and definitions of the carrier phase quality indicators are a little different between the two receivers (mesQI vs cpStdev), I believe they can be used in the same way.

I've incluced more details on the issue [here](https://rtklibexplorer.wordpress.com/2016/08/03/ublox-m8n-vs-m8t-part-3/) and a proposed code change [here](https://github.com/rtklibexplorer/RTKLIB/commit/062e79da228cbc447a45df90c81d17702738681e)

**Comment by tomojitakasu** [comment]
Thanks.
The proposed modification seems to detect too many cycle slips. In some cases, it degrades solutions.
Only carrier-phase valid test with std-dev in ubx-rxm-rawx is added in rtklib 2.4.3 b17.

**Comment by rtklibexplorer** [comment]
Thanks for the quick response to this issue!  Unfortunately I don't believe the fix in 2.4.3 b17 is sufficient to completely resolve the issue.  Part of the problem is that the quick summary I wrote above does not fully describe the problem.  

The way that the decode_trkmeas() function uses the the carrier phase quality indicator to decode the raw M8N output insures that if a cycle-slip is followed by an invalid carrier-phase measurement then the next valid carrier-phase measurement will always be flagged as a cycle-slip.  The decode_rxmrawx() function does not have this guarantee and hence can allow a cycle-slip to go unflagged.  My proposed fix closed this hole but I believe the b17 code does not.  I demonstrated this problem in more detail near the end of [this blog post](https://rtklibexplorer.wordpress.com/2016/07/30/ublox-m8n-vs-m8t-part-2/), the post previous to the one I cited above.

Replacing this line of code in b 17:

raw->obs.data[n].LLI[0]=0; 

with this line of code:

raw->obs.data[n].LLI[0]=cpstd>=CPSTD_VALID?1:0;

resolves the problem in my testing.

**Comment by tomojitakasu** [comment]
What F/W version of M8T do you use?
With M8T F/W 3.01, the cycle-slip detection by std-dev of carrier-phase often degrades the results.

**Comment by rtklibexplorer** [comment]
I am using M8T F/W 2.30.  I will upgrade to F/W 3.01 and re-test.

**Comment by tomojitakasu** [comment]
The u-blox receiver option -STD_SLIP is added in 2.4.3 b19.
If you want to handle a measurement with "cpStdDev" in UBX-RXM-RAWX equal or more than X as a cycle-slip, set the receiver option -STD_SLIP=X. Without the option, cycle-slips are detected only by "locktime".

**Comment by rtklibexplorer** [comment]
Thanks, I haven't had time yet to try the 3.01 F/W but the new option resolves the issue I was seeing with the M8T 2.3 F/W.

Thanks too for picking up the SBAS half-cycle valid fix.  I had hesitated on submitting it because it is only a "best guess" at half cycle status and not a true translation but I do find it definitely helps when using the SBAS satellites for range information.
