### ISSUE TITLE
Run Rtknavi with Rinex files

### ISSUE THREAD

**Issue by adbor** [tomojitakasu/RTKLIB#205]
I have 2 rinex files and would like to process them using rtknavi.exe ( not with rtkpost.exe ). I do not see such "Rinex file"  option in rtknavi. So I have 2 questions.

1. Is it possible to run rtknave with Rinex files
2. If not, is it possible to convert Rinex files to some other formats which rtknavi accepts. (using rtklib or any other utils)

**Comment by tomojitakasu** [comment]
1. No
2. No. Use RTKPOST.
