### ISSUE TITLE
wild-cards use in file path of rtkpost.

### ISSUE THREAD

**Issue by tom-clancy** [tomojitakasu/RTKLIB#208]
hi！
   i am a newbie as for RTKLIB.
   problem in data processing in ppp static model.
   data: three stastions in HongKong in one day.
   when i input RINEX obeservation data file path of the rover receiver in the text field"RINEX    OBS(:Rover)"m,wild-cards(eg.%r  %n  * ) are included in the file path.  it won't go on and tell me that   "error:no obs data(?"
     please give me some advice.
    attached the picture of  configuration.   
![qq 20160813224826](https://cloud.githubusercontent.com/assets/20356142/17736751/228c87e8-64bc-11e6-98a3-15aaf8f72248.jpg)
![qq 20160813225048](https://cloud.githubusercontent.com/assets/20356142/17736752/2365242c-64bc-11e6-8d5a-50cbd5dd0852.jpg)

**Comment by tomojitakasu** [comment]
The keyword %r in the path is replaced by a Station ID specified in Options - Misc - Rovers.
