### ISSUE TITLE
RTKNAVI Raw Antenna Position option does not set svr->rtk.opt.refpos not set

### ISSUE THREAD

**Issue by astrodanco** [tomojitakasu/RTKLIB#210]
2.4.3 In RTKNAVI settings, when setting the base station position to "Raw Antenna Position" the setting does not take effect. This setting should cause **svr->rtk.opt.refpos** to be set to **POSOPT_RAW (5)**, but it does not.

**Comment by tomojitakasu** [comment]
Thanks. It is fixed in 2.4.3 b19.

**Comment by astrodanco** [comment]
Re-tested the fix here. It's fixed.
