### ISSUE TITLE
"No Common Satellite" and "No double-differenced residual" errors

### ISSUE THREAD

**Issue by chesrae** [tomojitakasu/RTKLIB#218]
I have two NEO-M8T receivers acting as a base and rover connected via USB serial to the same laptop.   I have both receivers set up in an open field directly connected to the laptop about 20 feet apart.

I am able to get reasonable results in "Single" Mode.  In "Moving-Base" mode it stays at at a Float fix indefinitely.  Positioning in this mode is not significantly more stable than in "Single" Mode.  I have good signal (> 40 dBHz) of > 8 satellites (GPS/GLONASS) at all times.  

I set a base position based on the results of "Single" Mode.

In "Kinematic" or "Static" mode I get the following errors: "No Common Satellite" and "No double-differenced residual".  They usually occur in long individual runs.  For example, I will get "No Common Satellite" 20 times in a row then "No double differenced residual" 30 times in a row.

I assume this is a silly setup issue.   Any help or advice would be appreciated.

[rover.txt](https://github.com/tomojitakasu/RTKLIB/files/465661/rover.txt)
[base.txt](https://github.com/tomojitakasu/RTKLIB/files/465662/base.txt)
[rtknavi.txt](https://github.com/tomojitakasu/RTKLIB/files/465664/rtknavi.txt)

**Comment by mabrowning** [comment]
Did you solve your issue? I am having exactly the same problem.

**Comment by chesrae** [comment]
I am achieving excellent results at this time.  I am not sure what specific issue I was experiencing above.  I started using the rtklib fork in the links below.  There are also a number of very good articles discussing various technique and settings.  I would highly recommend trying the below fork out and reading every article on the blog - very informative.

https://rtklibexplorer.wordpress.com/
http://rtkexplorer.com/
