### ISSUE TITLE
rtkrcv.exe

### ISSUE THREAD

**Issue by gschora** [tomojitakasu/RTKLIB#22]
Is it possible to release the console app rtkrcv as windows executable?

I wasn't able to compile it myself with VS2013 express, or crosscompile it on Ubuntu.
Or maybe someone can give me a hint how to crosscompile it?

**Comment by ahanktcd** [comment]
Can someone point me to rtkrcv.exe compiled?  I do not know how to compile it.  Thanks!

**Comment by holishing** [comment]
Maybe you can try GNU mingw tools to complie this stuff.

**Comment by holishing** [comment]
But I am not sure how to build GUI tools here, maybe Qt or Virtual Studio will be needed?

**Comment by ahanktcd** [comment]
rtkrcv isn't a GUI tool, it is command line, I think, based on the docs.  I haven't been able to try it, though.  Basically, it is an embedded application and I want to have rtknavi just start when the computer turns on.  From what I can read in the manual, rtkrcv is just that, a command-line self-starting version of rtknavi.  Thanks.

**Comment by miguelfaro1180507** [comment]
Can someone send me to rtkrcv.exe compiled? I am having a very hard time porting and compiling it, a i really need to use it so i can automate rtk corrections on a windows server. Thanks!
