### ISSUE TITLE
rtknavi - problem with reading ubx & rtcm3 from file

### ISSUE THREAD

**Issue by laurioma** [tomojitakasu/RTKLIB#221]
Hi! I am trying to use rtcm and ubx files which I have previously created with rtklib by logging base station and rover input data. Something seems to be wrong with rtcm data reading. Rtknavi reads rtcm file very quickly and reports "end(2)" on UI at the moment when it has read ~10% or the rover input data. However the recordings are from same period and should end at the same time. Also rtknavi is not displaying any solution. If I convert both files to RINEX and use rtkpost with same settings, then rtk solution is calculated for the whole track nicely. What goes wrong with rtknavi?

I have uploaded rtknavi.ini, base station input gnss_rtk_base_20160910-1426.rtcm3, rover input gnss_rtk_rover_20160910-1426.ubx and rtknavi log file rtknavi_201609150520.trace (log level 3) there:
Logs https://www.dropbox.com/sh/npq72tjjpncjq18/AAD0yXnFIjB1iPXeQJT5ozmZa?dl=0

**Comment by tomojitakasu** [comment]
See the manual 3.2 (10) and check the tag-file.

**Comment by laurioma** [comment]
Thanx! problem solved :)
