### ISSUE TITLE
Fit interval/flag

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [tomojitakasu/RTKLIB#223]
1) RINEX 3.03 standard clarifies that Fit interval for QZSS must be written to RINEX as flag not as interval in meters.
2) This field is not used for BDS but it is written to eph struct in rtcm3.c > `decode_type1047`. Unfortunately I can't find neither specification nor data sample of this message to check if this field actually present.

**Comment by tomojitakasu** [comment]
1) Thanks. It will be fixed in next 2.4.3 beta.
2) MT1047 is just a tentative RTKLIB extension. It will be deleted in future releases. The RTCM draft assigns MT63 to BDS ephemerides at this moment.

**Comment by Fr0sT-Brutal** [comment]
Thanks for clarifying status of MT1047, I'll remove it from my software
