### ISSUE TITLE
QT port b26 compilation problem 

### ISSUE THREAD

**Issue by alquez** [tomojitakasu/RTKLIB#234]
(inb4 unsupported: i know)

I'm building snapshots of QT port for Windows platform (using mingw32)  on semi-regular basis (b24 builds with minor source hacks, b19 without if i remember correctly). Recently, I've been able to get rid of some errors by using '-fpermissive' flag, but now i ran into this:

`\RTKLIB\app\rtknavi_qt\navimain.cpp:1095: error: cannot convert 'prcopt_t*' to 'const double*' for argument '13' to 'int rtksvrstart(rtksvr_t*, int, int, int*, char**, int*, int, char**, char**, char**, int, int, const double*, prcopt_t*, solopt_t*, stream_t*, char*)'`

Any ideas? Someone managed to compile b26 qt port under win? 
Thanks in advance

**Comment by JensReimann** [comment]
Do you use Tomoji Takasu's repository? Recently there been some incompatible API changes which can cause your problems. The Qt port is currently not updated in-tree by Tomoji Takasu. See https://github.com/JensReimann/RTKLIB/tree/rtklib_2.4.3 repository for a recent version. I will try to merge these changes back to the official tree as soon as I got a little more time.

**Comment by alquez** [comment]
That's great! Thank you very much! I will keep an eye on your repo.
