### ISSUE TITLE
Compilation warning in postpos.c [rtklib_2.4.3 branch]

### ISSUE THREAD

**Issue by sergeyastakhov** [tomojitakasu/RTKLIB#236]
When compiling [postpos.c](https://github.com/tomojitakasu/RTKLIB/blob/rtklib_2.4.3/src/postpos.c#L1006) in rtklib_2.4.3 branch, there is warning generated due incorrect 'if' condition.

```
...RTKLIB/src/postpos.c:1006:40: warning: address of array 'fopt->blq' will always evaluate to 'true' [-Wpointer-bool-conversion]
    if (popt_.mode>PMODE_SINGLE&&fopt->blq) {
                               ~~~~~~~~^~~
1 warning generated.
```

Looks like typo and it should be "**fopt->blq[0]**" instead.

**Comment by tomojitakasu** [comment]
Thanks.
It is fixed in 2.4.3 b27.
