### ISSUE TITLE
issue of the satellites' antenna offset correction in File "preceph.c"

### ISSUE THREAD

**Issue by sailvssea** [tomojitakasu/RTKLIB#237]
It is something wrong in the calculation of the satellites' antenna offset -satantoff(time, rss, sat, nav, dant) at line 733 in peph2pos function - in file preceph.c .

Because this calculation the time is not the true time which means the proper time has been minused the **delt tt** **"0.001s"** at line 727 which is used to calculate the velocity of the satellites.

Although this tiny time span has little impact on the antenna offset correction, I think it is also a considerable bug to be fix to improve the readability and integraty of this software.

**Comment by tomojitakasu** [comment]
Thanks.
It is fixed in 2.4.3 b27.
