### ISSUE TITLE
how to add SBAS for navigation in u-Center

### ISSUE THREAD

**Issue by xiaomianhuxiao** [tomojitakasu/RTKLIB#257]
hello,  I'm using u-blox **C94-M8P** RTK-Applikations-Entwicklungsboard(two NEO-M8P-2 modul，1 base+1 rover) for RTK-Navigation,I have checked like this in u-Center ,because I wanted to **add SBAS for navigation**.
![1](https://cloud.githubusercontent.com/assets/23225352/21083235/49ffee1a-bfec-11e6-8999-aac648bfda3a.PNG)
but **after I clicked send buttom**, the configuration changed like the default configuration.
![2](https://cloud.githubusercontent.com/assets/23225352/21083249/a47b1be4-bfec-11e6-845c-2c5885a19714.PNG)
Does anyone know the right operation `?`
Thank you

**Comment by astrodanco** [comment]
You do realize that this isn't a UCENTER support forum, right?
