### ISSUE TITLE
problem about informations showed in table view of  Ucenter

### ISSUE THREAD

**Issue by xiaomianhuxiao** [tomojitakasu/RTKLIB#258]
hello,

I stored the measurement data of Rover and Base for postprocessing. From the table view, I can see many informations. Now **I just want to get a final solution about relative positions of Rover in txt or csv file**.I can save the information in table view as csv file, but it seems that the informations showed in table view are not right,for example, **the relPosE and relPosD**, when I compare them with the real-time informations showed in the UBX-NAV-RELPOSNED(relative position NED). 

Does anyone know the reason? or Do you have another simpler way to get a final solution about relative positions of Rover in txt or csv file?

![1](https://cloud.githubusercontent.com/assets/23225352/21296893/2a63a85a-c576-11e6-9e6f-1fb7e6ad3502.PNG)

**Comment by astrodanco** [comment]
You do realize that this isn't a UCENTER support forum, right?
