### ISSUE TITLE
How to save the raw measurement data of RTKNAVI

### ISSUE THREAD

**Issue by xiaomianhuxiao** [tomojitakasu/RTKLIB#259]
hello, I'm using u-blox C94-M8P RTK-Applikations-Entwicklungsboard(two NEO-M8P-2 modul，1 base+1 rover) for RTK-Navigation in RTKLIB.

configuration:

base: STRSVR(output: 1.TCP server (data transmission),**2. file(raw data storage)**)
rover: RTKNAVI(only solution about ENU or XYZ)

How can I **store the raw measurement data of rover**?

**Comment by tomojitakasu** [comment]
Please read 3.2 (17) of the manual.
