### ISSUE TITLE
problem about s showed in the table view of U-center

### ISSUE THREAD

**Issue by xiaomianhuxiao** [tomojitakasu/RTKLIB#260]
hello,

I'm using u-blox C94-M8P RTK-Applikations-Entwicklungsboard(two NEO-M8P-2 modul，1 base+1 rover) for RTK-Navigation in Ucenter 
I stored the measurement data of Rover and Base for postprocessing by C94-M8P. From the table view, I can see many informations. Now I just want to get a final solution about relative positions of Rover in txt or csv file.I think Ucenter can show the realtime relative positions itself, and the massages showed in the UBX-NAV-RELPOSNED(relative position NED) are right, but by the table view, you can see that only informationms about relPosN(relative North)are right,why,I have tried these operations on three computers, but the Problems are the same, does anyone know the solution?
![1](https://cloud.githubusercontent.com/assets/23225352/21363147/aba4d38c-c6eb-11e6-9733-f61656632331.PNG)

I need the precise solutions

**Comment by astrodanco** [comment]
You do realize that this isn't a UCENTER support forum, right?
