### ISSUE TITLE
Leap second on 2017 january 1st

### ISSUE THREAD

**Issue by geoweb-sk** [tomojitakasu/RTKLIB#263]
RTKLIB\src\rtkcmn.c is missing the additonal leap second that was introduced on 2017 january 1st

**Comment by arty86** [comment]
Just try to use 2.4.3 b26

**Comment by tomojitakasu** [comment]
Thanks.
It is fixed in rtklib 2.4.2 p12 in the master branch.
It has been already fixed in 2.4.3 b13 in the beta branch.
