### ISSUE TITLE
rtklib_2.4.3 rtkcmn.c compile for dll error!

### ISSUE THREAD

**Issue by Jin-Whu** [tomojitakasu/RTKLIB#267]
@tomojitakasu 
In **rtklib.h**, **global variables** have no **EXPORT**, but in **rtkcmn.c** these variables have **EXPORT**, so compile will has error for redefinition!

**Comment by tomojitakasu** [comment]
Thanks. It is fixed in 2.4.3 b27.

**Comment by kun-shang** [comment]
Doesn't seem to be fixed to me in b29. I have to manually add EXPORT to sysopts, igpband1 and igpband2 in rtklib.h to get rid of the redefinition error.
