### ISSUE TITLE
Bugs decoding Javad receiver input

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [tomojitakasu/RTKLIB#274]
src/rcv/javad.c, function `decode_rx`

According to recent GREIS manual (Aug'16), there are 2 incorrect constants: Asys for SBAS is 0.125 (not 0.115) and for GAL it is 0.085 (not 0.09).
Moreover, the whole construction is better to be changed to `switch` operator (much more efficient, and removing potentially buggy place where a new GNSS is added but the condition is forgot thus following the `else` branch).

**Comment by Fr0sT-Brutal** [comment]
Addition: as Javad guys told me, they also changed Ksys for Galileo from 1E-11 to 2E-11 in firmware 3.7.

**Comment by Fr0sT-Brutal** [comment]
Addition: bugs in `tofreq()` for BDS. First thing, GREIS signal/msg type "5" corresponds to CODE_L6I. Second, AFAIU Beidou's frequency is taken from the common frequency array while it uses different values so there should be a separate BDS processing like it is for GLO.

**Comment by tomojitakasu** [comment]
Thanks. These are fixed in 2.4.3 b27.
Ksys for Galileo is still 1E-11 defined by F/W 3.6.7.
