### ISSUE TITLE
RINEX 2.11 "no obs" in 2.4.3 while working fine in 2.4.2

### ISSUE THREAD

**Issue by wjax** [tomojitakasu/RTKLIB#289]
It seems there is a problem in 2.4.3 b26 reading RINEX 2.11 from Andalusia Government CORS station.

If used with RTKPLOT or RTKPOST 2.4.3 b26 it says "no obs". However if used that RINEX with 2.4.2 p12 it works fine.

Attatched files to test
[sevi357l.zip](https://github.com/tomojitakasu/RTKLIB/files/870687/sevi357l.zip)

**Comment by tomojitakasu** [comment]
This is due to a bug on command search path handling. Compressed observation files cannot be extracted by improper search path for GZIP or CRX2RNX.

It is fixed in 2.4.3 b27.
