### ISSUE TITLE
Extended RAW meas from skytraq

### ISSUE THREAD

**Issue by PellePettersson** [tomojitakasu/RTKLIB#291]
Will there be developed support for Extended raw (0xE5) to RTKNAVI?
I am using NAVSPARK and would like to have that.
/Pelle

**Comment by tomojitakasu** [comment]
It is supported in 2.4.3 b27 but still experimental with few tests.

**Comment by PellePettersson** [comment]
Ok. I Will update my SW. and  give it a tr. Thanks for answering.  / Pelle

**Comment by tomojitakasu** [comment]
Some bugs are fixed in 2.4.3 b28. Thanks Ryan.
