### ISSUE TITLE
Cannot use "./rtkrcv -s" command in version 2.4.3(b27)

### ISSUE THREAD

**Issue by cloudnavi** [tomojitakasu/RTKLIB#297]
When using 2.4.2 and 2.4.3(b22), we can use "./rtkrcv -s" command to launch the app "rtkrcv", yet it cannot take effect in the version 2.4.3(b27)

**Comment by zhaozoz** [comment]
In the file app/rtkrcv/rtkrcv.c, line 1632, version 2.4.3(b27) 
     /* start rtk server */
     if (start) {
-        startsvr(NULL);
+        startsvr(con[0]->vt);
     }
     while (!intflg) {

**Comment by cloudnavi** [comment]
solved,thx
