### ISSUE TITLE
I have some questions in eph2clk () function

### ISSUE THREAD

**Issue by llwaltj206513** [tomojitakasu/RTKLIB#302]
Why need to iterate three times in the calculation of satellite clock‐bias
Thank you
Best regards.

**Comment by llwaltj206513** [comment]
I would like to ask on the serial read and write did not open multi-threaded Linux, why should open a multi-threaded in the windows

**Comment by tomojitakasu** [comment]
(1) SV clock parameters in navigation data are defined in GPST. However satellite clocks usually have some bias to GPST. You have to count the bias.
(2) Sorry, I don't remember the specific reason. In windows, closing handle of serial devices was sometimes blocked. So read/write threads was to ensure closing device cleanly. Maybe ...

**Comment by llwaltj206513** [comment]
Appreciated your reply so quickly,But I do not know why the satellite clocks bias needs to be counted three times in eph2clk () function,as far as I'm concerned,it is enough to calculate once in the satellite clocks bias.
extern double eph2clk(gtime_t time, const eph_t *eph)
{
    double t;
    int i;
    
    trace(4,"eph2clk : time=%s sat=%2d\n",time_str(time,3),eph->sat);
    
    t=timediff(time,eph->toc);
    
	/*  for (i=0;i<2;i++) {
	t-=eph->f0+eph->f1*t+eph->f2*t*t;
	}*/
    return eph->f0+eph->f1*t+eph->f2*t*t;
}

**Comment by tomojitakasu** [comment]
Sorry. previous my description was misleading.

eph2clk() is used in ephclk(), which is used in satposs().
In satposs(), the signal transmission time Ts is calculated by the signal reception time Tr minus pseudorange P devided by speed of light C. It's derived from the definition of pseudorange: P = C(Tr - Ts). Carefully note that Tr and Ts are measured by the receiver clock and the satellite clock respectively.

In satposs(), ephclk() is called with Ts, which is not in GPST. SV clock parameters in navigation data is defined in GPST. So we have to account for the satellite clock bias dT with Ts. Consequently, the satellite clock bias dT at the signal transmission time can be calculated by:
dT = CLK(T) = CLK(Ts - dT) 
where CLK(T) is calculated by the SV clock parameters and T is defined in GPST.

To solve the equation, we can use normal iteration technique with the initial value dT = 0.
Usually, a few iterations are enough for stable satellite atomic clocks. In RTKLIB, I selected fixed number (=3) of iterations.

**Comment by tomojitakasu** [comment]
I'd like add some info.

The max absolute values of Af0 and Af1 in GPS LNAV are 2^-10 (=1E-3) (s) and 2^-28 (=4E-9) (s/s) respectively. It is considered that satellite clock bias and drift are maintained within the ranges.

If we ignore the satellite clock bias (that is dT = CLK(Ts) used instead of dT = CLK(Ts - dT)), the max error due to the approximation is guessed as:
1E-3 (s) x 4E-9 (s/s) = 4E12 (s) = 1.2 mm

It seems negligible according to the current GPS LNAV accuracy.

So you are right for GPS (not sure for BeiDou, Galileo, QZSS or IRNSS.)

**Comment by llwaltj206513** [comment]
I really appreciate your help very much（ありがとう）
