### ISSUE TITLE
Problem about the function eph2pos()

### ISSUE THREAD

**Issue by zyzy1251** [tomojitakasu/RTKLIB#314]
` for (n=0,E=M,Ek=0.0;fabs(E-Ek)>RTOL_KEPLER&&n<MAX_ITER_KEPLER;n++) {
        Ek=E; E-=(E-eph->e*sin(E)-M)/(1.0-eph->e*cos(E));
    }
`
Execuse me , may i am wrong but i still think the algorithm here maybe wrong , accrording to Kepler's equotion `E－esinE=M`,why does `(1.0-eph->e*cos(E))` exist?or here may something special differenced with the Kepler's eqution?
Looking foward to your reply , thank you very much.

**Comment by forrestv** [comment]
https://en.wikipedia.org/wiki/Newton%27s_method

**Comment by zyzy1251** [comment]
Ah,thank you.
