### ISSUE TITLE
a question about receiver clock offset.

### ISSUE THREAD

**Issue by tachien** [tomojitakasu/RTKLIB#316]
The receiver clock offset in solution status file is in GPST. To verify its accuracy,can I compare it with the .clk file in IGST? Thx.

**Comment by tomojitakasu** [comment]
Yes, roughly.

The clock offset in the RTKLIB solution status file is in GPST.
IGST is a different time system from GPST, strictly.

For details, search "IGS time scale" by Google.

**Comment by tachien** [comment]
Thanks for replying so quickly!  I check it by Google. It says that the IGST is steered to Broadcast GPST. IGST is steered to stay within +-50ns of GPST. I'm doing some research about time transfer with PPP.  The bias between IGST and GPST maybe important to me. I don't understand why RTKLIB processes data with .clk .sp3 file in IGST. But it produce the receiver clock offset in GPST. Can it produce offset in IGST?

**Comment by tomojitakasu** [comment]
Sorry. I confirmed the codes again.

The time system of RTKLIB solutions depends on the option "satellite ephemeris/clock" and input broadcast clocks or precise clocks.

If you select "Precise" and input the IGS final clock, it will be in IGST. It is typically in PPP modes. Please carefully check other precise clocks.

With "broadcast", it is usually GPST. As a special case, it would be GLONASST with only GLONASS. GPST always precedes other time systems in mixed satellite cases.

With other selections like "broadcast+SBAS" or "broadcast+SSR APC", it depends on the correction provider. For example, it may be WAAS time system with WAAS. I'm not sure the details.

**Comment by tachien** [comment]
Very appreciate!

**Comment by tachien** [comment]
Very appreciate!There are two clock offsets in solution status files.If we use precise ephemeris from IGS,the clock offset can be produced. Why there are two different clock offsets in status file?Are they both in IGST?or in GPST and GLONASST? Waiting for your reply!

**Comment by tomojitakasu** [comment]
The second one shows (GLOT-GPST)+ISB_{GLO-GPS) in ns.
The manual B.3 (3) is invalid. It should be fixed.

**Comment by tachien** [comment]
THX！
