### ISSUE TITLE
A bug in satellite clock error computations

### ISSUE THREAD

**Issue by yigiter** [tomojitakasu/RTKLIB#329]
The true transmit time computed within satellite clock correction functions is wrong.
They should be modified as follows: 

[eph2clk @ ephemeris.c](https://github.com/tomojitakasu/RTKLIB/blob/628fcf44cbb84be752c42d333145d3259dcd04fc/src/ephemeris.c#L171):
```
double dt=0;
for (i=0;i<2;i++) {
    dt=eph->f0+eph->f1*(t-dt)+eph->f2*(t-dt)*(t-dt);
}
t=t-dt;
```

Same modification is also needed for geph2clk.
[geph2clk @ ephemeris.c](https://github.com/tomojitakasu/RTKLIB/blob/628fcf44cbb84be752c42d333145d3259dcd04fc/src/ephemeris.c#L305):
```
double dt=0;
for (i=0;i<2;i++) {
    dt=-geph->taun+geph->gamn*(t-dt);
}
t=t-dt;
```

**Comment by Matioupi** [comment]
if I understand correctly equations (1) and (2) from IRN-IS-200H document paragraph 20.3.3.3.3.1

the expression that eph2clk tries to evaluate should be solved from a quadratic equations that rise when replacing t from (1) into (2), with t_SV-t_oc being what is called "t" in original rtklib code.
then solving from delta_t_SV...

Doing so need to take delta_t_r into accout in the first place and I dont really understand neither your computation or the original one.

![image](https://user-images.githubusercontent.com/5566194/29610445-74bd360e-87fa-11e7-943a-0b29a476d592.png)

am I understanding wrong ?

**Comment by Matioupi** [comment]
oups, I missed the note on the nex page of ICD... saying that in equation (2), t could be assimilated to t_SV
still then, I don't understand the need for the for loop, either in original code, or in your proposed version.

**Comment by Marszsu** [comment]
NO CHANGES are needed in the original codes, explained as following:
The equations to compute satellite clock bias from brd eph are:
------------------------------------------------------------------------------------
t=t-delta_t_SV; 
delta_t_SV=af0+af1*(t-toc)+af2*(t-toc)²   /* without relativistic correction*/

The origina code:
-----------------------------
t=timediff(time,eph->toc);   /* t = t-toc*/ 

    for (i=0;i<2;i++) {
        t-=eph->f0+eph->f1*t+eph->f2*t*t;  /* t-toc = t-toc-(af0+af1*(t-toc)+af2*(t-toc)²) = (t - delta_t_SV) -toc */
    }
    return eph->f0+eph->f1*t+eph->f2*t*t; /* return delt_t_SV = af0+af1*(t-toc)+af2*(t-toc)²*/

The iteration is because an updated of t will change the t-toc in delta_t_SV=a0+a1*(t-toc)+a2*(t-toc)² which will again update your t as t = t -delta_t_SV. 3 iteration (two in the for loop and the last in return) is sufficient enough to have a high precision delt_t_SV

**Comment by Matioupi** [comment]
Ok, you confirmed what I'd thought about why there was those iterations.

Considering the fact that equations are not so complicated, I'm curious why not implementing the relativistic correction and full quadratic equation solve ? Any idea ?

The ICD seems to state that "0" iteration is enought, so being in between with iterations done without the relativistic correction taken into account and the full formulae seems strange at first glance.

**Comment by yigiter** [comment]
I understand the intention behind the for-loop. However, I still insist that the loop does not result in the way that you intended.

Lets suppose there is only clock bias. In this case, the value of the "t" at the oftput of the loop will we be

> t - 2*eph->f0

However, it must be:

> t - eph->f0

As a result, the loop caues the clock bias value substracted twice. Hence, it leads to a wrong satellite clock. I don't think that this is your intended outcome from that loop.

**Comment by tomojitakasu** [comment]
Just easy reason for the iteration. The t in IS-GPS  20.3.3.3.1 is defined as "GPS system time". However, the argument time of eph2clk() is as "time by satellite clock" (not true time) usually computed by t_rcv - P / C, where P is pesudorange. The pseudorange P is defined as P = C (t_rcv - t_sat), where t_rcv is signal reception time measured by receiver clock and t_sat is signal transmission time measured by satellite clock, respectively. So time for eph2clk() is t_sat, which is measured by satellite clock. As you know, the satellite clock has some offset to GPS system time. So you have to account for the clock bias to compute the clock bias itself.
