### ISSUE TITLE
A question about ppp-ar in rtklib2.4.2

### ISSUE THREAD

**Issue by tachien** [tomojitakasu/RTKLIB#330]
Dear professor,
   I use the rtklib2.4.2 in ppp-ar mode with vs2010. And the program does well in ppp-static. When I change the prcopt, solopt and filopt to work in ppp-ar mode, the program can't produce the solution,and the screen does not show the information of trace.What's wrong with it? Should I modify the configuration file?

**Comment by kauevestena** [comment]
I'm also with this problem, can you please reopen this issue?
