### ISSUE TITLE
RTKLIB and leap second

### ISSUE THREAD

**Issue by zuliani71** [tomojitakasu/RTKLIB#37]
Dear group,
can you help me to understand how rtklib handles the leap second issue? Currently most GNSS networks provide RTK streams with RTCM TYPE 14 enabled. That type helps with the GPS time. Is rtklib able to recognize that type?
Bye
David

**Comment by DavidKelleySCSC** [comment]
[Posted July 1st when I noticed I was using several older copies of RTKLIB...]

Can we get yesterday's Leap Sec event added and then the Borlan code respun for the windows side?  Know how to fix this in the raw code, but the RTKLIB GUI is a great tool for every day use. 
I am somewhat embarrassed to say I can not update and build the Windows GUI tools here. If I am just behind the times and this was added early this please ,please let me know what release point it was point in at.  

>> From tomojitakasu
>> The current version handles the leap seconds by using a hard-coded UTC-GPST table in rtklib/src/rtkcmn.c.

const static double leaps[][7]={ /* leap seconds {y,m,d,h,m,s,utc-gpst,...} */
     Please Add:  -->  (2015,7,0,0,0, -17)  <--
    {2012,7,1,0,0,0,-16},
    {2009,1,1,0,0,0,-15},
    {2006,1,1,0,0,0,-14},  . . .
