### ISSUE TITLE
STR2STR from rtcm3 stream to rtcm3 file

### ISSUE THREAD

**Issue by ambrogino** [tomojitakasu/RTKLIB#386]
Using a CUI command str2str from tcp stream rtcm3 to rtcm3 file seems this file has only GPS data.
Using a GUI program STRSVR instead, with the same tcp input I can make a file with GPS, Galileo an Beidou satellites.
Can anione help me?
Thankyou
Ambrogino

**Comment by rinex20** [comment]
paste your command here.

**Comment by ambrogino** [comment]
str2str -in tcpcli://130.192.28.48:11000#rtcm3 -out file://%date:~8,2%%date:~3,2%%date:~0,2%.rt3#rtcm3 5 

(in windows CDM environnement)
For now I've resolved the problem using the GUI program STRSVR with -auto option
Thank you

**Comment by rinex20** [comment]
if your input and output stream all is the same format,you never need add "#rtcm3" option.

**Comment by ambrogino** [comment]
Thank you so much for the answer. The problem is resolved!
