### ISSUE TITLE
ERROR Fit Interval Encode in GPS Ephemeris Data with RTCM 3 format

### ISSUE THREAD

**Issue by yangboy** [tomojitakasu/RTKLIB#396]
in rtcm3e.c, we could see the following encode code in function encode_type1019, but according to the ICD (GPS-IS-200H), eph->fit has two values, 0 means 4 hours of curve-fit interval while 1 means greater than 4 hours.
`setbitu(rtcm->buff,i, 1,eph->fit>0.0?0:1); i+=1;`
So I think the code will get the opposite result with the ICD, it should be changed to this:
`setbitu(rtcm->buff,i, 1,eph->fit>0.0?1:0); i+=1;`

**Comment by DavidKelleySCSC** [comment]
Humm...    [Side note; be sure the encoder follows the change is one is made, encode_type1019(), and qzss ephemerides, etc..]

This value is never used by RTKLIB, as as long as it is consistence (which it seems to be) any reverse seems to be transparent. And, as the other GNSS device message format seem to work and are reversible, sounds like rtc3.c and rctm3e.c are correct. 

Looking into this a bit deeper... In in the "char as bool" for used in C here...  0=false, 1= true, although here a double is being used for the same thing.  In the case you cite (the encoder), any non zero value results in the flag being set to one (>4 hours in GNSS if true). 

So a 'normal' frame will have a zero in the sub frames and should result in a zero in the .fit element, which might be better called something along the lines of '_not a normal fit_' (which is always longer then 4 hours) if one thinks of it as bool.  But it is not called that and perhaps that's the confusion. 

Here is the key decoder line. It is converting one bit to an unsigned int, then testing if for T/F and assigning a double. It assigned 4.0, but if you look into the ICD it could be other values, and this quite smart for other GNSS systems.  One presumes decoding the other value is something one for his grad students might have done.  
     `eph.fit =getbitu(rtcm->buff,i, 1)?0.0:4.0; /* 0:4hr,1:>4hr */`

And for background, text from the ICD  (I had to look it up):
20.3.3.4.3.1  Curve Fit Intervals. 
Bit 17 in word 10 of subframe 2 is a "fit interval" flag which indicates the curve fit interval used by  the  CS  (Block  II/Block IIA/IIR/IIR M/IIF)  and  SS  (GPS  III)  in  determining  the  ephemeris parameters, as follows:
    0  =  4 hours,
    1  =  greater than 4 hours.
The  relationship  of  the  curve fit  interval  to  transmission  time  and  the  timing  of  the  curve fit  intervals is covered in section 20.3.4.

Ok, I do see it now, but I think the code is correct as is.  Fit is not an ideal name and perhaps a comment like the below would help the next person

```
double fit;  /* fit interval (h) */
                 /* 0=normal std fit (4hr for GPS), >0.0 longer fit */

```

**Comment by yangboy** [comment]
yeah, thank you for your help. 

And I have to admit that the decoder in rtklib does match with the encoder, which means using decoder in rtklib could get the correct fit value.
