### ISSUE TITLE
Suddenly RTKNAVI not showing position solution

### ISSUE THREAD

**Issue by atanusan** [tomojitakasu/RTKLIB#398]
Dear sir,
RTKNAVI suddenly stop showing position solution. Everything is right; even the HEX and ASCII have been showing but the position solution is not shown. When I want to save output, it also shows blank file just with lat lon etc headers.
I cant understand, what is the reason behind it.

**Comment by CGEOS** [comment]
You should look at the status as messages are reporting trouble. The status icon is on bottom left side (square)

Joel Van Cranenbroeck Mng. Director 
CGEOS - Creative Geosensing sprl-s
www.cgeos.com

**Comment by atanusan** [comment]
Sir,
position solution (lat, lon and alt), DOPs and everything are shown in status bar but not displayed in the left side of RTKNAVI GUI.

**Comment by atanusan** [comment]
Dear sir, 
I have attached a snap of RTKNAVI. Please open the following link. 
https://drive.google.com/open?id=1P0GfZLVT7XM5UX5MSWaD1vY6DjsqSsBK
