### ISSUE TITLE
RTKRCV for Windows Revisited

### ISSUE THREAD

**Issue by mjs513** [tomojitakasu/RTKLIB#407]
I managed to get rtkrcv to compile using VS2017 using TermiWin (https://github.com/ChristianVisintin/termiWin) as a replacement for Termios and incorporated pthreads using instructions I found (http://www.technical-recipes.com/2016/using-posix-threads-in-microsoft-visual-studio/).  Had to do a couple of other minor changes as well but it compiles - v2.4.2 as well as 2.4.3 but does not work the way it should.

1.  It will read the GPS and NTRIP server specified and write the files that it needs to write as specified in the conf file) as long as I give it a com port for -d or -m.
2.  It will not create a console that I can connect to and it does not connect to the telenet port.  Unfortunately Windows does not have a telnet server capability under windows 10, only the client.  I have tried RealTerm, putty, terraterm to see if I can connect.

Now the problem I am having is that I don't know if it is a problem with termiWin or pthreads or the changes I made to rtkrcv and vt.c to get it to compile. 

In all honesty I am not a c++ programmer (know enough to be dangerous) and this is my first foray into using a C++ compiler.  I did notice that the experimental branch of minGW has a termios_api available.

Any help would be appreciated. I can post the files that I changed and termiWin files as well.  Everything else seems to work.

Thanks
Mike

**Comment by mjs513** [comment]
Ok.  as a FYI got it working.

**Comment by miguelfaro1180507** [comment]
I am having a hardtime compiling rtkrcv for windows (version b34k in this case). Could you provide the compiled .exe? Thank you!
