### ISSUE TITLE
Request for start and stop commands for ublox receivers

### ISSUE THREAD

**Issue by atanusan** [tomojitakasu/RTKLIB#411]
Dear sir, 
What would be the start and stop command for ublox m8t and ublox EVK m8n?
I mean which file that belongs to data folder of rtklibmaster package is suitable for the above mentioned ublox receivers?

**Comment by yjmenezes** [comment]
@atanusan 

inside rtkrcv.conf 

#edit path here
misc-startcmd      =./rtkstart.sh
misc-stopcmd       =./rtkshut.sh
file-cmdfile1      =data/ubx_raw_1hz.cmd
file-cmdfile2      =data/ubx_raw_1hz.cmd

i hope it helps you.

cheers

**Comment by atanusan** [comment]
Dear Julio, 
Thanks for your suggestion. 
Best regards.
