### ISSUE TITLE
Unable to connect my data source to rtk2go.com using rtklib str2str in Ubuntu

### ISSUE THREAD

**Issue by jeetb007** [tomojitakasu/RTKLIB#419]
I have a Ublox C94-M8P kit. I want to use it as a basestation. and send the correction message over internet to the rover. I am trying to use RTKlib srt2str. 
I used the command -
$ _str2str -in serial://ttyACM0#rtcm3 -out ntrip://Dude:BETATEST@rtk2go.com:2101/Dude_

It keeps giving error- _no mountpaint_ 
![image](https://user-images.githubusercontent.com/33603307/41808504-9d0e96a6-76de-11e8-95be-fbcec5005699.png)

when I try to export it to a file using the command
$_str2str -in serial://ttyACM0:115200 -out test06.rtcm3 -t 1_
 it works fine

However, when I tried using RTKlib strsvr(the GUI version for windows) in Ubuntu using Wine, I was able to send the message.
![image](https://user-images.githubusercontent.com/33603307/41808620-9151d20e-76e0-11e8-9a0c-2f935806c60c.png)
i gave the same parameters(User- Dude Pass-BETATEST mount point- Dude) to strsvr and used the software ntripclient-openwrt-package to check all the open messages available in rtk2go. the command is -
_./ntripclient -s rtk2go.com -p 2101_

So How do I create a mountpoint in RTK2go?

**Comment by DavidKelleySCSC** [comment]
This seems to be an RTKLIB setup command issue with str2str, I can see that you were able to connect to RTK2go.com:2101 just fine,  and there nothing you need to 'do' to connect other then setup a normal NTRIP Server as you did.  Look at the str2str command, I am sorry but I am on the road and do not have those documents here.

General Hint: You can see if your connection 'worked' by looking midway down the page on this status page:  http://rtk2go.com:2101/SNIP::STATUS  where you will see a list of connections that once were active but are no longer.  If you do not see your stream listed there (or above when active) you are not managing to reach the SNIP Caster.

**Comment by DavidKelleySCSC** [comment]
See my reply by private eMail as well.

**Comment by jeetb007** [comment]
Hello @DavidKelleySCSC ,

What private email?

**Comment by jeetb007** [comment]
I'm sorry @DavidKelleySCSC it seems you sent this email to my colleague.

> This was just brought to my attention when I came to the office (was traveling when I replied to your post at  https://github.com/tomojitakasu/RTKLIB/issues/419 ).     You can of course have your serial stream sent to RTK2go with either RTKLIB tools or with a SNIP tool for other to connect to it.  And it appears that you first did this on the last week.   [Dude first seen Jun 19, Tue 12:50:42, ]     And you can have other connect to the SNIP Caster directed as well.   
> As to strange issues with the console side of the RTKlib str2str app, I do not know why it differs.  Perhaps this is not a dead issues as the other two ways seem to work for you?   Please advise.

Yes we managed to send data to rtk2go, using RTKstrsvr in both windows and linux(using Wine), and were able to use it in our rover but we want to setup a base station with Raspberry Pi and that's why we want RTKstr2str to function.
It seems that strsvr is able to create own mountpoint but the str2str somehow can't. 
In this code
_$ str2str -in serial://ttyACM0#rtcm3 -out ntrip://Dude:BETATEST@rtk2go.com:2101/Dude_
If we replace the mountpoint dude with any of the existing mountpoint then it doesn't show any error. It doesn't overwrite the data though. but this can't be the solution!
Please suggest us how we can proceed.

**Comment by incoherent1** [comment]
jeetb007,

With a similar setup here (ublox M8T), 
str2str -out ntrip://... gets the error you see (no mountpoint), but
str2str -out ntrips://... with the added "s" for server seems to work.

The output from str2str -h  shows a couple other options as well.

**Comment by marcoseba** [comment]
hi jeetboo7,
 I would like to do your own project, setup a base station with Raspberry Pi and push-in data to rtk2go.com using rtklib. Did you manage to do this?

I have read that there are another problem with rtklib: 
"RTKLIB has an issue where it will connect to the Caster every X seconds (typical ten) for day on end even when there is no GNSS data present to send"

**Comment by jeetb007** [comment]
@marcoseba- yes it worked with Rtklib. I tried it with Windows computer not with a Pi though.

**Comment by smartcode63** [comment]
You can try [http://rtkdata.online](url) NTRIP caster
