### ISSUE TITLE
outlier rejected and no double-diferenced residual when enter base station position

### ISSUE THREAD

**Issue by Aryaelektro** [tomojitakasu/RTKLIB#446]
I get outlier rejected & no double-differenced residual when I enter base station position value. Previously I get stable FIX result with my setup (use ublox 2x M8N and average single position in base station position). Why this error occur? here I attach the result screenshot and .conf file that I use
[error result.zip](https://github.com/tomojitakasu/RTKLIB/files/2722189/error.result.zip)

**Comment by ralphtee** [comment]
I saw this line
`# RTKNAVI options (2018/12/13 15:26:57, v.2.4.3 demo5 b29b)`
in your file M8N_1hz.conf.

If you are using rtklibexplorer's forked project/binaries, you may wish to redirect your question to his github site. (https://github.com/rtklibexplorer/RTKLIB)

**Comment by Aryaelektro** [comment]
ok, I have fix it. this error appear because of my base station value is wrong.

**Comment by thomashamain** [comment]
@Aryaelektro do you remmeber what change did you make?
