### ISSUE TITLE
What does Q=5 mean for kinematic positioning

### ISSUE THREAD

**Issue by zain-farooq** [tomojitakasu/RTKLIB#453]
Hi!
I am running a single frequency kinematic solution and I get Q=5 for 100% of epochs. From the POS file, I understand that Q=5 means: single but I don’t understand what is single. If it is single-point-positioning then, as per my understanding, we should get the base position but we do get a moving case.
I am concerned because all the RTK data I have collected myself gives either Q=0 or Q=5 unfortunately.
Could you please shed some light on it.

**Comment by mdeago** [comment]
According to the user manual, Q5 means single point positioning or SBAS DGPS.
Did you changed the positioning mode as "Kinematic" or "DGPS / DGNSS" (in "Options > Setting1" menu)?
Did you use a base station?

**Comment by zain-farooq** [comment]
I used Kinematic positioning (as well as base station data). This is what concerns me, that whether it means that base station data is ignored. If yes, what would be the reason? I can also share the files if required.

**Comment by tomojitakasu** [comment]
To investigate the reason why you can not get FIX (Q=1) or FLOAT (Q=2) solutions, please enable DEBUG TRACE (set "Output Debug Trace" to Level 2, 3, or 4) and see the warnings or errors in the TRACE file.

**Comment by zain-farooq** [comment]
Thank you for your reply. I have done the following
1) changed kinematic mode to single mode in Options 1 (and it confirms my fears that base station data is ignored since I get same pos file in both modes).
2) Changed Trace to Level 3 but unfortunately I cannot understand the problem. (I can only understand that there are errors in the epoch 06:58:49.00: no double-differenced residual).
Is there some guideline available as to how to read the trace files. I know you are busy, but I am attaching the trace file just incase you want to see it.
[rover-trace.txt](https://github.com/tomojitakasu/RTKLIB/files/2991226/rover-trace.txt)

**Comment by YangY-Yang** [comment]
@zain-farooq I read the txt file, it seems that the residuals are too large and all ejected, then there is no double differential result, may be check the the max age for difference setting?

**Comment by zain-farooq** [comment]
Thank you. I resolved the issue. Actually, I was not taking base-station position. It works after doing either of the following changes
i) read rinex header for base
ii) manually entering base coordinates.
