### ISSUE TITLE
High elevation satellite residuals are zero

### ISSUE THREAD

**Issue by kriete** [tomojitakasu/RTKLIB#457]
Hello,

I stumbled upon this when I tried to analyze the logged residuals from the .pos.stat files of post-processed RNX2RTKP (or rtkpost).
High elevation satellite residuals (C and L) were zero. I conducted some tests with different datasets (zero-and short baselines) and the high-elevation residuals were always zero. In one case C2 and L2 residuals even went to zero from an elevation of 70 degree onwards. I did the same test with an older version (legacy code from rtklib.com) and it did not give these artifacts (even though the residuals itself are slightly different).

As an example, I conducted a simple experiment on a zero baseline. I processed the data with three different, freshly compiled, RTKLIB versions and the same configurations in RNX2RTKP
```
./rnx2rtkp -o dlf50330.pos -p 2 -m 5 -i -v 3.0 -y 2 -a dlf50330.19o dlf10330.19o brdc0330.19n
```
Breaking down the command:

- execute rnx2rtkp using the following arguments:
- output file to dlf50330.pos
- kinematic mode
- elevation cutoff 5 degree
- instantenous ambiguity resolution
- ambiguity threshold ratio of 3.0
- output residuals
- output ENU baseline
- rover dlf50330.19o
- base dlf10330.19o
- navigation file brdc0330.19n

The raw data is attached to this message.

Tested RTKLIB versions:

1) RTKLIB 2.4.2 latest master (p13) from github

2) RTKLIB 2.4.3 latest branch (b31) from github

3) "legacy" RTKLIB 2.4.2 from rtklib.com (2013/04/29)

I also attached the output (residuals+pos) files.

The binned residuals (black dots), mean residuals (black line) and their standard deviation (green line) plotted over 0.5 degree width on C1 using RTKLIB 2.4.3:
![image](https://user-images.githubusercontent.com/15364653/54073977-83c41b00-428d-11e9-8e86-ee8eaef7ad00.png)

and compared to the 'legacy' RTKLIB 2.4.2 (from rtklib.com)
![image](https://user-images.githubusercontent.com/15364653/54073998-ca197a00-428d-11e9-94f2-bf4b89c6d2fd.png)

L1 on RTKLIB 2.4.3 (github version)
![image](https://user-images.githubusercontent.com/15364653/54073989-b3732300-428d-11e9-8423-a90bda38ab7b.png)

L1 from 'legacy' RTKLIB 2.4.2
![image](https://user-images.githubusercontent.com/15364653/54074004-d3a2e200-428d-11e9-8913-c4db173b2638.png)

As one can see from the legacy solution, there are datapoints above 85 degree. Also, some datapoints seem to be missing, which are in fact zeros in the case of the github versions. The residuals for these zero cases (high elevation satellites) are flagged as 'valid' and 'fixed' and also contain SNR:
![image](https://user-images.githubusercontent.com/15364653/54074011-e4ebee80-428d-11e9-839b-176efaf64cde.png)

But residuals (L and C) are zero for high elevation satellites in both github versions (2.4.2 and 2.4.3). As mentioned before, the plots shown are actually from a zero-baseline experiment. The same applies to short baselines that I tested and in one extreme case also L2 and C2 from >70 degree went to zero.

I only GPS-only and used 'valid' and fixed flagged residuals. So RTKLIB gives a 'valid' flagged residual ($SAT) in the .pos.stat file where residuals drop suddenly to zero for high elevation angles.

I can see the point that the precision of the residual outputs in this case is not enough for caching the L phase residuals (0.1mm is lowest resolution). However, I manually changed the precision in the rtkpost.c for the $SAT residual output and recompiled, but the result is the same. Also, the C-residuals should be there at least (since they are way less precise than L-residuals).

Since I am working in a Linux environment, I tried the same on Windows as well (pre-compiled versions) and the results were the same.

Does anybody has an idea what happened here? Any thoughts are very welcome!
Thanks!

PS:
The files (input and output):
[to_github_rtklib.zip](https://github.com/tomojitakasu/RTKLIB/files/2948588/to_github_rtklib.zip)

**Comment by tomojitakasu** [comment]
In base-line modes (DGPS, Kinematic, Static or Moving-base), the residuals mean DD (double-difference) ones from a reference satellite. In RTKLIB, the reference satellite of DD is always selected with the highest elevation angle (and with valid observation data). So the residuals for the reference satellite indicates zero for both codes and phases. Notes that the behavior is a little different in former versions.

**Comment by kriete** [comment]
Dear @tomojitakasu , thanks a lot for the answer!
 
That explains the zero residuals and makes completely sense. So, we may assume that, in the former versions, the residuals are single difference residuals.
 
For us it would be really interesting to get the old behaviour back. Do you think this is somehow possible, maybe as an option?
 
If not, which we can understand very well, we can also think of another solution. One which we can do ourselves and requires no changes in RTKLIB. This is to take the DD residuals from RTKLIB and shift them by a (weighted) mean value for each epoch (and signal). This approach is similar to estimating the receiver clock correction from DDs. For the best result we should use the same weighting scheme as in RTKLIB. Do you think this is a good approach, and if so, can you tell us which weighting scheme is used by RTKLIB?
 
Thank you and best regards!

**Comment by tomojitakasu** [comment]
Strictly, until the version 2.4.2_p10, the phase and code residuals were referenced to the average of DD residuals in the same system and same signal. In 2.4.2_p11, I changed them to be referenced to just the reference satellite because the old codes were a little confusing to analyze various errors.

The old codes still remain as commented out by "#if 0 ... #endif" at rtklib/src/rtkpos.c L.1168-1185 (2.4.2_p13). So  if you dislike the current behavior, please restore these old codes and rebuild APs.

**Comment by kriete** [comment]
Dear tomojitakasu,
Sorry for the late reply and thank you very much for the explanation and instructions. I rebuilt the APs and it seems to work well! I only had to define one variable that was not used anymore.
Best wishes!
