### ISSUE TITLE
Need Zero-Padding PRNs in RNX files?

### ISSUE THREAD

**Issue by rharder** [tomojitakasu/RTKLIB#468]
Thanks so much for your awesome work on RTKLib!  I use the convbin tool a lot to process RTCM3 data from navigation satellites retrieved via ntrip casters and then generate RINEX files.

I'm not sure if this problem needs to be fixed on our end or RTKLib, but the PRN codes for single digit satellites, like G01, are output in the RINEX file without a zero-padding: G 1.  Some of our tools die on that.  For now I just go through and insert zeroes as needed, but are the PRNs supposed to be zero-padded?  Looks like that part of the code might be lines 178-184 in rinex.c.

Thanks for your time.

-Rob

**Comment by tomojitakasu** [comment]
The "G 1" is compliant to the RINEX. Some other RINEX converters output no-zero-padded satellite number.  RTKLIB accepts both. So your tools also had better to accept both.

**Comment by rharder** [comment]
Thanks!  That's how we'll take care of it then.
