### ISSUE TITLE
RTKConv and convbin do not appear to convert SBAS ephemerous data to RINEX file

### ISSUE THREAD

**Issue by rharder** [tomojitakasu/RTKLIB#469]
Again, thanks for all your work on RTKLib!

I use convbin to convert RTCM3 ephemerous data that I get from ntrip casters and generate RINEX files for further processing.

It appears that when SBAS data comes through, convbin (and RTKConv) just ignore it.  I don't have any other way to inspect those RTCM3 messages, so I don't know if it's being ignored due to a bug or because there's something wrong with the messages.

For example, here's the command I might give to process a file:

    convbin rtcm3_sbas.rtcm3 -r rtcm3 -v 3.0.3 -n out.rnx 

The rtcm3_misc.rtcm3 file (attached) outputs a variety of data, but nothing comes out of the rtcm3_sbas.rtcm3 file.  (These files came from chunks delivered by ntrip caster http://mgex.igs-ip.net).

Would appreciate it if you could take a look.

-Rob

[rtcm3_misc.rtcm3.gz](https://github.com/tomojitakasu/RTKLIB/files/3183307/rtcm3_misc.rtcm3.gz)
[rtcm3_sbas.rtcm3.gz](https://github.com/tomojitakasu/RTKLIB/files/3183308/rtcm3_sbas.rtcm3.gz)

**Comment by tomojitakasu** [comment]
RTCM has not yet defined the message for SBAS ephemeris even in the latest version 3.3.

**Comment by rharder** [comment]
Oh!  Huh, now I'm really curious what _is_ getting sent by those ntrip casters!  OK, thanks.

**Comment by DavidKelleySCSC** [comment]
After looking at the stream overnight, just one message observed.  As tomojitakasu notes, RTCM SC104 has yet to define an SBAS ephemeris, but this message number is where it would be presumed to go.

> [RTCM3EPH-MGEX-SBAS]:   MountPt RTCM3EPH-MGEX-SBAS [R010], 1 RTCM3 messages decoded, of 52,920 so far.
>    RTCM3 Type 1043 (035 bytes), the 52,920th message of this type found so far.
