### ISSUE TITLE
age of differential error

### ISSUE THREAD

**Issue by bhushan-123** [tomojitakasu/RTKLIB#473]
Hi everybody
I am trying to implement the RTK technique for automatic navigation system . I am using two Beagle-bone black  and the LoRa sx1278 radio module for the communication.
we received  the data from Base Station and send it to Rover over LoRa [sx1278 ]  . we received correct RTCM3 data on the  Rover side and give them as  input to the RTKRCV .

I am getting the following error:
age of differential error (age=30239998.0)
 age of differential error (age=30240002.0)
age of differential error (age=30240004.0)

**can anybody help me out above problem**

**Comment by tomojitakasu** [comment]
RTCM messages usually does not contain week or day infomation. RTKLIB uses the system clock to resolve such week of day ambiguities. So, if the system clock is wrong, the correction time becomes also wrong.
Please adjust the system clock properly anyway, like using NTP.

**Comment by bhushan-123** [comment]
thanks
