### ISSUE TITLE
satazel is buggy

### ISSUE THREAD

**Issue by shiluotang** [tomojitakasu/RTKLIB#483]
![image](https://user-images.githubusercontent.com/3193750/63679509-0896f700-c824-11e9-9033-8c6559e9ad39.png)

As the image describes, if ECEF-z is no larger than RE_WGS84, then the yield elevation will be 90 degrees. This is definitely not right!

**Comment by tomojitakasu** [comment]
See the header comments of the API.
The pos[2] does not show ECEF-Z but ellipsoidal height.

**Comment by YangY-Yang** [comment]
I think it is a minus RE_WG84, if not larger than it, then will set the elevation to 90. Pretty fair

**Comment by yydgis** [comment]
You did not fully understand the principle of the design logic. Based on my
understanding, in this case, there is no approximate coordinates of the
station, then all the satellite elevations are PI/2.0, then it is equally
weight for all satellites, this is only used in the initial case. Yudan

**Comment by shiluotang** [comment]
> See the header comments of the API.
> The pos[2] does not show ECEF-Z but ellipsoidal height.

Thanks for you suggestion! It's my fault! I was misled by the method name ecef2enu which made me took pos parameter as ECEF coordinate  is actually BLH thing.

By the way, the name "ecef2enu" is really easy to confuse rookies.
