### ISSUE TITLE
Rover Antenna delta offset not used

### ISSUE THREAD

**Issue by Stefal** [tomojitakasu/RTKLIB#486]
Hi!
With RTKPost 2.4.3 b33

I'd like to use a 1.695m height delta on the rover antenna, but it doesn't work correctly:

If I check "Antenna type", with no value in the drop down menu, and put my delta value, the Rtkpost output is correct, but if I save and reload the conf file, the delta value is disabled.

If I check "Antenna type", with * value as antenna type and put my delta value, the Rtkpost output doesn't use the delta. But the settings are correctly saved and loaded.

**Comment by tomojitakasu** [comment]
If checking "Antenna type" and selecting "*" (auto) for the antenna type, "Delta-E/N/U" values are not used. Antenna delta values are automatically obtained from RINEX header "ANTENNA: DELTA H/E/N" record for post-processing or RTCM station info messages for real-time. In the next release, "Delta-E/N/U" fields will be disabled in these cases.

**Comment by tomojitakasu** [comment]
It is fixed in 2.4.3 b34.

**Comment by Stefal** [comment]
Thank you!
