### ISSUE TITLE
Rtklib + F9P + ntrip snip caster

### ISSUE THREAD

**Issue by richardklasens** [tomojitakasu/RTKLIB#490]
Hi folks.

I’m trying to archive this:

Ardusimple Rtk2b connected to usb on My Windows pc, sending data to str2str.
I’ve selected 115200 baud, and in stream converter rtcm3 -> rtcm3.
I select ntrip server as an output and I want to send MT 1004,1006,1007,1012,1019 and 1020.
When click start it starts but the outgoing bytes are much smaller then ingoing bytes. In Ucenter i only send out RTCM3.x data.

In snip caster i created an Push in stream and that works, all messages are being parsed by snip, but there are no sats available in MT1004 or 1012. Even when trying to set it to MSM 1074/1077 and 1084/1087. 

What am i doing wrong?
1006 works good, in snip caster i can see the base station location data.

**Comment by DavidKelleySCSC** [comment]
Well if any RTCM message has reached the SNIP NTRIP Caster and got decoded, that absolves the normal serial port baud rate garbled message parts.  And the NTRIP protocol parts.  Congrats there.  Is this setup indoors?

> no sats available in MT1004 or 1012

This sounds like the SNIP RTCM viewer messages displayed are "empty" which can occur if you are indoors and therefore not decoding the GNSS signals.  You are getting just an empty frame, which str2str sends at the rate you requested.  [Note to gourp we should patch that out] It would also explain very small message sizes.   Run one of the other RTKLIB tools, display the monitoring abilities, and confirm you have observational data present. 

> When click start it starts but the outgoing bytes are much smaller then ingoing bytes

That is probably fine in general, as 1004 and 1012 are only a few hundred bytes messages each (but perhaps you only see <20 or so from your description above).  FYI also, you may not need 1019 and 1020 (there are orbital messages) if your solution or rover gets them by another means.  They are typically not sent in RTCM corrections.

**Comment by richardklasens** [comment]
The antenna is on the roof. If i use connect snip caster directly to My F9P it works good (but only have mt 1005,1074,1084,1094,1124,1230, i also need 1006 and 1007 or 1008. 

The F9P is set to TimeMode3 with a fixed location. Also having 27 sats observed inside ucenter

**Comment by richardklasens** [comment]
F9P doesnt support these extra MT’s directly from the board itself

**Comment by DavidKelleySCSC** [comment]
What does the control line under Conversion options / Message type look like?  It is in the form of: 1004(1), 1006(10), 1012(1) or something similar?  [The item in (-) is how often the send that message]
> F9P doesn't support these extra MT’s directly

Not following this, can you explain further?
FYI, MT1006 just has an ant offset height which MT1005 does not, if you got your final ECEF location with OPUS or some similar tool then any height and phase center offset is probably baked in already.

**Comment by richardklasens** [comment]
Yes it’s Like your line.. 1004(1),1006(10),1008(10), etc etc.

You can create rtcm directly from the f9p board, but you can only select rtcm 3.3 with MT 1005, 1074, 1077, 1084, 1087, 1097, 1124, 1127 and 1230. I can take this as a serial stream directly into snip caster and pushed out to rtk2go.com. 
For me i want legacy versions and My neighbours gps system (agricultural) needs 1006 and 1007/1008 to work

**Comment by DavidKelleySCSC** [comment]
Can you PM me with what the mountPt name you are using on RTK2go.com is.  I can then take a closer look at the content and try to get a copy of str2str working.  Aside, a pending SNIP feature is legacy message from MSM for this sort of need.  Aside, I find it odd that they would send 1074/1077 or 1084/1087 as a preset mix of messages.  To my limited awareness, any device that can do MSM would be able to do both of these.  Any idea the design intent for that?

**Comment by richardklasens** [comment]
How can i write a PM?

**Comment by DavidKelleySCSC** [comment]
I was able to find your email on the SNIP registration db (I work there), will use it in a moment,  Sorry but am multi tasking (poorly) at the moment with remote machines and a dial in RTCM meeting.  Please stand by.

**Comment by richardklasens** [comment]
When using Beta version 2.4.3 B33 everything works fine for me.
