### ISSUE TITLE
The elements in D matrix after lambda reduction is not in descending order

### ISSUE THREAD

**Issue by achenjw** [tomojitakasu/RTKLIB#500]
The elements in D matrix after lambda reduction is not in descending order, is am I wrong or it originally is ?

**Comment by tomojitakasu** [comment]
In my understanding, the LAMBDA reduction is based on LLL, which is one of the major lattice basis reduction algorithms:

https://en.wikipedia.org/wiki/Lenstra%E2%80%93Lenstra%E2%80%93Lov%C3%A1sz_lattice_basis_reduction_algorithm

The LLL does not ensure the condition:  d1 >= d2 >= d3 >= ... >= dn. The detailed condition by the LAMBDA reduction, refer equation (13) of the following paper :

X. -W. Chang et al., MLAMBDA: A modified LAMBDA method for integer least-squares estimation, Journal of Geodesy, 2005

**Comment by achenjw** [comment]
Thanks
