### ISSUE TITLE
Rtklib appears to use 16 leap seconds between GPST and UTC for 2019

### ISSUE THREAD

**Issue by jtec** [tomojitakasu/RTKLIB#501]
Hi, 

steps to reproduce:
- rtkpost 2.4.2
- run rtklibpost in Kinematic mode with ECEF output and GPST timestamp with observations from 2019
- run rtklibpost on the same input data with output time stamp set to UTC

In the output .pos logs I find that the first position solution record of each file differ by 16 seconds:

%  UTC                   latitude(deg) longitude(deg)  height(m)   Q  ns   sdn(m)   sde(m)   sdu(m)  sdne(m)  sdeu(m)  sdun(m) age(s)  ratio
2019/10/11 11:16:50.000   48.748075732    2.102047402   205.8760   2   9   0.3702   0.3061   0.6852   0.1856   0.1226   0.2725   0.00    1.2

versus

%  GPST                  latitude(deg) longitude(deg)  height(m)   Q  ns   sdn(m)   sde(m)   sdu(m)  sdne(m)  sdeu(m)  sdun(m) age(s)  ratio
2019/10/11 11:17:06.000   48.748075732    2.102047402   205.8760   2   9   0.3702   0.3061   0.6852   0.1856   0.1226   0.2725   0.00    1.2

 In 2019, GPS time and UTC differ by 18 seconds (see http://www.leapsecond.com/java/gpsclock.htm). I checked the unit tests in RTKLIB/test/utest/t_time.c  and find the following test:

Line 171    double ep6[]={2038, 1, 1, 0, 0, 0.000000};
Line 186 t=gpst2utc(epoch2time(ep6)); time2epoch(t,ep);
        assert(ep[0]==2037&&ep[1]==12&&ep[2]==31&&ep[3]==23&&ep[4]==59&&ep[5]==44.0);
which corresponds to 16 leap seconds for 2038 as well.

Is it possible that the Rtklib leap seconds need to be updated?

cheers, 
Jan

**Comment by tomojitakasu** [comment]
See support info no. 135. Use 2.4.2 p11 or later.

http://www.rtklib.com/rtklib_support.htm

**Comment by jtec** [comment]
Thanks!
