### ISSUE TITLE
No floating nor fix, only single as solution in RTKLIB

### ISSUE THREAD

**Issue by akisoy** [tomojitakasu/RTKLIB#502]
Hello,

I am currently working with the M8P modules from ublox and the RTKLIB.
I set up the two M8P as Transmitter and Receiver respectively like the quick-start guide advised + activated the raw messages RAWX and SFRBX. But I am only getting SINGLE as Solution in RTKLIB. My RTKLIB settings are the following:
Options: standard, except checking all satellites
Input:
Rover: Type: Serial, Format: u-blox, cmd: none, Opt: none
Base Station: Type: Serial, Format: u-blox, cmd: none, Opt: none

Hope that anyone can help me!

**Comment by improve100** [comment]
how do you fix the problem?
