### ISSUE TITLE
*.ubx files cannot be converted 

### ISSUE THREAD

**Issue by Deejuha** [tomojitakasu/RTKLIB#506]
Hello, 
*.ubx files from u-center cannot be converted.

It seems that files are just not written to disc, and it's known problem but on other version of rtklib.
I was using version from b33 commit a558afc from repo with binaries.

![image](https://user-images.githubusercontent.com/31712401/68999407-fc20b880-08bf-11ea-9a6b-9630fd2dcfdf.png)

**Comment by ghost** [comment]
I had the same problem but you have to make sure that you have configured the messages like RAWX

**Comment by Deejuha** [comment]
issue closed without resolution
