### ISSUE TITLE
Insufficient memory with importing data

### ISSUE THREAD

**Issue by alehanderoo** [tomojitakasu/RTKLIB#509]
With importing 1 hour of 20Hz GNSS data RTKlib is giving an insufficient memory data error. 

Has the max data size been fixed for a reason?
Is it possible to enlarge this max size?

**Comment by easyrtk** [comment]
The logic of rtklib post-process is to load all the raw measurements into
the memory, then process the data forward and backward, the code is able to
allocate the memory if needed depending on the limitation of your computer.
If you can not process the data, just cut the file and reprocess it.

**Comment by tomojitakasu** [comment]
The default RTKPOST is built on 32 bit environment, which has the memory limitation of 1.5 GB for a process. Try to use RTKPOST_WIN64 (rtklib_bin/bin/rtkpost_win64.exe) on Windows 64 bit instead.

**Comment by alehanderoo** [comment]
Thanks Tomojitakasu!
This did the trick.
