### ISSUE TITLE
RTKLIB can't decode 3.0 SP3 and CLK files

### ISSUE THREAD

**Issue by marcoamm** [tomojitakasu/RTKLIB#520]
When trying to do a multi-GNSS PPP using MGEX orbits and clocks from here:

ftp://cddis.gsfc.nasa.gov/pub/gps/products/mgex/

RTKLIB doesn't provide a solution, and in the trace file raises a "no precise eph" error at every epoch, even though in preceph.c, there is support for multi-GNSS.

**Comment by tomojitakasu** [comment]
The current version supports only SP3-c.
So somehow you have to convert SP3-d to SP3-c or add codes for SP3-d by yourself.

**Comment by marcoamm** [comment]
Thank you very much! I think it's an important feature since all the MGEX products are now in SP3-d. I'll give it a shot and send a pull request when I finish it.
