### ISSUE TITLE
MP LC reference?

### ISSUE THREAD

**Issue by YangRiverJiang** [tomojitakasu/RTKLIB#524]
Hello Sir,

I would like to know where can I find further materials regarding the MP calculation in the RTKPLOT module? Specifically the *UpdateMp* function of *plotdata.cpp* file in *\app\rtkplot\* directory.

Thanks so much for helping me,

River

**Comment by tomojitakasu** [comment]
See eq. 6.4 in:
P. J. G. Teunissen and A. Kleusberg (eds.), GPS for geodesy (2nd edition), 1998, Springer
