### ISSUE TITLE
What is the rtknavi_qt default config .ini file path?

### ISSUE THREAD

**Issue by xmfcx** [tomojitakasu/RTKLIB#542]
Where is the default .ini configuration path for rtklib for Ubuntu 18.04?

I can't find an example .ini file to modify to run it with it.

Also, is it possible export the configuration to an .ini file for rtknavi_qt?

Using RTKNAVI-QT ver.2.4.3 b8

**Comment by reza-ebrahimi** [comment]
Use `Exit` button when closing the `rtknavi_qt` main window. It will save all configurations you made into `rtknavi_qt.ini` file.

**Comment by xmfcx** [comment]
Thank you!
I ran `locate rtknavi_qt` and it returned: `/usr/bin/rtknavi_qt`
Then when I ran `sudo rtknavi_qt`, set my settings and quit with the GUI Exit button, `/usr/bin/rtknavi_qt.ini` was saved.
