### ISSUE TITLE
Empty solution file RTKPOST

### ISSUE THREAD

**Issue by lbenvenuto91** [tomojitakasu/RTKLIB#551]
Hi,

I'm trying to using rtkpost v.2.4.3 b33 in order to elaborate a single baseline.
As output I just want the rover coordinates for the whole period (and not rover's coordinates for each epocs) so I set the option 'Solution for static mode' to single and not to all.
The processing seems ok but at the end I find the solution file without the coordinates.
I attach both the conf and the solution file to a better understanding.

Note that using the rtkpost v.2.4.2 with the same options this problem doesn't occur

[
[test-base-rover-LIGE-conf.txt](https://github.com/tomojitakasu/RTKLIB/files/5510327/test-base-rover-LIGE-conf.txt)
](url)

[LIGE00ITA_R_20203130000_01D_30S_MO-solution.txt](https://github.com/tomojitakasu/RTKLIB/files/5510332/LIGE00ITA_R_20203130000_01D_30S_MO-solution.txt)

**Comment by GHolk** [comment]
I faced the same problem before, but you should ask the problem about b33 version in [rtkexplorer's github repository](https://github.com/tomojitakasu/RTKLIB/issues).

**Comment by rtklibexplorer** [comment]
Yes, I suspect this is the same I issue I ran into recently.

When "Solution for Static Mode" is set to "Single", RTKLIB tries to save and report the last best solution point in the data set.  Unfortunately it prioritizes Q=0 over valid solution points so if it calculates a single Q=0 (no solution) point it never replaces it with a valid solution.  This can be modified by changing the priority of the Q=0 solution.  In postpos.c, change:

    int i,nobs,n,solstatic,num=0,pri[]={0,1,2,3,4,5,1,6}

to:

    int i,nobs,n,solstatic,num=0,pri[]={6,1,2,3,4,5,1,6}

As Gholk mentioned, I recently checked this change into the rtklibexplorer/demo5 repository as part of a larger set of changes but it is not yet in the latest version of the demo5 executables.

**Comment by lbenvenuto91** [comment]
Thank you very much for the answer!
I don't know if this is the right place to ask, but how can I recompile RTKPOST after I've modified this line?

**Comment by rtklibexplorer** [comment]
You will need the Embarcadero C++ Builder.  You can download the community edition for free from the Embarcadero website.  Open the rtkpost.cbproj or rtkpost_win64.proj project file (in the rtklib/app folders) with the C++ builder and then build.

**Comment by lbenvenuto91** [comment]
Thank you very much @rtklibexplorer it worked!
