### ISSUE TITLE
Issue with Delta Clock C2 value

### ISSUE THREAD

**Issue by arty86** [tomojitakasu/RTKLIB#560]
Hello!
It seen there is a bug with Delta Clock C2 in rtcm3e.c
In accordance with RTCM description DF378 has resolution 0.00002 mm/s2 so the strings should be like:

`dclk[2]=ROUND(rtcm->ssr[j].dclk[2]/1E-8); - >    dclk[2]=ROUND(rtcm->ssr[j].dclk[2]/2E-8);`
`dclk [2]=ROUND(rtcm->ssr[j].dclk [2]/1E-8); ->    dclk [2]=ROUND(rtcm->ssr[j].dclk [2]/2E-8);`

**Comment by tomojitakasu** [comment]
Thanks. It is fixed in 2.4.3 b34.
