### ISSUE TITLE
2.4.3 b34 build error with Embarcadero - missing OpenBLAS

### ISSUE THREAD

**Issue by vbnhu** [tomojitakasu/RTKLIB#561]
I just tried to compile RTKPOST with C++ Builer 10.3 and got the following error:

bcc64 command line for "..\appcmn\freqdlg.cpp"
  c:\program files (x86)\embarcadero\studio\20.0\bin\bcc64.exe -cc1 -D NDEBUG -D WIN32 -D TRACE -D ENAGLO -D ENAGAL -D ENAQZS -D ENACMP -D ENAIRN -D 
  NFREQ=5 -D LAPACK -D WIN32 -D TRACE -D ENAGLO -D ENAGAL -D ENAQZS -D ENACMP -D ENAIRN -D NFREQ=5 -D LAPACK -output-dir release_build -I 
  C:\Temp\RTKLIB\RTKLIB\app\winapp\rtkpost -I ..\..\..\src -I ..\appcmn -I ..\..\src -isystem "c:\program files (x86)\embarcadero\studio\20.0\include" 
  -isystem "c:\program files (x86)\embarcadero\studio\20.0\include\dinkumware64" -isystem "c:\program files 
  (x86)\embarcadero\studio\20.0\include\windows\crtl" -isystem "c:\program files (x86)\embarcadero\studio\20.0\include\windows\sdk" -isystem 
  "c:\program files (x86)\embarcadero\studio\20.0\include\windows\rtl" -isystem "c:\program files (x86)\embarcadero\studio\20.0\include\windows\vcl" 
  -isystem "c:\program files (x86)\embarcadero\studio\20.0\include\windows\fmx" -isystem C:\Users\Public\Documents\Embarcadero\Studio\20.0\hpp\Win64 
  -isystem C:\Users\Public\Documents\Embarcadero\Studio\20.0\hpp\Win64 -fborland-extensions -nobuiltininc -nostdsysteminc -triple x86_64-pc-win32-elf 
  -emit-obj -fexceptions -fcxx-exceptions -fseh -munwind-tables -fno-spell-checking -fno-use-cxa-atexit -x c++ -std=c++17 -fmath-errno -tM -tW -o 
  release_build\freqdlg.o -dependency-file release_build\freqdlg.d -MT release_build\freqdlg.o -sys-header-deps ..\appcmn\freqdlg.cpp 
ilink64 command line
  c:\program files (x86)\embarcadero\studio\20.0\bin\ilink64.exe -G8 -Lrelease_build;"c:\program files (x86)\embarcadero\studio\20.0\lib\release";
  D:\share\RTKLIB\lib\openblas;"D:\share\RTKLIB\lib\OpenBLAS-v0.2.14-Win64-int32\lib";D:\share\RTKLIB\lib\omf;..\..\..\src;..\appcmn;..\..\src;
  D:\share\RTKLIB\lib\openblas;"D:\share\RTKLIB\lib\OpenBLAS-v0.2.14-Win64-int32\lib";D:\share\RTKLIB\lib\omf;..\..\..\src;..\appcmn;..\..\src;
  "c:\program files (x86)\embarcadero\studio\20.0\lib\win64\release";"c:\program files (x86)\embarcadero\studio\20.0\lib\win64\release\psdk";
  C:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp\Win64;C:\Users\Public\Documents\Embarcadero\Studio\20.0\DCP\Win64\Release;
  C:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp\Win64 -jrelease_build;"c:\program files (x86)\embarcadero\studio\20.0\lib\release";
  D:\share\RTKLIB\lib\openblas;"D:\share\RTKLIB\lib\OpenBLAS-v0.2.14-Win64-int32\lib";D:\share\RTKLIB\lib\omf;..\..\..\src;..\appcmn;..\..\src;
  D:\share\RTKLIB\lib\openblas;"D:\share\RTKLIB\lib\OpenBLAS-v0.2.14-Win64-int32\lib";D:\share\RTKLIB\lib\omf;..\..\..\src;..\appcmn;..\..\src;
  "c:\program files (x86)\embarcadero\studio\20.0\lib\win64\release";"c:\program files (x86)\embarcadero\studio\20.0\lib\win64\release\psdk";
  C:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp\Win64;C:\Users\Public\Documents\Embarcadero\Studio\20.0\DCP\Win64\Release;
  C:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp\Win64 -lrelease_build -v -Gn 
  -GA"C:\Users\balin\AppData\Local\Temp\vfsB6AB.tmp"="C:\Temp\RTKLIB\RTKLIB\app\winapp\rtkpost\postmain.dfm" -aa -V5.0 -Tpe c0w64 memmgr.a sysinit.o 
  release_build\aboutdlg.o release_build\confdlg.o release_build\freqdlg.o release_build\keydlg.o release_build\maskoptdlg.o release_build\refdlg.o 
  release_build\timedlg.o release_build\viewer.o release_build\vieweropt.o release_build\kmzconv.o release_build\postmain.o release_build\postopt.o 
  release_build\rtkpost.o release_build\convgpx.o release_build\convkml.o release_build\convrnx.o release_build\datum.o release_build\ephemeris.o 
  release_build\geoid.o release_build\ionex.o release_build\lambda.o release_build\options.o release_build\pntpos.o release_build\postpos.o 
  release_build\ppp.o release_build\ppp_ar.o release_build\preceph.o release_build\rinex.o release_build\rtcm.o release_build\rtcm2.o 
  release_build\rtcm3.o release_build\rtcm3e.o release_build\rtkcmn.o release_build\rtkpos.o release_build\sbas.o release_build\solution.o 
  release_build\tides.o , release_build\rtkpost.exe , release_build\rtkpost.map , rtl.a vcl.a vclx.a libopenblas.a import64.a cp64mt.a , , rtkpost.res 
  rtkpost.res 
[ilink64 Error] Fatal: Unable to open file 'LIBOPENBLAS.A'
Failed

**Comment by tomojitakasu** [comment]
My environment (C++ builder 10.3.3 community edition) does not have any error.
Try 10.3.3 or add path ...\RTKLIB\lib\openblas to library search paths in build options.

**Comment by vbnhu** [comment]
Thanks a lot for the fast response and also for the new features and improvements in RTKLIB!
I installed 10.3.3 and now libopenblas.a shows up in the Project and I receive error only at the end of compilation: 'libopenblas.dll not found...'. If I look into the release_build folder there is the rtkpost.exe file, so the error comes from the fact that C++ builder wants to open the app after it compiled. 
In the _BIN distribution I can find some standalone .dll-s in the project folder so I just copied them ('libopenblas.dll', 'libfortran-3.dll', 'libgcc_s_seh-1.dll','libquadmath-0.dll') to the release_build folder and after this I can start the program. 

Is it the intended way, or compilation should also include openblas?

**Comment by tomojitakasu** [comment]
Compilation itself does not need any DLLs but needs openblas.a, that is an import library for DLLs. Execution of AP (RTKPOST.exe in this case) needs DLLs including  libopenblas.dll, libquadmath-0.dll, libgfortran-3.dll and libgcc_s_seh-1.dll. So you have to place these DLLs in the same directory of the AP exe file (or search paths of DLLs). Otherwise, execution of the AP is failed. These DLLs are already installed in the directory RTKLIB_bin/bin for the repository RTKLIB_bin or RTKLIB/bin for the RTKLIB release package.

**Comment by vbnhu** [comment]
Thanks, I will use them as you described!
