### ISSUE TITLE
The file 2.4.3-b34.tar.gz contains an old release

### ISSUE THREAD

**Issue by Stefal** [tomojitakasu/RTKLIB#566]
I think it's the 2.4.2 source code, not the 2.4.3-b34. It's probably the same with the zip file.

part of convbin source code:
```
* version : $Revision: 1.1 $ $Date: 2008/07/17 22:13:04 $
* history : 2008/06/22 1.0 new
*           2009/06/17 1.1 support glonass
*           2009/12/19 1.2 fix bug on disable of glonass
*                          fix bug on inproper header for rtcm2 and rtcm3
*           2010/07/18 1.3 add option -v, -t, -h, -x
*           2011/01/15 1.4 add option -ro, -hc, -hm, -hn, -ht, -ho, -hr, -ha,
*                            -hp, -hd, -y, -c, -q 
*                          support gw10 and javad receiver, galileo, qzss
*                          support rinex file name convention
*           2012/10/22 1.5 add option -scan, -oi, -ot, -ol
*                          change default rinex version to 2.11
*                          fix bug on default output directory (/ -> .)
*                          support galileo nav (LNAV) output
*                          support compass
*           2012/11/19 1.6 fix bug on setting code mask in rinex options
*           2013/02/18 1.7 support binex
*           2013/05/19 1.8 support auto format for file path with wild-card
*           2014/02/08 1.9 add option -span -trace -mask
*           2014/08/26 1.10 add Trimble RT17 support
*-----------------------------------------------------------------------------*/
```

**Comment by tomojitakasu** [comment]
Thanks. I don't fully understand GitHub's Releases feature. I only uploaded ZIP file RTKLIB_2.4.3_b33.zip but the release automatically contains Source code (zip) and Source code (tar.gz) by checking out the base repository. How can I edit them ?

**Comment by Stefal** [comment]
Hi!
Yes, when you create a new release, Github always add the source code so you don't have to add it manually, but you have to choose the right branch:
![image](https://user-images.githubusercontent.com/8255984/103753657-99cad000-500b-11eb-8994-cf5dc50f7b01.png)

Then you can add some binary (windows, linux, ...). With this feature, you don't need to maintain the RTKLIB_Bin repo.

Now, if you want to fix the actual b34 release, you have to:
- Delete the b34 release. Go to your [release](https://github.com/tomojitakasu/RTKLIB/releases/tag/v2.4.3-b34), you should see the delete button, but perhaps you'll have to remove your zip file before. See https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository#deleting-a-release
- If you try to re-create the v2.4.3-b34 release right now, perhaps you will have a problem to select the correct git branch: the v2.4.3-b34 is already used. You need to delete this tag. You can't delete it from the github webpage, but you can do it with the git command line, see https://github.community/t/how-to-delete-release-completely/1466
- Now you can re-create your b34 release, including the windows binary zip file, the changelog in the release description and so on.

I'm not a git/github expert so perhaps there are better ways to do this.

**Comment by tomojitakasu** [comment]
Oh, thanks for your suggestion.

Replaced the release by the proper one.

**Comment by Stefal** [comment]
Thank you for the fix.
