### ISSUE TITLE
How to output a NMEA string by str2str, like a STRSVR via TCP port.

### ISSUE THREAD

**Issue by mikiofuku** [tomojitakasu/RTKLIB#573]
STRSVR can output a NMEA String same as a serial port.

- How to : Input -> Serial -> Opt -> "Output Received Stream to TCP Port:"

That's great.

Can **str2str** output a NMEA string?

I trid this, I could not got a NMEA string, they are seems RTCM binaries.
sudo ./str2str -in ntrip://user:pass@hostname:port -out serial://ttyACM0:115200 -b 1 -out tcpsrv://localhost:52001

Thank you.

**Comment by tomojitakasu** [comment]
Yes.

STRSVR or STR2STR only relay the input stream to output streams if setting it without conversion. So configure your NTRIP source to output NMEA.

**Comment by mikiofuku** [comment]
Dr. Takasu
Thank you for your quick reply.
I would like to pay tribute to your amazing effort for RTKLib.

Many ntrip caster outputs a RTCM format, not a NMEA.

>STRSVR can output a NMEA String same as a serial port.
>-  How to : Input -> Serial -> Opt -> "Output Received Stream to TCP Port:"

Does str2str have an same function?

I want to get of "Fixed NMEA GGA" strings by using F9P internal calc engine.
Already I got a "Fixed NMEA" by F9P, u-center and Ntrip caster. (F9P setup by u-center for RTK internal engine) 
but I should use a Raspbery pi4.

"Fixed NMEA" strings means
1. run str2str
2. str2str gets RTCM from Ntrip caster.
3. str2str write RTCM to the F9P via serial port.
4. str2str gets a NMEA strings from the F9P via serial port. the NMEA strings contains "Fixed NMEA GxGGA" if any condition is good.

Thank you.

**Comment by tomojitakasu** [comment]
I understand what you want.

STR2STR also implements "Output Received Stream to TCP Port" option like STRSVR 2.4.3 b34. However, it is not yet documented and tested.

Please add the option "#\<port\>" to the serial stream path as follows, where \<port\> is the TCP server port to output the return serial stream from receivers (NMEA in your F9P case).

-out serial://port[:brate[:bsize[:parity[:stopb[:fctr]]]]]#\<port\>

Note again it's unofficial and untested. If any trouble, let me know.

**Comment by mikiofuku** [comment]
Thank you for your quick reply.

I got a NMEA string as follows.

$ sudo ./str2str -in ntrip://username:password@hostname:port/mountpoint -out serial://ttyACM0:115200#52001 -b 1

How to get nmea string.
$ nc localhost 52001

I think I will make it in time for field test next week.
Thank you.
