### ISSUE TITLE
galileo ephemeris problem

### ISSUE THREAD

**Issue by zhengjialiang2** [tomojitakasu/RTKLIB#580]
Hello! I downloaded a rnx file from ftp://ftp.pecny.cz/LDC/orbits_brd/gop3/2021/ ,then I found that there are two different ephemeris of a single galileo satellite at the same time like below. Does anybody can tell me why?

E01 2021 02 05 00 00 00-1.039387774650e-03-8.029132914090e-12 0.000000000000e+00
     8.000000000000e+01 1.427812500000e+02 3.004410860060e-09-9.341216454590e-01
     6.711110472680e-06 2.636719727890e-04 6.077811121940e-06 5.440614204410e+03
     4.320000000000e+05 4.470348358150e-08 2.534694323870e+00-5.215406417850e-08
     9.793612342810e-01 2.190312500000e+02 1.716587152570e-01-5.722024059560e-09
     2.025084352890e-10 5.160000000000e+02 2.143000000000e+03 0.000000000000e+00
     3.120000000000e+00 0.000000000000e+00 2.328306436540e-10 2.328306436540e-10
     4.326640000000e+05
E01 2021 02 05 00 00 00-1.039387832861e-03-8.043343768804e-12 0.000000000000e+00
     8.000000000000e+01 1.427812500000e+02 3.004410860057e-09-9.341216454589e-01
     6.711110472679e-06 2.636719727889e-04 6.077811121941e-06 5.440614204407e+03
     4.320000000000e+05 4.470348358154e-08 2.534694323873e+00-5.215406417847e-08
     9.793612342808e-01 2.190312500000e+02 1.716587152574e-01-5.722024059555e-09
     2.025084352892e-10 2.580000000000e+02 2.143000000000e+03 0.000000000000e+00
     3.120000000000e+00 0.000000000000e+00 2.328306436539e-10 0.000000000000e+00
     4.327000000000e+05
E01 2021 02 05 00 10 00-1.039392605890e-03-8.043343768800e-12 0.000000000000e+00
     8.100000000000e+01 1.421250000000e+02 2.990124550690e-09-8.593817415680e-01
     6.686896085740e-06 2.639790764080e-04 5.980953574180e-06 5.440614841460e+03
     4.326000000000e+05 5.029141902920e-08 2.534690865530e+00-5.587935447690e-08
     9.793613761840e-01 2.215625000000e+02 1.713043321300e-01-5.717738166750e-09
     2.028655930230e-10 5.160000000000e+02 2.143000000000e+03 0.000000000000e+00
     3.120000000000e+00 0.000000000000e+00 2.328306436540e-10 2.328306436540e-10
     4.332640000000e+05
E01 2021 02 05 00 10 00-1.039392605890e-03-8.043343768804e-12 0.000000000000e+00
     8.100000000000e+01 1.421250000000e+02 2.990124550690e-09-8.593817415676e-01
     6.686896085739e-06 2.639790764078e-04 5.980953574181e-06 5.440614841461e+03
     4.326000000000e+05 5.029141902924e-08 2.534690865534e+00-5.587935447693e-08
     9.793613761838e-01 2.215625000000e+02 1.713043321302e-01-5.717738166745e-09
     2.028655930234e-10 2.580000000000e+02 2.143000000000e+03 0.000000000000e+00
     3.120000000000e+00 0.000000000000e+00 2.328306436539e-10 0.000000000000e+00
     4.333000000000e+05

**Comment by diddlum** [comment]
INAV (E1B/E5b) and FNAV (E5a) messages. Look at those 516 and 258 in broadcast orbit 5. You will also see you have two bgds at bo 6 in the first message and only one in the second. See Galileo navigation data in RINEX doc file of that RINEX version.

**Comment by tomojitakasu** [comment]
One is I/NAV and another is F/NAV.
You can identify whether I/NAV or F/NAV with the data sources filed (the 2nd field of the 6th line) in RINEX NAV.

**Comment by zhengjialiang2** [comment]
Thank you for your answers.
