### ISSUE TITLE
rnx2rtkp CLI -- velocity output is all zeros

### ISSUE THREAD

**Issue by stephenwinn16** [tomojitakasu/RTKLIB#581]
Hi all, 

I'm using the rtklib_2.4.3 branch and the CLI commands to run rnx2rtkp. I use the attached configuration (generated using the graphical interface) but the velocity solution in the output .rtk file is just columns of zeros (even though my rover is moving) despite the position solution being correct. Am I missing a flag or is this a bug? 

[config.txt](https://github.com/tomojitakasu/RTKLIB/files/6020370/config.txt)

**Comment by guhland** [comment]
I have the same problem. Hoping somebody could tell me what I am missing to get some velocity numbers...

**Comment by guhland** [comment]
> Hi all,
> 
> I'm using the rtklib_2.4.3 branch and the CLI commands to run rnx2rtkp. I use the attached configuration (generated using the graphical interface) but the velocity solution in the output .rtk file is just columns of zeros (even though my rover is moving) despite the position solution being correct. Am I missing a flag or is this a bug?
> 
> [config.txt](https://github.com/tomojitakasu/RTKLIB/files/6020370/config.txt)

Hey Stephen,

I believe I have solved this problem. If you are using the convbin command line tool to generate RINEX files, make sure you have the "-od" tag. This should add doppler-frequency to the observation types. I found that without this tag the rtk file generated using those RINEX files have a velocity of all zeros.

Hope this helps!

**Comment by stephenwinn16** [comment]
Hi guhland, 

That was the option I was missing! Adding the "-od" option when running convbin and then running rnx2rtkp ensures the output file contains the velocity values. 

Thanks!
