### ISSUE TITLE
Steps to Raw Measurement Data by M8N

### ISSUE THREAD

**Issue by shubham9436** [tomojitakasu/RTKLIB#611]
I am trying to get the Raw Measurement Data by M8N but not able to get it. The firmware version is 2.01. 
I followed this tutorial:
https://rtklibexplorer.wordpress.com/2016/02/03/collecting-raw-gps-data-with-rtklib/ .

I start the STRSVR program and enter the following command in input:
```
!UBX CFG-GNSS 0 32 32 1 0 10 32 0 1
!UBX CFG-GNSS 0 32 32 1 6 8 16 0 1
!UBX CFG-MSG 3 15 0 1 0 1 0 0
!UBX CFG-MSG 3 16 0 1 0 1 0 0
!UBX CFG-MSG 1 32 0 1 0 1 0 0 
```
This is the file (.ubx) I get after running the above mentioned command.
[gps.zip](https://github.com/tomojitakasu/RTKLIB/files/6472027/gps.zip)

But when I use rtkconv to get .nav and .obs file, it produces error E=7. The error maybe because of the absence of raw data.

Can someone please tell me the proper steps to get the raw data from M8N

**Comment by reid-p** [comment]
On 13/05/2021 19:00, Shubham Baranwal wrote:
> I am trying to get the Raw Measurement Data by M8N but not able to get it. The firmware version is 2.01.
> I followed this tutorial:
> https://rtklibexplorer.wordpress.com/2016/02/03/collecting-raw-gps-data-with-rtklib/ 
> 
> I start the STRSVR program and enter the following command in input:
> 
> |!UBX CFG-GNSS 0 32 32 1 0 10 32 0 1 !UBX CFG-GNSS 0 32 32 1 6 8 16 0 1 !UBX CFG-MSG 3 15 0 1 0 1 0 0 !UBX CFG-MSG 3 16 0 1 0 1 0 0 !UBX CFG-MSG 1 32 0 1 0 1 0 0 |
> 
> This is the file (.ubx) I get after running the above mentioned command.
> gps.zip <https://github.com/tomojitakasu/RTKLIB/files/6472027/gps.zip>
> 
> But when I use rtkconv to get .nav and .obs file, it produces error E=7. The error maybe because of the absence of raw data.
> 
> Can someone please tell me the proper steps to get the raw data from M8N

See the note at the top of the link:
https://rtklibexplorer.wordpress.com/2016/02/03/collecting-raw-gps-data-with-rtklib/

The TRK-MEAS and TRK-SFRBX messages on the most recent version of the M8N are now scrambled, making raw observations unavailable on this receiver. You will need 
to use either the u-blox M8T, M8P, or F9P receiver, and enable the RXM-RAWX and RXM-SFRBX messages.



-- 
Regards
Phil Reid

ElectroMagnetic Imaging Technology Pty Ltd
Development of Geophysical Instrumentation & Software
www.electromag.com.au

23 Junction Parade, Midland WA 6056, AUSTRALIA
Ph: +61 8 9250 8100
Fax: +61 8 9250 7100
Email: ***@***.***

**Comment by tomojitakasu** [comment]
For raw data in M8N F/W 2.01, refer the following material.

http://gpspp.sakura.ne.jp/paper2005/gpssymp_2014_ttaka.pdf

TRK-MEAS and TRK-SFRBX have been unformal and unsupported by u-blox. I found unexpected behavior in raw measurement. I recommend to use M8T instead.

**Comment by shubham9436** [comment]
> For raw data in M8N F/W 2.01, refer the following material.
> 
> http://gpspp.sakura.ne.jp/paper2005/gpssymp_2014_ttaka.pdf
> 
> TRK-MEAS and TRK-SFRBX have been unformal and unsupported by u-blox. I found unexpected behavior in raw measurement. I recommend to use M8T instead.

Thank you for the suggestion.
