### ISSUE TITLE
why does antenna delta have to be added twice?

### ISSUE THREAD

**Issue by 7upcyang** [tomojitakasu/RTKLIB#617]
When we used the coordinates of the header file as the reference station coordinates, the antenna delta was first added to the coordinates of the header file in the antpos function in postpos.c. 

![image](https://user-images.githubusercontent.com/63029228/124411954-17378900-dd80-11eb-9ed6-594f06d10ce0.png)

And then to the pcv in the antmodel function in rtkpos.c. Why does antenna delta have to be added twice?
![image](https://user-images.githubusercontent.com/63029228/124412016-2e767680-dd80-11eb-9ef7-7cc98677a9b7.png)

**Comment by uuiitwp** [comment]
I have tested the rtkpost and rnx2rtkp and I think it's a bug

**Comment by 7upcyang** [comment]
> the antpos function in postpos.c.
