### ISSUE TITLE
Position offset after exiting a bridge

### ISSUE THREAD

**Issue by nikhilbhatia123** [tomojitakasu/RTKLIB#627]
@tomojitakasu I've been using RTKPost 2.4.3 b34 (also tried 2.4.2) to post process the data: rover obs, base obs and base nav, and have been comparing the RTKLib solution with the known good solution. Before entering under a bridge, the fix/float sol is right on top of known good, but after after exiting the bridge the RTKlib solution (float or fix) has about 10m offset from the known good solution. This offset stays on for a long time during the drive.  This happens most of the time when exiting any bridge. 

Interestingly, the single solution shows better result in this situation, but the kinematic solution always has as offset. Could you let me know if this is a known issue? Does it have to do with the RTKPost configuration?  The rtkpost config file has been attached. 
[rtkpost.txt](https://github.com/tomojitakasu/RTKLIB/files/7297135/rtkpost.txt)
![offset](https://user-images.githubusercontent.com/92045293/136283484-3f509759-ad3e-4c73-8b5d-b8b4148f8e4b.JPG)

You response would be really appreciated.
Thanks,
Nikhil

**Comment by schumipush** [comment]
Hi, nikhilbhatia123, have you tried set the parameter "pos1-dynamics" as "on" ?
Have you tried set the parameter "pos1-frequency" as "2" ?
I'm not sure about your satellite system Settings. Would you like to attach your raw measurement data?

**Comment by nikhilbhatia123** [comment]
@schumipush thanks for your response.  I tried different settings without any luck. Setting pos1-dynamics actually crashes the RTKPost (with some error in Chinese that I can't understand!). The data only has L1 freq, so setting pos1-frequency to 2 doesn't help.
We want to use RTKLib as the real-time RTK engine, so we want to find out if it's the engine error or post-processing error that's introducing the offset after exiting under a bridge. I've attached rover observation data and base state observation and nav data that you can use with the RTKPost. Let me know if you need any other info.
Your help is really appreciated.
[data.zip](https://github.com/tomojitakasu/RTKLIB/files/7306153/data.zip)

**Comment by schumipush** [comment]
Hi, nikhilbhatia123. 
I have run a preliminary test with your data. I found that the solution would be slightly better if the parameter "pos2-aroutcnt" is set as "2". 
In addition, I am curious how you resolved the "known good solutoin"? Is another high quality receiver or commercial RTK software involved? Can you provide the "known good solution"? Thanks.
As I know, the TRIMBLE NETR9 is not a single frequency receiver. Are you working on low-cost single-frequency cases?
![image](https://user-images.githubusercontent.com/22997461/136511753-60122956-922f-4fc7-9f43-35fb5f579263.png)

**Comment by nikhilbhatia123** [comment]
Hello @schumipush 
The known good solution was taken using Novatel Waypoint Inertial Explorer. I've attached the kml file from the known good (sorry, I should have included that in the previous post) The rover is a regular ublox receiver.  The idea is to use RTKLib engine and get a good solution using rover observations and base station observation and eph. As you can compare the results, the position deviates every time we exit under the bridge. Wondering if this is a bug in the RTKLib. 
Thank you so much for your help so far.
[data.zip](https://github.com/tomojitakasu/RTKLIB/files/7309640/data.zip)

**Comment by nikhilbhatia123** [comment]
Hi @schumipush, the results do look much better with pos2-aroutcnt" is set as "2". What does this setting do? Does it mean this is a post-processing issue? How do we make sure in real-time the engine uses this setting?
Thank you so much.

**Comment by schumipush** [comment]
Hi, nikhilbhatia123

You  can refer to the manual of RTKLIB (p.39)
![image](https://user-images.githubusercontent.com/22997461/136577822-3573433c-2848-4bba-990f-228b22ab95cc.png)

Let me try to explain why it looks better. My understanding is that the parameter "pos2-aroutcnt" is used in the process of updating kalman filter state vector (the ambiguities parts). When measurements of a satellite encounters an outage of epochs more than the value of  the "pos2-aroutcnt", its ambiguity estimate would be reset, and this satellite would also be considered unlocked in the next few epochs (refer to lines. 732-750 of rtkpos.c file, the variable "rtk->opt.maxout" is assigned from the "pos2-aroutcnt"). As we know, the outage of measurements is very common when there is a bridge.

**Comment by nikhilbhatia123** [comment]
Hi @schumipush, 
That makes sense. Thank you so much. We will use this setting in rtkrcv and rtkpost for real-time and post-processing.

**Comment by schumipush** [comment]
The parameter "pos2-aroutcnt" is suit for real-time cases. If you got the original binex or novatel measurement file, try rtknavi.exe.
