### ISSUE TITLE
Issue reading combined broadcast ephemeris products

### ISSUE THREAD

**Issue by asymingt** [tomojitakasu/RTKLIB#63]
Hi Tomoji

I'm working on a simulator for multi-constellation GNSS. I've been trying to open combined broadcast ephemerides in RINEX 3.02 format. Here's an example of one such file:

ftp://cddis.gsfc.nasa.gov/gnss/data/campaign/mgex/daily/rinex3/2014/brdm/brdm2830.14p.Z

I've been trying to use the ```readrnx``` function in ```src/rinex.c``` to do this. I noticed that this function was returning 0 each time, so I printed out a level 5 trace and found this error.

```
2 rinex file uncompact error: /path/to/brdm2830.14p
```

This error occurs if both the uncompressed and compressed files are used. I also tried to use the ```rtconv.exe``` app to load and extract the NAV data for just GPS. I noticed that no file was produced, and so I expect the issue lies somewhere in the format of the file not being compatible with RTKLIB. 

Are there known issues with the RINEX 3.02 parser?

Thanks
Andrew

UPDATE: I neglected to mention that I am working with the rtklib_2.4.3 branch.

**Comment by tomojitakasu** [comment]
It is fixed in rtklib 2.4.3 b15.
