### ISSUE TITLE
Update MAXPRNGAL for GALILEO satellites in the rtklib.h

### ISSUE THREAD

**Issue by StefanCiesilski** [tomojitakasu/RTKLIB#652]
Hello,
can you update the MAXPRNGAL for GALILEO satellites in the rtklib.h

https://github.com/tomojitakasu/RTKLIB_bin/issues/25#issue-1195598234

Thanks

**Comment by tomojitakasu** [comment]
Use 2.4.3 b34. The constant is defined as 36 according to the current constellation.

https://www.gsc-europa.eu/system-service-status/constellation-information

**Comment by StefanCiesilski** [comment]
OK. Thanks
