### ISSUE TITLE
Static solution and not enought GPS  satellites

### ISSUE THREAD

**Issue by euge1980** [tomojitakasu/RTKLIB#656]
Dear all,
I am processing a short baseline with many satellites in common (logging 15 s). I want a static solution and RTKlib v.2.4.2 provides me with a single solution (Q:5) and says that there are only 3 satellites. There should be around 7/8 satellites. I am using broadcast orbit created with teqc from the base observation file. I am attaching the configuration file.
Can anybody help me on that?
[static_conf.txt](https://github.com/tomojitakasu/RTKLIB/files/8506708/static_conf.txt)

**Comment by euge1980** [comment]
i have solved with version 2.4.3

**Comment by ValZapod** [comment]
>that there are only 3 satellites

You can get good solution with 3 or even 2 satellities, but you need atomic clock in the room with you. Synced.
