### ISSUE TITLE
Setting up RaspberryPi Rover without a base station

### ISSUE THREAD

**Issue by Ezward** [tomojitakasu/RTKLIB#659]
I would like to use high resolution gps for autonomous scale car (rc) racing.  I have a Sparkfun F9P based gps module and an L1/L2 active antenna.  I am hoping I can achieve high precision gps coordinates without needing to purchase a second F9P board to use as a base station.  My car has a RaspberryPi with Wifi connectivity, so it is capable of connecting to an NTRIP server (we have good wifi at the track); I have several UNAVCO stations near me.  I can get a fix using my Windows PC and u-center sofware, so I know my UNAVCO credentials are working.  I would like to use RTKLIB console tools running on the RaspberryPi to take the NTRIP feed from UNAVCO and create high precision NMEA which I would consume using python code running on the RaspberryPi, reading from a serial port.  I can access the Sparkfun F9P using USB and/or two serial uarts exposed with pins (see illustration).  I have no idea how to setup the RTKLIB console apps (or even which one(s) to use) to make this happen; any help you could provide would be greatly appreciated. 

![image](https://user-images.githubusercontent.com/1163329/167347135-11011fbf-789b-4e52-8652-d3ab8324d6ba.png)

**Comment by reid-p** [comment]
With the F9P in this setup I'd just feed it RTCM and let it do it's thing.
It'll output corrected data from it's own rtk engine.

See: https://rtklibexplorer.wordpress.com/2017/06/12/real-time-solutions-with-rtklib-and-ntrip-using-a-cell-phone-as-data-link/

and the str2str command line util.

**Comment by yydgis** [comment]
use the str2str to get the rtcm data from the server and send to the F9P

**Comment by geofis** [comment]
As advised by @yydgis, use `str2str` to send RTCM corrections from the Raspberry Pi (which needs to be connected to the Internet if you plan to use UNAVCO services) to the receiver. I wrote a not so user-friendly program to do this task, repo [here](https://github.com/geofis/BashRTKStation/), "but it works".

I am now planning to use RTKBase for this task, as it uses a user-friendly interface, but since it was designed to operate bases some adaptations are needed. This is the original [repo](https://github.com/Stefal/rtkbase). I forked the original to provide support for sending corrections to the receiver.

Please, also take a look to this setup (in Spanish):

![image](https://user-images.githubusercontent.com/13460617/167396814-7348915a-6f03-405d-b730-95742922e2bc.png)
(The source of the image is this revealjs presentation: https://geofis.github.io/rtk-para-todos/#/section-3)

It is important to pay attention (double check) when connecting pins to the receiver, because the input voltage must be chosen with caution (3V3 as logical level for RX/TX communication).

**Comment by Ezward** [comment]
Here is what I have done:

Connections
FP9-UART2 is the corrections port on the Sparkfun GPS-RTK-SMA Breakout ZED-F9P
- This port is setup to input UBX, NMEA and RCTM3
- This port is setup to output RCTM3

FP9-USB port
- This port is setup to input and output UBX, NMEA and RTCM3

GPIO is the 40 GPIO bus on the SBC (RaspberryPi or Jetson Nano)
- Board pin 6 is GND
- Board pin 8 is TX for UART-2, which is serial port /dev/ttyTHS1
- Board pin 10 is RX for UART-2

```
RPi            FP9   
------------------------
Pin-6   <--->  GND
Pin-8   <--->  UART2-RX
Pin-10  <--->  UART2-TX
USB     <--->  USB
```

Software setup
- Use u-center to set the FP9 UART-2 to 230400 baud
- Set the RPi/Jetson Nano serial port to 230400 baud
`sudo stty -F /dev/ttyTHS1 clocal raw speed 230400`
- Run str2str on the RPi to get corrections from UNAVCO and send them to the FP9 via UART2
`./str2str -in ntrip://USERNAME:PASSWORD@rtgpsout.unavco.org:2101/P200_RTCM3 -out serial://ttyTHS1:230800:8:n:1`
- Read NMEA messages on USB serial port, /dev/ttyACM0

With this setup I never get to float mode on the FP9; the led says solidly lit.  Perhaps the pin connections in this setup are not correct or I need to change the messages that go in and out on F9P UART-2.

If I change this up a bit and stream the corrections to the F9P USB serial port instead of UART-2, I can float, but it never goes to fixed. 

As mention before, I can quickly get to float then fixed on my Windows PC if I connect the F9P to USB and I run u-center and setup the NTrip client settings to use UNAVCO.  This is with the same antenna in the same exact position.

Am I using str2str correctly?  Is there any particular messages or message types I have to setup?  Is there any additional settings, like base position, that I have to pass?  Does the stream between UNAVCO and F9P need to be bidirectional?

Thanks for you help, I'm much farther along then before, but not quite there.

**Comment by geofis** [comment]
Your setup looks fine. However, it seems to me that the 3V3 is missing, which is needed for the logical level to operate flawlessly (see my diagram in a previous post).

I think the UNAVCO ntrip client address is not written correctly (see my proposed spelling below). The `mailto` part may cause errors.

If you are using an RPi 3, the serial port may be at `/dev/serial0` (which is symlinked to `/dev/ttyS0` BTW), but if you are using a Jetson this may not be the case. Regarding the serial port, I also suggest using a lower baud rate, say 115200, because higher rates may not be handled correctly by the Pi, so you may need to reconfigure the UART2 baud rate of the receiver in the u-center. With the baud rate is set to 115200, the command may look like this:

```
./str2str -in ntrip://USERNAME:PASSWORD@rtgpsout.unavco.org:2101/P200_RTCM3 -out serial://serial0:115200:8:n:1
```

You may also want to check if the UNAVCO streaming is working properly. If so, use the first part of the command:

```
./str2str -in ntrip://USERNAME:PASSWORD@rtgpsout.unavco.org:2101/P200_RTCM3
```

If the streaming is OK, you should see machine characters which form the binary RTCM messages.

Please, also note that the physical UART is not directly connected to pins 8/10 in the RPi. By default, the system uses a "mini UART" in these pins and assigns the high efficiency physical UART to the Bluetooth interface. If you want reliable connection though the serial port, you may want to assign the physical UART to pins 8/10, by swapping the devices in the `/boot/config.txt` file. You may find more info in RPi Forums (serial login must be disabled too). I wrote a brief note in the installation steps (item 2) of my simple [Bash program](https://github.com/geofis/BashRTKStation/#installation).

**Comment by Ezward** [comment]
@geofis Thank you for your reply.  It is good to know I'm on the right track at least.
- I had a typo in what I pasted into the comment for the UNAVCO addres, but the code I was running had the UNAVCO address correctly as you had suggested.   I fixed the comment to reflect this.
- I am using an Nvidia Jetson Nano, so the ports above reflect that.
- I checked the UNAVCO stream and I am getting binary data and the connection is solid.  
- I will reduce the baud to 115200 and see if that helps.  That may explain why I could not get to floating using the GPIO uart but I could using the USB serial.
- As far as the 3.3v for the F9P logic, I am powering via the USB connection, so I have left off the 3.3v connection, but have kept the gnd to make sure the Jetson Nano had F9P have common ground.  That all seems to work fine.  The power light on the F9P is solidly lit.

**Comment by geofis** [comment]
@Ezward 

You're welcome.

I am not sure that the logic level is set properly by powering the board through the USB connector. If I remember correctly, I had a similar issue when I first tried to send RTCM corrections to my Sparkfun module. Everything went fine after I connected the 3V3 pin from the RPi to the 3V3 of the module.

**Comment by Ezward** [comment]
@geofis I can give it a try connecting the 3.3v.  I had another thought as well.  The ports on the FP9 (both usb and UART2) are configurated to return UBX, NMEA and RTCM3.  I'm wondering if str2str is trying to read from the port or if it just let's stuff build up unless the `-b` flag is used.  In that case the UART might get messed up because it's buffer overruns.  Should I turn off output on the port I am using to send the RTCM3 to the F9P, since it only needs to receive the RTCM3?

**Comment by geofis** [comment]
@Ezward 

The `-b` flag is worth a try. Anyway, I guess that when the receiver sends outputs through a port, if the SBC (in your case, the Jetson) does not receive them, the buffer won't be overloaded. I remember once trying to receive raw UBX data and simultaneously send RTCM corrections (using another process) over the same port, and this did indeed overload the buffer to the point of preventing the receiver from computing fixed solutions.

Another thing to check is the current reaching the Jetson. In my case, I once designed a circuit providing less than 1A to the RPi 3, and this caused a voltage drop of 0.4V, enough to reduce the SBC performance, which eventually prevented corrections from reaching the receiver.

**Comment by Ezward** [comment]
@geofis I got a fix on the Jetson Nano by streaming RTCM3 to the USB serial port and reading the NMEA from UART2.  In 100 samples I got range of 2.5 cm.  So there is some issue with how UART2 is setup on the F9P module; if I use that to send the RTCM3 to the module then I never even get to float; but I can read NMEA from it fine.  Well, I have a solution for now; I can do some tests later to figure out the UART2/RTCM3 issues.  This is what worked;
- `./str2str -in ntrip://USERNAME:PASSWORD@rtgpsout.unavco.org:2101/P200_RTCM3 -out serial://ttyACM0:230400:8:n:1`
- Then read NMEA messages from `/dev/ttyTHS1`  

Thank you for all of your help.

**Comment by Ezward** [comment]
More findings:

**Jetson Nano**
I have found that the UART on the GPIO bus (gpio 14&15 exposed on board pins 8&10 respectively) to be unreliable for receiving RTCM3 corrections; when I use it to receive RCTM3 the F9P never goes to float, let alone fixed.  However, if I use the USB serial port to send RTCM3 corrections to the F9P, then I can get to float and eventually get to fixed.  I seem to be able to read NMEA reliably from the GPIO serial port.  So any solution using the Jetson Nano  will involve sending RTCM3 to the F9P via the USB port.

NOTE: it's possible that I've forgotten to disable the serial console in some of my sessions, which will mess things up because the serial console uses the GPIO serial port.  That would interfere with any other communication.  The serial console can be disabled iin each session by stopping it's service:
`$ systemctl stop nvgetty `
To make this permanent (which messes up logging in via ssh, so I don't recommend it)
```
$ systemctl stop nvgetty
$ systemctl disable nvgetty
$ udevadm trigger
```
In the field I will not always be getting RTCM3 corrections over the internet; sometimes I will need a radio, like a LoRa radio, to receive corrections from a local broadcast base station.  It is common to connect that directly to the corrections serial port on the F9P (uart2), in which case I would not even need to send corrections from the Jetson Nano; then I can read NMEA via USB.

However, if I am in a place where I want to use an NTRIP server, but I don't have good fixed internet, then I will need another option.  There are a few I could use;
Use an Android NTRIP client on my phone and a bluetooth receiver attached to the corrections port on the FP9.  The Android NTRIP client would receive the corrections via the mobile internet connection, then broadcast them over bluetooth to the receiver attached to the F9P corrections port.
Similarly, use an Android NTRIP client, but pair it with the bluetooth on the Nano, then route it to USB.  We then read NMEA from the gpio serial.

**Raspberry Pi 4**
I have found that the UART exposed on the GPIO bus (gpio 14&15 exposed on board pins 8&10 respectively) to be unreliable at higher baud rates; it is not based on a hardware UART and so is more prone to issues at higher speeds.  By default the RPi uses two UARTs; one for the bluetooth functionality and one for the GPIO serial port.  The BT uart uses underlying hardware and so can handle very high baud rates.  The UART exposed on the GPIO bus is less capable.  Luckily the RPi 4 actually has 6 hardware-based UARTS. We can expose these by using device-tree overlays.  The device tree is data that is loaded at boot time that tells Linux which devices are attached and so which drivers to load.  A device tree overlay (dtoverlay) is a way of adding to the device tree without having to create a whole new one.  RasberryPi OS has a bunch of available dtoverlays that can be used to turn on optional features.  We can list the ones that have to do with UARTs (see this RPi forum discussion)

```
$ dtoverlay -a | grep uart
  midi-uart0
  midi-uart1
  miniuart-bt
  uart0
  uart1
  uart2
  uart3
  uart4
  uart5
```

Add this in the /boot/config.txt in the [pi4] section (you will need to sudo) to enable uart3 using defaults, then reboot.
```
# Enable UART3 on gpio 4=tx & 5=rx, no flow control pins
dtoverlay=uart3
```

Once that is done, then the serial device /dev/ttyAMA1 can be used to control the UART exposed on gpio 4&5, which are exposed on the 40 pin bus on board pin 7 and board pin 29 respectively
