### ISSUE TITLE
One mistake in nmf function in rtcmn.c

### ISSUE THREAD

**Issue by jstzzym2020** [tomojitakasu/RTKLIB#666]
Hello!
I've been reading source code of precise positioning these days .I found that function named 'nmf' about the Niell Mapping Function may be have a mistake in its formula.
Looking at nmf function in rtkcmn.c file,there's minus sign between the average part of the coefficient a and the amplitude part of the coefficient a as below.
![image](https://user-images.githubusercontent.com/70496047/175190090-032a2a40-9574-46d5-99b4-30111066148a.png)

However,the reference paper published in 1996 by A.E.Niell shows there should be a plus sign as below.
![image](https://user-images.githubusercontent.com/70496047/175190331-f6770de7-05e3-469a-9cbe-0eb1151401ee.png)
[1]A. E. Niell, Global mapping functions for the atmosphere delay at radio wavelengths, Journal of
geophysical research, 1996

And in a report by Mendez,there is also a plus sign in it as below.
![image](https://user-images.githubusercontent.com/70496047/175191220-35996b47-d587-4771-a01c-4098b88f3eab.png)
[2]Mendes V B. Modeling the neutral-atmospheric propagation delay in radiometric space techniques[J]. UNB geodesy and geomatics engineering technical report, 1999 (199).

I don't know whether the difference in nmf function is a mistake or something else.I hope someone can answer my question.

Best regards
Yumin

**Comment by tomojitakasu** [comment]
The original JGR paper of NMF has well-known errata in eq. (4) and (5).

The corrected version is attached.

[niell_jgr_1996.pdf](https://github.com/tomojitakasu/RTKLIB/files/8963152/niell_jgr_1996.pdf)

**Comment by jstzzym2020** [comment]
Thank you sincerely for your reply and guidance！



At 2022-06-23 10:36:01, "Tomoji Takasu" ***@***.***> wrote:

The original JGR paper of NMF has well-known errata in eq. (4) and (5).

The corrected version is attached.

niell_jgr_1996.pdf
