### ISSUE TITLE
NMEA GGA FIX FLAG

### ISSUE THREAD

**Issue by zuliani71** [tomojitakasu/RTKLIB#68]
Dear all, I'm running rtklib between 1 GNSS permanent sites and a VRS generated by our network software, more or less as described at:
https://github.com/tomojitakasu/RTKLIB/issues/35
I've solved some of the problems using the patch described at:
https://github.com/tomojitakasu/RTKLIB/issues/37

now I get a fix very quickly but I've noticed that the GGA sentence generated by the rover is not correctly parsed by rtklib. Looking at the  Input Streams menù of rtklib I found the "Transmit NMEA GPGGA to base station" popup and I set it to "Single Solution". That string is generated by the rover and usually used but most of the VRS casters to yeld a correct solution for the requesting rover. Further more the GPGGA Fix Quality field is used by the caster to understand if the rover has been able to fix the solution. What I think is that rtklib just handles/parses the coordinate fields avoiding the "Fix Quality" flag which remains 1=GPS SPS mode even if the rover has a FIX 4=RTK with fixed ambiguities.

Is it possible to implement the Fix Quality feature inside the GPGGA sentence? My be I've miss a patch about it. Can you help me?

Bye David

**Comment by tomojitakasu** [comment]
Transmitting NMEA is done by strsendnmea() in rtklib/src/stream.c (L2155). In the function, the solution status is always set to SOLQ_SINGLE. So the quality flag in the sentence is always set to 1 = gps fix (sps). (see outnmea_gga() in rtklib/src/solution.c L1061, L56).

**Comment by zuliani71** [comment]
Ok, thanks. Do you think to implement a full working quality flag in the next versions of rtklib?
Thanks

**Comment by zuliani71** [comment]
Can I suggest to implement the correct value of the FIX flag value?
