### ISSUE TITLE
Ublox Firmware update broke convbin.exe

### ISSUE THREAD

**Issue by Dan-Martin512** [tomojitakasu/RTKLIB#700]
I have been using the latest convbin.exe (2.4.3 b34) build to generate RINEX data from Ublox F9T receivers, it would seem that with Ublox new firmware update convbin is now not working fully for at least Galileo RINEX (seems to work on GPS still), any ideas on if this will be worked on or pointers on where to look in the source code to start on this issue?

**Comment by Stefal** [comment]
Maybe related to https://github.com/rtklibexplorer/RTKLIB/commit/4df03b9afe62a1c882a2800eac19e3f4627df293

**Comment by Dan-Martin512** [comment]
Thanks @Stefal, I made that change localy and it does seem to work
