### ISSUE TITLE
convbin different results than rtkconv gui

### ISSUE THREAD

**Issue by arknoll** [tomojitakasu/RTKLIB#707]
Converting rtcm3 data to RINEX:

Problem:
convbin has incorrect date

steps to reproduce:
use rtkconv gui on a rtcm3 file and use all the default options. The rtcm3 file is scanned as you would expect (2023/01/29 00:00:00-01/29 21:49:01)

When running the same rtcm3 file through convbin I get the following:
convbin /root/output/merged.rtcm3
input file  : /root/output/merged.rtcm3 (RTCM 3)
->rinex obs : /root/output/merged.obs
->rinex nav : /root/output/merged.nav
->sbas log  : /root/output/merged.sbs

scanning: 2023/02/05 21:49:01 GREC
2023/02/05 00:00:18-02/05 21:49:01: O=73723 N=429 E=33

The RINEX file is generated with convbin, but all the dates are incorrect (in the future by several days)

**Comment by yydgis** [comment]
use convbin -r rtcm3 -tr 2023/1/29 0:0:0 filename
or you can use convbin --help to get  more details on how to use it

**Comment by tomojitakasu** [comment]
Use -tr option for RTCM3 (refer the manual A.4).

https://www.rtklib.com/prog/manual_2.4.2.pdf

**Comment by arknoll** [comment]
Thank you. Yep, I just figured it out as well. Appreciate it!
