### ISSUE TITLE
java：Data cannot be obtained by forwarding with NTRIP Server

### ISSUE THREAD

**Issue by YiMoWanXia** [tomojitakasu/RTKLIB#719]
#### I wrote a server to get the data and now only receive the following message: 

```
SOURCE 1 RTCM33_GRCEJ
Source-Agent: NTRIP RTKLIB/2.4.2
STR:
```

The output to the file is fine, the reception through the socket is empty, if I want the socket to receive what should be changed? Here is the main code:

```java
BufferedReader reader = 
    new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
String request = reader.readLine();

while (StrUtil.isNotBlank(request)) {
    System.out.println(request);
    request = reader.readLine();
}

```

**Comment by changan1231231** [comment]
> #### 我写了一个服务器来获取数据，现在只收到以下消息：
> ```
> SOURCE 1 RTCM33_GRCEJ
> Source-Agent: NTRIP RTKLIB/2.4.2
> STR:
> ```
> 
> #### 输出到文件是正常的，请帮忙看看是什么问题，下面是主要代码：
> ```java
> BufferedReader reader = 
>     new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
> String request = reader.readLine();
> 
> while (StrUtil.isNotBlank(request)) {
>     System.out.println(request);
>     request = reader.readLine();
> }
> ```
