### ISSUE TITLE
Does rtkpos use INS data ?

### ISSUE THREAD

**Issue by melikekaymak** [tomojitakasu/RTKLIB#722]
Can I post process the RTK measurement I made with GNSS and INS sensors with rtkpos? Can I use both data at the same time?

**Comment by Imtiaz08** [comment]
> Can I post process the RTK measurement I made with GNSS and INS sensors with rtkpos? Can I use both data at the same time?

I don't think so

**Comment by SquirrelKnight** [comment]
No, RTKlib is strictly for GNSS data. INS sensor support would be awesome! I've dabbled in a few attempts of my own but have been less than pleased with my results :(
