### ISSUE TITLE
ver2.4.3 got no positions when using Kinematic Mode

### ISSUE THREAD

**Issue by zvictorliu** [tomojitakasu/RTKLIB#730]
Hi~
I am excuting ver2.4.3 RTKPOST but it doesn't have results:
![image](https://github.com/tomojitakasu/RTKLIB/assets/93273685/7ec549f3-8f13-480b-89ff-46d1f92029c3)

However, if using ver2.4.2 then it works...
![image](https://github.com/tomojitakasu/RTKLIB/assets/93273685/b7fa527e-48b2-4a7b-a848-f6706558ca5f)

The configuration is the same( 2.4.3 rtk.conf)
Is there compatibillity requirement?

**Comment by zvictorliu** [comment]
Solved! The base station position should be checked in config file.

**Comment by yydgis** [comment]
you do not set the base station coordinate.
