### ISSUE TITLE
Creating 2 directory level

### ISSUE THREAD

**Issue by Matioupi** [tomojitakasu/RTKLIB#74]
Hello,

rtknavi (I guess it's same with other tools) fails when it has to create more than one directory in a raw 
with output path such as  C:\Users\Mathieu\Documents\RTKLIB\log\%Y\%n\chbx%n%H.gps

creating one directory level is Ok

Regards

**Comment by tomojitakasu** [comment]
That's a limitation of current version.
The API createdir() does not support recursive generation of directories. It will be improved in future versions.
