### ISSUE TITLE
Process cycle (ms) >= 1001 causes crash.

### ISSUE THREAD

**Issue by nunojpg** [tomojitakasu/RTKLIB#76]
If Process cycle is set to 1001, as soon as Start is pressed, RTKNAVI crashes.

Happens to both Master and rtklib_2.4.3.

**Comment by tomojitakasu** [comment]
Thanks.
It seems due to zero-divide exception at L458 of rtklib/src/srtsvr.c.
It will be fixed in next release.

**Comment by tomojitakasu** [comment]
It is fixed in rtklib 2.4.3 b24.
