### ISSUE TITLE
Upcoming leap second

### ISSUE THREAD

**Issue by Matioupi** [tomojitakasu/RTKLIB#77]
RTKLIB\src\rtkcmn.c is missing the additonnal leap second that will be introduced on 2015 july 1st

**Comment by tomojitakasu** [comment]
Apply 2.4.2 p11.

**Comment by Matioupi** [comment]
I was reviewing branch 2.4.3...

**Comment by tomojitakasu** [comment]
It is fixed in 2.4.3 b6.
