### ISSUE TITLE
VRS RTCM3 streams not recognized

### ISSUE THREAD

**Issue by zuliani71** [tomojitakasu/RTKLIB#81]
Dear all
I'm trying an experiment working with a VRS streamed out on RTCM3 format. I've log the stream and then I've tried to convert it to RINEX using RTKCONV but inside no data just the RINEX header. I've made the same with VRS RTCM2.3 and I got the right RINEX with the observations inside. Can you help me?

**Comment by tomojitakasu** [comment]
Send a sample log of RTCM 3 to the support address.

rtklib_support@gpspp.sakura.ne.jp

**Comment by zuliani71** [comment]
Ok done.

**Comment by tomojitakasu** [comment]
Thanks.
The log includes RTCM MT 1003 and 1011 (GPS and GLONASS Compact L1/L2 OBS). The current version RTKLIB does not support decode of these messages. See the manual D.2.

**Comment by zuliani71** [comment]
Dear Tomoji

thanks for the answer, I’m sorry to have bothered you with a question easily
solvable by reading carefully the manual.

Bye

David


Il giorno 22/apr/2015, alle ore 18:14, Tomoji Takasu <notifications@github.com> ha scritto:

> Thanks.
> The log includes RTCM MT 1003 and 1011 (GPS and GLONASS Compact L1/L2 OBS). The current version RTKLIB does not support decode of these messages. See the manual D.2.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Ing. David Zuliani
Istituto Nazionale di Oceanografia e di Geofisica Sperimentale - OGS
dept: Centro di Ricerche Sismologiche - CRS
Via Treviso, 55 - 33100 Cussignacco UDINE Italy
ph.  +39 0432 522433
fax  +39 0432 522474
E-mail: dzuliani@inogs.it
