### ISSUE TITLE
rtkrcv ublox-m8t can't get solution

### ISSUE THREAD

**Issue by Tep-S** [tomojitakasu/RTKLIB#82]
Couldn't get any solution in rtkrcv. with the same option in rtkNavi everything work quite well. I check data in obs and nav they are the same on ubuntu and windows. What i should check? 
By the way, i didn't know how to set in rtkrcv snrmask= 0 so i wrote snrmask = 0.

**Comment by Yorik-Code** [comment]
Hello

I have a NEO-M8T as well. I might not be able to help directly, but maybe I can recreate the fault. Can I ask the following:
-What version of RTKLIB are you running?
-What Position Mode are you using?
-What RAW Messages are you outputting from your M8T?
-What is your rtrcv command in full?

That will be a good place to start.

**Comment by Tep-S** [comment]
Thanks, I'm already solve the problem, it was my fault that i didn't check everything well, in my config file by default was option precise ephemerid, but i get them from broadcast.

**Comment by nopeppermint** [comment]
@Tep-S as you are also using rtkrcv, could you maybe provide some help here https://github.com/tomojitakasu/RTKLIB/issues/84

**Comment by bszdev** [comment]
Hello!
Can somebody help me?
I try to use a NEO-M8T module with an Ntrip base server but i can't get FIX solution in the rtknavi. I get SINGLE solution only.

I set the following things:
**u-center:** RXM-RAWX, RXM-SFRBX
**rtknavi:** Rover(serial port) u-blox format, Base station(NTRIP client) RTCM3 format, Position mode is kinematic.

I connect device via USB port and I use a high performance active GPS antenna.

In the error/warning list i receive continously **"no base station observation data for rtk"** and **"point pos error (chi-square error nv=9 vv=16.2 cs=13.8)"** messages.

What do i do wrong?

Thank you!
