### ISSUE TITLE
E/N/U baseline projection

### ISSUE THREAD

**Issue by zuliani71** [tomojitakasu/RTKLIB#85]
Dear all
looking at the solutions produced by rtklib I find something uncomplete about the E/N/U‐Baseline format.
Which is the projection used to yeld this kind of baseline? I've tried to calculate the baseline components in the UTM projection starting from MASTER-ROVER geographic coordinates (Lat/Lon/Height) produced with rtklib. Comparing those coordinate with the same coordinates reported by the rtklib E/NU-Baseline format the result is very different even if the baseline lengths are the same.

**Comment by forrestv** [comment]
It isn't UTM ... it's ENU. It's a coordinate system with (0, 0, 0) being at the master, +x being east from there, +y being north from there, and +z being up from there, presumably according to the selected reference ellipsoid.

**Comment by zuliani71** [comment]
Ok, what it's clear is that ENU are the COMPONENTS of the baseline between master and rover in a some sort of coordiante system which is local. In any way that components are a function of the ECEF (or a function of the geodetic) coordinates of master and rover (and also depend on the adopted ellipsoid) and that function is crucial if you want to compare baseline components produced by different softwares. When I've mentioned UTM I've also told that I'm comparing the components of the baseline produced by rtklib against the UTM baseline components (also in that last case I've removed the master coordinates from the rover to get the components from the master) and anyway they differ.
Currently I'm tring to compare the baseline components produced using rtklib and gamit/globk (which is another GNSS software). Unfortunately gamit/globk has it's own local coordinate system (a usually refered to the master so the master coordinates are (0,0,0) ) as rtklib has it's own. For that reason, the NEU components of rtklib and gamit are different (also of tens of meters) even if the baseline lengths are clearly more or less the same (in my current solutions gamit/globk and rtklib baseline length differ for some mm).  What do you think?
