### ISSUE TITLE
How does rtknavi.exe time mark RTCM3 observations obtained over TCP?

### ISSUE THREAD

**Issue by asymingt** [tomojitakasu/RTKLIB#86]
Hi Tomoji

I am working on a simulator for GNSS. I have calculated pseudorange measurements for a given point in time ```t``` and stream them in RTCM3 over a TCP socket to ```rtknavi```. What I have noticed is that the ```Trcv``` column in observable log seems to have a different time than what I'm putting into my ```obs_t``` struct before encoding and sensing the frame:

The general idea is as follows:

```c
rtcm_t   rtcm;
stream_t stream;
obsd_t   obs;

// Populate RTCM with header data
// Setup TCP stream
// Populate OBS with pseudorange, and  time as below
obs.time = gpst2time(1813, 61714.285714286);

// Add OBS to RTCM 
addobsdata(&(rtcm.obs), &obs);

// Generate a RTCM3 message
gen_rtcm3(&rtcm, 1019, 1);

// Write the message to the stream
strwrite(&stream, rtcm.buff, rtcm.nbyte)
```

Is there some other way that the observation time should be set, or does it use a different representation than I am using?

Thanks
Andrew

**Comment by tomojitakasu** [comment]
You might need to set rtcm->time for observation message time in RTCM.

**Comment by asymingt** [comment]
I did actually try that. In fact, I set both rtcm->time and rtcm->time_s immediately prior to calling gen_rtcm3.  ie. I tried hard-coding the values:

```
      rtcm.obsflag = 1;
      rtcm.time   = gpst2time(1813,432000.0);
      rtcm.time_s = gpst2time(1813,432000.0);
      if (!gen_rtcm3(&rtcm, 1002, 1))
```

However, rtknavi replaces the observable time with 2015/05/15 00:00:00 (midnight today). It's like there is some system call in the rtcm3 decoder that resets the time to seconds relative to the start of the current day. Weird!

**Comment by tomojitakasu** [comment]
It's just due to a RTCM format limitation. RTCM messages does not contain week (for GPS) or date (for GLONASS) information in any field. So RTKLIB completes them by using current CPU time when the first OBS message arrived. It is not a problem with usual real-time stream. But in simulation or playback, you might have a trouble.There is no easy way to handle that except for manipulating the CPU time.

**Comment by asymingt** [comment]
Thank you -- that is exactly what I needed to know, and completely explains the issue I was seeing. I really appreciate your help.
