### ISSUE TITLE
RTKPOST sp3 file no nav data

### ISSUE THREAD

**Issue by zuliani71** [tomojitakasu/RTKLIB#87]
Dear all,
I'm using rtkpost to calculate a baseline between two sites. For both of them I've the RINEX observable files but no nav data. For the satellite orbits I'm using a precise sp3 file provided by IGS, and I've selected the "Precise ephemeris satellite/clock" inside rtkpost options . When I run execute I've the "no nav data" message and rtkpost suddely stops. I've tried rtkpsot 2.4.2, 2.4.2_p11 and rtkpost 2.4.3. All of them gave me the same result. Can anybody help me?

**Comment by tomojitakasu** [comment]
RINEX NAV is always needed even with precise ephemeris and clocks. It's used to recognize unhealthy satellites.

**Comment by zuliani71** [comment]
Ok great, thanks. I've been able to recover nav data for at least one of the cited sites. I've put both glonass and gps nav files inside the directory containing the RINEX observables. Currently I'm able to see just the GPS skyplots even if Sat Vis is for both GPS and GLONASS. GLONASS Sat Vis is anyway gray for all satellites. Is it correct?
And... How to understand if rtkpost is using nav file or sp3 orbits for its elaboration?

**Comment by avkonst** [comment]
Probably beginner's question, but there do you get NAV file from? I have got obs for my rover and base station. I can not figure out where NAV file should come from. Thanks for a hint!

**Comment by geofis** [comment]
@avkonst 

Hello. 

The navigation data is usually included in the raw file generated by your receiver, as long as you configured the receiver to do so.

I am not familiar with the GUI, but in the CUI you may run...

`convbin rawobservations`

...where `rawobservations` is your receiver's raw data filename. The command will output both `.obs` and `.*nav` files. Depending on the RINEX format selected, you'll get multiple NAV files, or only a single one.

Also, I would suggest you to post a question in forums, since you will reach a broader audience.

Best

**Comment by CGEOS** [comment]
*Hi Andrey,*

Very much simple indeed at the NAV files has to be input just below the
rover/base and you have to use "*" on the extension to ensure GPS, GLONASS
and other constellations ephemeris will be taken into account.

If you look on the RTK-LIB User Guide, it's detailed.

All best regards,

*Prof. Joël van Cranenbroeck *

Managing Director CGEOS - CREATIVE GEOSENSING SPRL
Rue du Tienne de Mont, 11 at 5530 MONT, YVOIR
Belgium - EUROPE

Tel +32 81 41 36 57
Mobile +32 474 98 61 93
Web site : www.cgeos.com

Confidentiality Notice: This message (including attachments) is a private
communication solely for use of the intended recipient(s). If you are not
the intended recipient(s) or believe you received this message in error,
notify the sender immediately and then delete this message. Any other use,
retention, dissemination or copying is prohibited and may be a violation of
law, including the Electronic Communication Privacy Act of 1986.
