### ISSUE TITLE
RTK (Kinematic mode) with RTKLIB

### ISSUE THREAD

**Issue by Ebi10** [tomojitakasu/RTKLIB#95]
Hello !

This is my real first time to use rtklib, and I met some difficulties which I hope to dispel through this issue. Indeed, there's little I realized a measurement campaign with uBlox neo 7p as the rover., and a novatel as the base station. After, I try to post-process these data by using RTKPOST, so I converted my recorded data to RINEX format using RTKCONV. But, I realize that it's impossible for me to have a RTK (Kinematic mode) post-processing. Everytime I choose "Kinematic" like post-processing mode, it performs single position until the end. First, I believed that it's due to my data, but I realize that even by  trying to use the data of the rtklib tutorial (after converting them to rinex format), I'm confronted to the same results. So, may someone help me and tell me what's wrong with what I do ??

Thank you

**Comment by tomojitakasu** [comment]
Check the base station position properly set for baseline modes.
(It's the most FAQ)
