### ISSUE TITLE
Importance of checking "Time" in Kinematic (RTKNAVI)

### ISSUE THREAD

**Issue by Ebi10** [tomojitakasu/RTKLIB#96]
Hello

Why RTK (Kinematic) doesn't work when the time is not checked in RTKNAVI configurations (It provided single position solutions) ?

**Comment by nopeppermint** [comment]
@Ebi10 what do you mean with "the time is not checked" ?

**Comment by Ebi10** [comment]
here is a screenshot to better illustrate ..
![capture](https://cloud.githubusercontent.com/assets/13016766/8306364/b4bfb23a-19b7-11e5-8f0e-60d3bf7ef6ca.JPG)

**Comment by nopeppermint** [comment]
Sorry, I don't know. If it works with the checked "Time" why you use it without?

**Comment by Ebi10** [comment]
because when you check it, you have to provide time tag files (and I don't have them, I don't even know how to get them) !!!

**Comment by tomojitakasu** [comment]
You need the time-tag file to replay a log file in the current release.
Otherwise, use RTKPOST after converting the log to RINEX.
