### ISSUE TITLE
Inserting the recent Leap Second into rtklib/src/rtkcmn.c.logic. 

### ISSUE THREAD

**Issue by DavidKelleySCSC** [tomojitakasu/RTKLIB#97]
[Posted July 1st when I noticed I was using several older copies of RTKLIB...]

Can we get yesterday's Leap Sec event added and then the Borlan code re-spun for the windows side? Know how to fix this in the raw code, but the RTKLIB GUI is a great tool for every day use.
I am somewhat embarrassed to say I can not update and build the Windows GUI tools here. If I am just behind the times and this was added earlier this year then please just please let me know what release point it was point in at.  I do not see it int he revision histories. [And I also just miss posted this on a dead thread, very sorry.] 

>>From tomojitakasu
>>The current version handles the leap seconds by using a hard-coded UTC-GPST table in rtklib/src/rtkcmn.c.

const static double leaps[][7]={ /* leap seconds {y,m,d,h,m,s,utc-gpst,...} */
   Please Add: --> (2015,7,0,0,0, -17) <--
   {2012,7,1,0,0,0,-16},
   {2009,1,1,0,0,0,-15},
   {2006,1,1,0,0,0,-14}, . . .

**Comment by tomojitakasu** [comment]
Use APs in the latest patch (2.4.2 p11).

**Comment by DavidKelleySCSC** [comment]
Got it, and with those the time issue is resolved.  

In the absence of the patch for the last leap second I see, [but only in streams that have both GPS AND GLO observation sets], some strange things that do not make sense to me.  And if I turn off the GLO stream (msgs 1012 and 1019 to be specific) from my ref station it goes away.  There seems to be more than just time involved here.  I have not tracked into this line by line but is seems that the GPS SVs are not being decoded with the correct IDs and hence the nav filter things it has no valid data.  Is there perhaps some aspect of the 2.4.3 design where the decoding of the GLO message could corrupt the GPS SV values due to the common use of rtcm_t?  This sounds crazy to even suggest, but your are the person to ask.

**Comment by tomojitakasu** [comment]
The time-tag of GLO RTCM messages is based on UTC. Without proper leap-second handling, the RTKLIB RTCM decoder discards messages prior to GLO due to time-tag miss-match.
In the current version, The leap-second handling is implemented by a hard-coded UTC-GPST table. So users have to update the version before new leap-second insertion. In future releases, some leap-second table file will be introduced in order to avoid such a bothersome procedure. 
I'm not sure the problem of improper GPS SV-ID decoding without GLO. It may be due to some bugs.

**Comment by DavidKelleySCSC** [comment]
Takasu san:
    On LS time loading:  So this might be easily handled with a small
    call to load from a file during the start up sequence, and then use
    the hard coded table if that file was not found.  It would be easier
    to do this if the table was treated as a pointer on the heap rather
    than in line, then the code could more easily dynamically allocate
    the array size.  If I produced a fragment to do this later in a week
    or so, would it be of use to you?  Where would you recommend placing
    the call to build the array, as we do not have a traditional
    constructor to use here. 
    
    On incorrect SV IDs:  I will need to sit down with the programmer to
    get to the bottom of this one, it seems likely you code base was
    misused in some subtle way that the LS plus the flow of GLO message
    brought out.  If I find anything in RTKLIB will report back. 
    
    On 7/3/2015 4:07 PM, Tomoji Takasu
      wrote:
    
    
      The time-tag of GLO RTCM messages is based on UTC. Without
        proper leap-second handling, the RTKLIB RTCM decoder discards
        messages prior to GLO due to time-tag miss-match.
        In the current version, The leap-second handling is implemented
        by a hard-coded UTC-GPST table. So users have to update the
        version before new leap-second insertion. In future releases,
        some leap-second table file will be introduced in order to avoid
        such a bothersome procedure. 
        I'm not sure the problem of improper GPS SV-ID decoding without
        GLO. It may be due to some bugs.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
Regards,
David Kelley
ITS Programs Manager
SubCarrier Systems Corp. (SCSC)
1833 East Foothill Blvd. Glendora, CA USA  91741
626-485-7528 (Cell)      888-950-8747 (Main)
626-513-7715 (Office)    888-613-0757 (Fax)
<DavidKelley@ITSware.net>

**Comment by CGEOS** [comment]
I am very embarrassed  that I can only track GLO satellites and no more any GPS. Can you help me ? I am deploying a big project and without RTK-LIB working as before the 30th of June, I will feel very bad. Many thanks to inform me on what is happening ? Best regards, Joel

**Comment by CGEOS** [comment]
Back to my previous comment here is what I got ... So
![capture1](https://cloud.githubusercontent.com/assets/13218177/8546378/a67022e0-24b7-11e5-856f-afef7f56d16c.PNG)
![capture2](https://cloud.githubusercontent.com/assets/13218177/8546379/a670c66e-24b7-11e5-89a9-630463c38c23.PNG)

 many thanks for any support !!!

**Comment by CGEOS** [comment]
while both receivers are tracking all satellites (GPS and GLO) in view ...

**Comment by DavidKelleySCSC** [comment]
Joel:

I really have no idea.  When I took the same version/release here and 
tried it - it is working fine from here.  See image below. Those mount 
points are public, so feel free to to try them from your end if you 
wish.  Perhaps in that way you can determine if the root issue come from 
RTKLIB or from your caster sources.



At a guess, I bet your caster source is the issue due to the leap second 
and perhaps a restart there will make the issues go away.  I would then 
capture that data into RTCM and see what might be up. Pay close 
attention to the time stamps for each measurement epoch.

Regards,   David Kelley

**Comment by DavidKelleySCSC** [comment]
Sorry the png got suppressed when I replied by email, here it is
![gps_glo_working in r11](https://cloud.githubusercontent.com/assets/5143060/8549231/8c9ae0fa-247e-11e5-941f-f43485f114d8.png)

**Comment by CGEOS** [comment]
Dear David,
Many thanks for your feedback and indeed I got a problem with some RTCM settings (don't know why it moved away but I reset them and got back on marvellous results !) Greetings from Belgium !

**Comment by CGEOS** [comment]
![capture3](https://cloud.githubusercontent.com/assets/13218177/8555164/7c27858c-24ee-11e5-9a3b-61357134d1fa.PNG)
